# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ALFA\Desktop\Applications\energy\UI\Energy_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os , pandas as p

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(288, 340)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Program Files (x86)/Real/Images/electricy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-140, -10, 601, 351))
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Program Files (x86)/Real/Images/energy.png"))
        self.label.setObjectName("label")
        self.btn_automode = QtWidgets.QPushButton(Form)
        self.btn_automode.setGeometry(QtCore.QRect(30, 80, 231, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_automode.setFont(font)
        self.btn_automode.setStyleSheet("color : white;background-color : gray; border-radius : 20")
        self.btn_automode.setObjectName("btn_automode")
        self.btn_manualmode = QtWidgets.QPushButton(Form)
        self.btn_manualmode.setGeometry(QtCore.QRect(28, 130, 231, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_manualmode.setFont(font)
        self.btn_manualmode.setStyleSheet("color : white;background-color : gray; border-radius : 20")
        self.btn_manualmode.setObjectName("btn_manualmode")
        self.btn_analys = QtWidgets.QPushButton(Form)
        self.btn_analys.setGeometry(QtCore.QRect(28, 180, 231, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_analys.setFont(font)
        self.btn_analys.setStyleSheet("color : white;background-color : gray; border-radius : 20")
        self.btn_analys.setObjectName("btn_analys")
        self.btn_removedata = QtWidgets.QPushButton(Form)
        self.btn_removedata.setGeometry(QtCore.QRect(28, 230, 231, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_removedata.setFont(font)
        self.btn_removedata.setStyleSheet("color : white;background-color : gray; border-radius : 20")
        self.btn_removedata.setObjectName("btn_removedata")
        self.btn_exit = QtWidgets.QPushButton(Form)
        self.btn_exit.setGeometry(QtCore.QRect(98, 280, 91, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("color : white;background-color : navy; border-radius : 20")
        self.btn_exit.setObjectName("btn_exit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color : yellow ; border-radius : 20; color : gray")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color : white ; border-radius : 25")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Program Files (x86)/Real/Images/electricy.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.btn_abotus = QtWidgets.QPushButton(Form)
        self.btn_abotus.setGeometry(QtCore.QRect(250, 300, 41, 41))
        self.btn_abotus.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Program Files (x86)/Real/Images/icons8-about-us-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abotus.setIcon(icon1)
        self.btn_abotus.setIconSize(QtCore.QSize(32, 32))
        self.btn_abotus.setFlat(True)
        self.btn_abotus.setObjectName("btn_abotus")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.btn_automode.raise_()
        self.btn_manualmode.raise_()
        self.btn_analys.raise_()
        self.btn_removedata.raise_()
        self.btn_exit.raise_()
        self.btn_abotus.raise_()

        self.btn_analys.clicked.connect(self.analys_data)
        self.btn_automode.clicked.connect(self.energy_auto)
        self.btn_manualmode.clicked.connect(self.energy_manual)
        self.btn_exit.clicked.connect(self.exit)
        self.btn_abotus.clicked.connect(self.about_us)
        self.btn_removedata.clicked.connect(self.resetdata)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Energy Analys System"))
        self.btn_automode.setText(_translate("Form", "حالت خودکار (آنلاین)"))
        self.btn_automode.setShortcut(_translate("Form", "1"))
        self.btn_manualmode.setText(_translate("Form", "حالت دستی   (آفلاین)"))
        self.btn_manualmode.setShortcut(_translate("Form", "2"))
        self.btn_analys.setText(_translate("Form", "تجزیه اطلاعات و نمایش نمودار"))
        self.btn_analys.setShortcut(_translate("Form", "3"))
        self.btn_removedata.setText(_translate("Form", "حذف اطلاعات"))
        self.btn_removedata.setShortcut(_translate("Form", "4"))
        self.btn_exit.setText(_translate("Form", "خروج"))
        self.btn_exit.setShortcut(_translate("Form", "Esc"))
        self.label_2.setText(_translate("Form", "         سیستم آنالیز انرژِی"))

    def analys_data (self) :
        Form.close()
        os.system("streamlit run c:/Users/ALFA/Desktop/Applications/energy/Codes/energy.py")
        
    def energy_auto (self) :
            Form.close()
            os.system("python C:/Users/ALFA/Desktop/Applications/energy/Codes/Energy_auto.py")
            
    def energy_manual (self) :
        Form.close()
        os.system("python C:/Users/ALFA/Desktop/Applications/energy/Codes/Energy_manual.py")
    
    def about_us (self) :
        Form.close()
        os.system("python C:/Users/ALFA/Desktop/Applications/energy/Codes/About_us.py")
    
    def resetdata (self) :
        filepath = "C:/Users/ALFA/Desktop/Applications/energy/panda inserting/energy_data.csv"
        file = p.read_csv(filepath)
        file = p.DataFrame()
        file["Date"] = None
        file["Consumption"] = None
        file["Temperature"] = None
        file["Humidity"] = None
        file["Hour"] = None
        file["Month"] = None
        file.to_csv(filepath , index=False)
        
    def exit (self) :
            Form.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())