# -*- coding: utf-8 -*-
"""resizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVCF-_UI0-MeYTJUMPpNmcvPUTPivdcA
"""

# prompt: now how do I make it a .exe file?

# You will need to save this code as a Python file (e.g., resizer.py)
# and then use PyInstaller to create the executable.

import tkinter as tk
from tkinter import filedialog
from PIL import Image

def resize_image():
    input_file = filedialog.askopenfilename(title="Select input PSD file", filetypes=[("PSD files", "*.psd")])
    if not input_file:
        return

    output_file = filedialog.asksaveasfilename(title="Select output file", defaultextension=".png", filetypes=[("PNG files", "*.png")])
    if not output_file:
        return

    try:
        width = int(width_entry.get())
        height = int(height_entry.get())

        img = Image.open(input_file)
        resized_img = img.resize((width, height), Image.Resampling.LANCZOS)
        resized_img.save(output_file)
        status_label.config(text=f"Resized '{input_file}' to '{output_file}' successfully.")

    except FileNotFoundError:
        status_label.config(text=f"Error: Input file '{input_file}' not found.")
    except ValueError:
        status_label.config(text="Error: Please enter valid integer values for width and height.")
    except Exception as e:
        status_label.config(text=f"An error occurred: {e}")

root = tk.Tk()
root.title("PSD Resizer")

width_label = tk.Label(root, text="Width:")
width_label.grid(row=0, column=0)
width_entry = tk.Entry(root)
width_entry.grid(row=0, column=1)
width_entry.insert(0, "500")

height_label = tk.Label(root, text="Height:")
height_label.grid(row=1, column=0)
height_entry = tk.Entry(root)
height_entry.grid(row=1, column=1)
height_entry.insert(0, "500")

resize_button = tk.Button(root, text="Resize", command=resize_image)
resize_button.grid(row=2, column=0, columnspan=2)

status_label = tk.Label(root, text="")
status_label.grid(row=3, column=0, columnspan=2)

root.mainloop()