# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12d93wgGXhCl-mbU1b8eeGQIjZ9v0KSac
"""

# 🚀 Super Simple Trading Profit Calculator

# Step 1: Ask for user inputs
money_put = float(input("💰 How much money did you put into the trade? ($): "))
buy_price = float(input("📈 At what price did you BUY? : "))
current_price = float(input("📊 What is the price NOW? : "))

# Step 2: Calculate profit/loss
price_change = (current_price - buy_price) / buy_price  # Percentage change
profit_loss = money_put * price_change                  # $ profit or loss

# Step 3: Show results
print("\n📢 Result:")

if profit_loss > 0:
    print(f"✅ You are making +${profit_loss:.2f} profit!")
else:
    print(f"❌ You are losing -${abs(profit_loss):.2f}.")

print(f"📈 That's a {price_change * 100:.2f}% change from your buy price.")